class AllRunner {

    public static void main(String[] args) {

        NoteBook noteBook1 = new NoteBook();
        System.out.println("NoteBook1 Ref: " +noteBook1);
        
        System.out.println("Brand: "+noteBook1.brand);
        System.out.println("Pages: "+noteBook1.pages);
		System.out.println("Price: "+noteBook1.price);
		System.out.println("Color: "+noteBook1.color);
		System.out.println("Ruled: "+noteBook1.ruled);
        System.out.println("Size: "+noteBook1.size);
		System.out.println("Weight: "+noteBook1.weight);
		System.out.println("Type: "+noteBook1.type);
		System.out.println("Cover Type: "+noteBook1.coverType);
		System.out.println("Binding: "+noteBook1.binding);
		System.out.println("Thickness: "+noteBook1.thickness);
		System.out.println("Quality: "+noteBook1.quality);
		System.out.println("Usage: "+noteBook1.usage);
		System.out.println("Waterproof: "+noteBook1.waterproof);
		System.out.println("Manufacturer: "+noteBook1.manufacturer);
		System.out.println("Warranty: "+noteBook1.warranty);
		System.out.println("Country: "+noteBook1.country);
		System.out.println("Paper Type: "+noteBook1.paperType);
		System.out.println("Recycled: "+noteBook1.recycled);
		System.out.println("Design: "+noteBook1.design);
		System.out.println("Edition: "+noteBook1.edition);
		System.out.println("Rating: "+noteBook1.rating);
		System.out.println("Availability: "+noteBook1.availability);
		System.out.println("Code: "+noteBook1.code);
		System.out.println("Language: "+noteBook1.language);
		System.out.println("Category: "+noteBook1.category);
		
		NoteBook noteBook2 = new NoteBook();
		System.out.println("NoteBook2 Ref: " +noteBook2);
		
		System.out.println("Brand: "+noteBook2.brand);
        System.out.println("Pages: "+noteBook2.pages);
		System.out.println("Price: "+noteBook2.price);
		System.out.println("Color: "+noteBook2.color);
		System.out.println("Ruled: "+noteBook2.ruled);
        System.out.println("Size: "+noteBook2.size);
		System.out.println("Weight: "+noteBook2.weight);
		System.out.println("Type: "+noteBook2.type);
		System.out.println("Cover Type: "+noteBook2.coverType);
		System.out.println("Binding: "+noteBook2.binding);
		System.out.println("Thickness: "+noteBook2.thickness);
		System.out.println("Quality: "+noteBook2.quality);
		System.out.println("Usage: "+noteBook2.usage);
		System.out.println("Waterproof: "+noteBook2.waterproof);
		System.out.println("Manufacturer: "+noteBook2.manufacturer);
		System.out.println("Warranty: "+noteBook2.warranty);
		System.out.println("Country: "+noteBook2.country);
		System.out.println("Paper Type: "+noteBook2.paperType);
		System.out.println("Recycled: "+noteBook2.recycled);
		System.out.println("Design: "+noteBook2.design);
		System.out.println("Edition: "+noteBook2.edition);
		System.out.println("Rating: "+noteBook2.rating);
		System.out.println("Availability: "+noteBook2.availability);
		System.out.println("Code: "+noteBook2.code);
		System.out.println("Language: "+noteBook2.language);
		System.out.println("Category: "+noteBook2.category);
		
		System.out.println("\n-----------------------------------------\n");
		
        Clock clock1 = new Clock();
        System.out.println("Clock1 Ref: " + clock1);
     
        System.out.println("Brand: "+clock1.brand);
		System.out.println("Type: "+clock1.type);
		System.out.println("Price: "+clock1.price);
		System.out.println("Color: "+clock1.color);
		System.out.println("digital: "+clock1.digital);
		System.out.println("Shape: "+clock1.shape);
		System.out.println("Weight: "+clock1.weight);
		System.out.println("Material: "+clock1.material);
		System.out.println("Battery Life: "+clock1.batteryLife);
		System.out.println("Display: "+clock1.display);
		System.out.println("Usage: "+clock1.usage);
		System.out.println("Alarm: "+clock1.alarm);
		System.out.println("Manufacturer: "+clock1.manufacturer);
		System.out.println("Warranty: "+clock1.warranty);
		System.out.println("Country: "+clock1.country);
		System.out.println("Design: "+clock1.design);
		System.out.println("Edition: "+clock1.edition);
		System.out.println("Rating: "+clock1.rating);
		System.out.println("Availability: "+clock1.availability);
		System.out.println("Code: "+clock1.code);
		System.out.println("Language: "+clock1.language);
		System.out.println("Category: "+clock1.category);
		System.out.println("Power Source: "+clock1.powerSource);
		System.out.println("Smart: "+clock1.smart);
		System.out.println("Size: "+clock1.size);
		System.out.println("Model: "+clock1.model);
		
		Clock clock2 = new Clock();
		System.out.println("Clock2 Ref: " + clock2);
		
		System.out.println("Brand: "+clock2.brand);
		System.out.println("Type: "+clock2.type);
		System.out.println("Price: "+clock2.price);
		System.out.println("Color: "+clock2.color);
		System.out.println("digital: "+clock2.digital);
		System.out.println("Shape: "+clock2.shape);
		System.out.println("Weight: "+clock2.weight);
		System.out.println("Material: "+clock2.material);
		System.out.println("Battery Life: "+clock2.batteryLife);
		System.out.println("Display: "+clock2.display);
		System.out.println("Usage: "+clock2.usage);
		System.out.println("Alarm: "+clock2.alarm);
		System.out.println("Manufacturer: "+clock2.manufacturer);
		System.out.println("Warranty: "+clock2.warranty);
		System.out.println("Country: "+clock2.country);
		System.out.println("Design: "+clock2.design);
		System.out.println("Edition: "+clock2.edition);
		System.out.println("Rating: "+clock2.rating);
		System.out.println("Availability: "+clock2.availability);
		System.out.println("Code: "+clock2.code);
		System.out.println("Language: "+clock2.language);
		System.out.println("Category: "+clock2.category);
		System.out.println("Power Source: "+clock2.powerSource);
		System.out.println("Smart: "+clock2.smart);
		System.out.println("Size: "+clock2.size);
		System.out.println("Model: "+clock2.model);
		
		System.out.println("\n-----------------------------------------\n");

        Bangle bangle1 = new Bangle();
		System.out.println("Bangle1 Ref: " + bangle1);
		
		System.out.println("Material: "+bangle1.material);
		System.out.println("Color: "+bangle1.color);
		System.out.println("Design: "+bangle1.design);
		System.out.println("Size: "+bangle1.size);
		System.out.println("Type: "+bangle1.type);
		System.out.println("Brand: "+bangle1.brand);
		System.out.println("Usage: "+bangle1.usage);
		System.out.println("Manufacturer: "+bangle1.manufacturer);
		System.out.println("Country: "+bangle1.country);
		System.out.println("Availability: "+bangle1.availability);
		System.out.println("Code: "+bangle1.code);
		System.out.println("Category: "+bangle1.category);
		System.out.println("Style: "+bangle1.style);
		System.out.println("Finish: "+bangle1.finish);
		System.out.println("Occasion: "+bangle1.occasion);
		System.out.println("Pattern: "+bangle1.pattern);
		System.out.println("Quantity: "+bangle1.quantity);
		System.out.println("Warranty: "+bangle1.warranty);
		System.out.println("Price: "+bangle1.price);
		System.out.println("Weight: "+bangle1.weight);
		System.out.println("Rating: "+bangle1.rating);
		System.out.println("Adjustable: "+bangle1.adjustable);
		System.out.println("Handmade: "+bangle1.handmade);
		System.out.println("Waterproof: "+bangle1.waterproof);
		System.out.println("Durable: "+bangle1.durable);
		System.out.println("Polished: "+bangle1.polished); 
		
        Bangle bangle2 = new Bangle();
        System.out.println("Bangle2 Ref: " + bangle2);
		
        System.out.println("Material: "+bangle2.material);
		System.out.println("Color: "+bangle2.color);
		System.out.println("Design: "+bangle2.design);
		System.out.println("Size: "+bangle2.size);
		System.out.println("Type: "+bangle2.type);
		System.out.println("Brand: "+bangle2.brand);
		System.out.println("Usage: "+bangle2.usage);
		System.out.println("Manufacturer: "+bangle2.manufacturer);
		System.out.println("Country: "+bangle2.country);
		System.out.println("Availability: "+bangle2.availability);
		System.out.println("Code: "+bangle2.code);
		System.out.println("Category: "+bangle2.category);
		System.out.println("Style: "+bangle2.style);
		System.out.println("Finish: "+bangle2.finish);
		System.out.println("Occasion: "+bangle2.occasion);
		System.out.println("Pattern: "+bangle2.pattern);
		System.out.println("Quantity: "+bangle2.quantity);
		System.out.println("Warranty: "+bangle2.warranty);
		System.out.println("Price: "+bangle2.price);
		System.out.println("Weight: "+bangle2.weight);
		System.out.println("Rating: "+bangle2.rating);
		System.out.println("Adjustable: "+bangle2.adjustable);
		System.out.println("Handmade: "+bangle2.handmade);
		System.out.println("Waterproof: "+bangle2.waterproof);
		System.out.println("Durable: "+bangle2.durable);
		System.out.println("Polished: "+bangle2.polished); 
		
		System.out.println("\n-----------------------------------------\n");

        Engine engine1 = new Engine();
		System.out.println("Engine1 Ref: " + engine1);

		System.out.println("Type: " + engine1.type);
		System.out.println("Brand: " + engine1.brand);
		System.out.println("Power: " + engine1.power);
		System.out.println("Cylinders: " + engine1.cylinders);
		System.out.println("Capacity: " + engine1.capacity);
		System.out.println("FuelType: " + engine1.fuelType);
		System.out.println("Turbo: " + engine1.turbo);
		System.out.println("Weight: " + engine1.weight);
		System.out.println("CoolingSystem: " + engine1.coolingSystem);
		System.out.println("IgnitionType: " + engine1.ignitionType);
		System.out.println("Usage: " + engine1.usage);
		System.out.println("Manufacturer: " + engine1.manufacturer);
		System.out.println("Warranty: " + engine1.warranty);
		System.out.println("Country: " + engine1.country);
		System.out.println("Model: " + engine1.model);
		System.out.println("Version: " + engine1.version);
		System.out.println("Efficiency: " + engine1.efficiency);
		System.out.println("EmissionType: " + engine1.emissionType);
		System.out.println("Electric: " + engine1.electric);
		System.out.println("Color: " + engine1.color);
		System.out.println("Design: " + engine1.design);
		System.out.println("Code: " + engine1.code);
		System.out.println("Category: " + engine1.category);
		System.out.println("Availability: " + engine1.availability);
		System.out.println("Price: " + engine1.price);
		System.out.println("Durable: " + engine1.durable);

		Engine engine2 = new Engine();
		System.out.println("Engine2 Ref: " + engine2);
		
		System.out.println("Type: " + engine2.type);
		System.out.println("Brand: " + engine2.brand);
		System.out.println("Power: " + engine2.power);
		System.out.println("Cylinders: " + engine2.cylinders);
		System.out.println("Capacity: " + engine2.capacity);
		System.out.println("FuelType: " + engine2.fuelType);
		System.out.println("Turbo: " + engine2.turbo);
		System.out.println("Weight: " + engine2.weight);
		System.out.println("CoolingSystem: " + engine2.coolingSystem);
		System.out.println("IgnitionType: " + engine2.ignitionType);
		System.out.println("Usage: " + engine2.usage);
		System.out.println("Manufacturer: " + engine2.manufacturer);
		System.out.println("Warranty: " + engine2.warranty);
		System.out.println("Country: " + engine2.country);
		System.out.println("Model: " + engine2.model);
		System.out.println("Version: " + engine2.version);
		System.out.println("Efficiency: " + engine2.efficiency);
		System.out.println("EmissionType: " + engine2.emissionType);
		System.out.println("Electric: " + engine2.electric);
		System.out.println("Color: " + engine2.color);
		System.out.println("Design: " + engine2.design);
		System.out.println("Code: " + engine2.code);
		System.out.println("Category: " + engine2.category);
		System.out.println("Availability: " + engine2.availability);
		System.out.println("Price: " + engine2.price);
		System.out.println("Durable: " + engine2.durable);
		
		System.out.println("\n-----------------------------------------\n");

        Monitor monitor1 = new Monitor();
		System.out.println("Monitor1 Ref: " + monitor1);

		System.out.println("Brand: " + monitor1.brand);
		System.out.println("Type: " + monitor1.type);
		System.out.println("Price: " + monitor1.price);
		System.out.println("Color: " + monitor1.color);
		System.out.println("Size: " + monitor1.size);
		System.out.println("Resolution: " + monitor1.resolution);
		System.out.println("RefreshRate: " + monitor1.refreshRate);
		System.out.println("PanelType: " + monitor1.panelType);
		System.out.println("Curved: " + monitor1.curved);
		System.out.println("Connectivity: " + monitor1.connectivity);
		System.out.println("Weight: " + monitor1.weight);
		System.out.println("Usage: " + monitor1.usage);
		System.out.println("Manufacturer: " + monitor1.manufacturer);
		System.out.println("Warranty: " + monitor1.warranty);
		System.out.println("Country: " + monitor1.country);
		System.out.println("Model: " + monitor1.model);
		System.out.println("Version: " + monitor1.version);
		System.out.println("Rating: " + monitor1.rating);
		System.out.println("DisplayType: " + monitor1.displayType);
		System.out.println("Touch: " + monitor1.touch);
		System.out.println("Design: " + monitor1.design);
		System.out.println("Code: " + monitor1.code);
		System.out.println("Category: " + monitor1.category);
		System.out.println("Availability: " + monitor1.availability);
		System.out.println("HDMI: " + monitor1.hdmi);
		System.out.println("Durable: " + monitor1.durable);

		Monitor monitor2 = new Monitor();
		System.out.println("Monitor2 Ref: " + monitor2);
		
		System.out.println("Brand: " + monitor2.brand);
		System.out.println("Type: " + monitor2.type);
		System.out.println("Price: " + monitor2.price);
		System.out.println("Color: " + monitor2.color);
		System.out.println("Size: " + monitor2.size);
		System.out.println("Resolution: " + monitor2.resolution);
		System.out.println("RefreshRate: " + monitor2.refreshRate);
		System.out.println("PanelType: " + monitor2.panelType);
		System.out.println("Curved: " + monitor2.curved);
		System.out.println("Connectivity: " + monitor2.connectivity);
		System.out.println("Weight: " + monitor2.weight);
		System.out.println("Usage: " + monitor2.usage);
		System.out.println("Manufacturer: " + monitor2.manufacturer);
		System.out.println("Warranty: " + monitor2.warranty);
		System.out.println("Country: " + monitor2.country);
		System.out.println("Model: " + monitor2.model);
		System.out.println("Version: " + monitor2.version);
		System.out.println("Rating: " + monitor2.rating);
		System.out.println("DisplayType: " + monitor2.displayType);
		System.out.println("Touch: " + monitor2.touch);
		System.out.println("Design: " + monitor2.design);
		System.out.println("Code: " + monitor2.code);
		System.out.println("Category: " + monitor2.category);
		System.out.println("Availability: " + monitor2.availability);
		System.out.println("HDMI: " + monitor2.hdmi);
		System.out.println("Durable: " + monitor2.durable);
		
		System.out.println("\n-----------------------------------------\n");

        Generator generator1 = new Generator();
		System.out.println("Generator1 Ref: " + generator1);

		System.out.println("Brand: " + generator1.brand);
		System.out.println("Type: " + generator1.type);
		System.out.println("Power: " + generator1.power);
		System.out.println("FuelType: " + generator1.fuelType);
		System.out.println("Portable: " + generator1.portable);
		System.out.println("Weight: " + generator1.weight);
		System.out.println("CoolingSystem: " + generator1.coolingSystem);
		System.out.println("Usage: " + generator1.usage);
		System.out.println("Manufacturer: " + generator1.manufacturer);
		System.out.println("Warranty: " + generator1.warranty);
		System.out.println("Country: " + generator1.country);
		System.out.println("Model: " + generator1.model);
		System.out.println("Version: " + generator1.version);
		System.out.println("Efficiency: " + generator1.efficiency);
		System.out.println("Phase: " + generator1.phase);
		System.out.println("ElectricStart: " + generator1.electricStart);
		System.out.println("Color: " + generator1.color);
		System.out.println("Design: " + generator1.design);
		System.out.println("Code: " + generator1.code);
		System.out.println("Category: " + generator1.category);
		System.out.println("Availability: " + generator1.availability);
		System.out.println("Price: " + generator1.price);
		System.out.println("Durable: " + generator1.durable);
		System.out.println("Runtime: " + generator1.runtime);
		System.out.println("NoiseLevel: " + generator1.noiseLevel);
		System.out.println("Voltage: " + generator1.voltage);

		Generator generator2 = new Generator();
		System.out.println("Generator2 Ref: " + generator2);
		
		System.out.println("Brand: " + generator2.brand);
		System.out.println("Type: " + generator2.type);
		System.out.println("Power: " + generator2.power);
		System.out.println("FuelType: " + generator2.fuelType);
		System.out.println("Portable: " + generator2.portable);
		System.out.println("Weight: " + generator2.weight);
		System.out.println("CoolingSystem: " + generator2.coolingSystem);
		System.out.println("Usage: " + generator2.usage);
		System.out.println("Manufacturer: " + generator2.manufacturer);
		System.out.println("Warranty: " + generator2.warranty);
		System.out.println("Country: " + generator2.country);
		System.out.println("Model: " + generator2.model);
		System.out.println("Version: " + generator2.version);
		System.out.println("Efficiency: " + generator2.efficiency);
		System.out.println("Phase: " + generator2.phase);
		System.out.println("ElectricStart: " + generator2.electricStart);
		System.out.println("Color: " + generator2.color);
		System.out.println("Design: " + generator2.design);
		System.out.println("Code: " + generator2.code);
		System.out.println("Category: " + generator2.category);
		System.out.println("Availability: " + generator2.availability);
		System.out.println("Price: " + generator2.price);
		System.out.println("Durable: " + generator2.durable);
		System.out.println("Runtime: " + generator2.runtime);
		System.out.println("NoiseLevel: " + generator2.noiseLevel);
		System.out.println("Voltage: " + generator2.voltage);
		
		System.out.println("\n-----------------------------------------\n");
        

        Arduino arduino1 = new Arduino();
		System.out.println("Arduino1 Ref: " + arduino1);

		System.out.println("BoardType: " + arduino1.boardType);
		System.out.println("Brand: " + arduino1.brand);
		System.out.println("Price: " + arduino1.price);
		System.out.println("Microcontroller: " + arduino1.microcontroller);
		System.out.println("DigitalPins: " + arduino1.digitalPins);
		System.out.println("AnalogPins: " + arduino1.analogPins);
		System.out.println("ClockSpeed: " + arduino1.clockSpeed);
		System.out.println("Voltage: " + arduino1.voltage);
		System.out.println("USB: " + arduino1.usbSupport);
		System.out.println("Weight: " + arduino1.weight);
		System.out.println("Usage: " + arduino1.usage);
		System.out.println("Manufacturer: " + arduino1.manufacturer);
		System.out.println("Warranty: " + arduino1.warranty);
		System.out.println("Country: " + arduino1.country);
		System.out.println("Model: " + arduino1.model);
		System.out.println("Version: " + arduino1.version);
		System.out.println("Rating: " + arduino1.rating);
		System.out.println("Connectivity: " + arduino1.connectivity);
		System.out.println("WiFi: " + arduino1.wifi);
		System.out.println("Bluetooth: " + arduino1.bluetooth);
		System.out.println("Design: " + arduino1.design);
		System.out.println("Code: " + arduino1.code);
		System.out.println("Category: " + arduino1.category);
		System.out.println("Availability: " + arduino1.availability);
		System.out.println("Programmable: " + arduino1.programmable);
		System.out.println("Durable: " + arduino1.durable);

		Arduino arduino2 = new Arduino();
		System.out.println("Arduino2 Ref: " + arduino2);
		
		System.out.println("BoardType: " + arduino2.boardType);
		System.out.println("Brand: " + arduino2.brand);
		System.out.println("Price: " + arduino2.price);
		System.out.println("Microcontroller: " + arduino2.microcontroller);
		System.out.println("DigitalPins: " + arduino2.digitalPins);
		System.out.println("AnalogPins: " + arduino2.analogPins);
		System.out.println("ClockSpeed: " + arduino2.clockSpeed);
		System.out.println("Voltage: " + arduino2.voltage);
		System.out.println("USB: " + arduino2.usbSupport);
		System.out.println("Weight: " + arduino2.weight);
		System.out.println("Usage: " + arduino2.usage);
		System.out.println("Manufacturer: " + arduino2.manufacturer);
		System.out.println("Warranty: " + arduino2.warranty);
		System.out.println("Country: " + arduino2.country);
		System.out.println("Model: " + arduino2.model);
		System.out.println("Version: " + arduino2.version);
		System.out.println("Rating: " + arduino2.rating);
		System.out.println("Connectivity: " + arduino2.connectivity);
		System.out.println("WiFi: " + arduino2.wifi);
		System.out.println("Bluetooth: " + arduino2.bluetooth);
		System.out.println("Design: " + arduino2.design);
		System.out.println("Code: " + arduino2.code);
		System.out.println("Category: " + arduino2.category);
		System.out.println("Availability: " + arduino2.availability);
		System.out.println("Programmable: " + arduino2.programmable);
		System.out.println("Durable: " + arduino2.durable);
		
		System.out.println("\n-----------------------------------------\n");

        Shampoo shampoo1 = new Shampoo();
		System.out.println("Shampoo1 Ref: " + shampoo1);

		System.out.println("Brand: " + shampoo1.brand);
		System.out.println("Type: " + shampoo1.type);
		System.out.println("Price: " + shampoo1.price);
		System.out.println("Fragrance: " + shampoo1.fragrance);
		System.out.println("Color: " + shampoo1.color);
		System.out.println("Volume: " + shampoo1.volume);
		System.out.println("Herbal: " + shampoo1.herbal);
		System.out.println("HairType: " + shampoo1.hairType);
		System.out.println("Usage: " + shampoo1.usage);
		System.out.println("Manufacturer: " + shampoo1.manufacturer);
		System.out.println("Warranty: " + shampoo1.warranty);
		System.out.println("Country: " + shampoo1.country);
		System.out.println("Model: " + shampoo1.model);
		System.out.println("Version: " + shampoo1.version);
		System.out.println("Rating: " + shampoo1.rating);
		System.out.println("Ingredients: " + shampoo1.ingredients);
		System.out.println("SulfateFree: " + shampoo1.sulfateFree);
		System.out.println("ParabenFree: " + shampoo1.parabenFree);
		System.out.println("Design: " + shampoo1.design);
		System.out.println("Code: " + shampoo1.code);
		System.out.println("Category: " + shampoo1.category);
		System.out.println("Availability: " + shampoo1.availability);
		System.out.println("Organic: " + shampoo1.organic);
		System.out.println("Medicated: " + shampoo1.medicated);
		System.out.println("Packaging: " + shampoo1.packaging);
		System.out.println("Durable: " + shampoo1.durable);

		Shampoo shampoo2 = new Shampoo();
		System.out.println("Shampoo2 Ref: " + shampoo2);

		System.out.println("Brand: " + shampoo2.brand);
		System.out.println("Type: " + shampoo2.type);
		System.out.println("Price: " + shampoo2.price);
		System.out.println("Fragrance: " + shampoo2.fragrance);
		System.out.println("Color: " + shampoo2.color);
		System.out.println("Volume: " + shampoo2.volume);
		System.out.println("Herbal: " + shampoo2.herbal);
		System.out.println("HairType: " + shampoo2.hairType);
		System.out.println("Usage: " + shampoo2.usage);
		System.out.println("Manufacturer: " + shampoo2.manufacturer);
		System.out.println("Warranty: " + shampoo2.warranty);
		System.out.println("Country: " + shampoo2.country);
		System.out.println("Model: " + shampoo2.model);
		System.out.println("Version: " + shampoo2.version);
		System.out.println("Rating: " + shampoo2.rating);
		System.out.println("Ingredients: " + shampoo2.ingredients);
		System.out.println("SulfateFree: " + shampoo2.sulfateFree);
		System.out.println("ParabenFree: " + shampoo2.parabenFree);
		System.out.println("Design: " + shampoo2.design);
		System.out.println("Code: " + shampoo2.code);
		System.out.println("Category: " + shampoo2.category);
		System.out.println("Availability: " + shampoo2.availability);
		System.out.println("Organic: " + shampoo2.organic);
		System.out.println("Medicated: " + shampoo2.medicated);
		System.out.println("Packaging: " + shampoo2.packaging);
		System.out.println("Durable: " + shampoo2.durable);
		
		System.out.println("\n-----------------------------------------\n");

        Iron iron1 = new Iron();
		System.out.println("Iron1 Ref: " + iron1);

		System.out.println("Brand: " + iron1.brand);
		System.out.println("Type: " + iron1.type);
		System.out.println("Price: " + iron1.price);
		System.out.println("Color: " + iron1.color);
		System.out.println("Power: " + iron1.power);
		System.out.println("Steam: " + iron1.steam);
		System.out.println("Soleplate: " + iron1.soleplate);
		System.out.println("Usage: " + iron1.usage);
		System.out.println("Manufacturer: " + iron1.manufacturer);
		System.out.println("Warranty: " + iron1.warranty);
		System.out.println("Country: " + iron1.country);
		System.out.println("Model: " + iron1.model);
		System.out.println("Version: " + iron1.version);
		System.out.println("Rating: " + iron1.rating);
		System.out.println("TemperatureControl: " + iron1.temperatureControl);
		System.out.println("AutoCut: " + iron1.autoCut);
		System.out.println("Design: " + iron1.design);
		System.out.println("Code: " + iron1.code);
		System.out.println("Category: " + iron1.category);
		System.out.println("Availability: " + iron1.availability);
		System.out.println("Weight: " + iron1.weight);
		System.out.println("Cordless: " + iron1.cordless);
		System.out.println("Voltage: " + iron1.voltage);
		System.out.println("Durable: " + iron1.durable);
		System.out.println("Material: " + iron1.material);
		System.out.println("Size: " + iron1.size);

		Iron iron2 = new Iron();
		System.out.println("Iron2 Ref: " + iron2);

		System.out.println("Brand: " + iron2.brand);
		System.out.println("Type: " + iron2.type);
		System.out.println("Price: " + iron2.price);
		System.out.println("Color: " + iron2.color);
		System.out.println("Power: " + iron2.power);
		System.out.println("Steam: " + iron2.steam);
		System.out.println("Soleplate: " + iron2.soleplate);
		System.out.println("Usage: " + iron2.usage);
		System.out.println("Manufacturer: " + iron2.manufacturer);
		System.out.println("Warranty: " + iron2.warranty);
		System.out.println("Country: " + iron2.country);
		System.out.println("Model: " + iron2.model);
		System.out.println("Version: " + iron2.version);
		System.out.println("Rating: " + iron2.rating);
		System.out.println("TemperatureControl: " + iron2.temperatureControl);
		System.out.println("AutoCut: " + iron2.autoCut);
		System.out.println("Design: " + iron2.design);
		System.out.println("Code: " + iron2.code);
		System.out.println("Category: " + iron2.category);
		System.out.println("Availability: " + iron2.availability);
		System.out.println("Weight: " + iron2.weight);
		System.out.println("Cordless: " + iron2.cordless);
		System.out.println("Voltage: " + iron2.voltage);
		System.out.println("Durable: " + iron2.durable);
		System.out.println("Material: " + iron2.material);
		System.out.println("Size: " + iron2.size);
		
		System.out.println("\n-----------------------------------------\n");

        Stand stand1 = new Stand();
		System.out.println("Stand1 Ref: " + stand1);

		System.out.println("Brand: " + stand1.brand);
		System.out.println("Type: " + stand1.type);
		System.out.println("Price: " + stand1.price);
		System.out.println("Material: " + stand1.material);
		System.out.println("Color: " + stand1.color);
		System.out.println("Height: " + stand1.height);
		System.out.println("Adjustable: " + stand1.adjustable);
		System.out.println("Usage: " + stand1.usage);
		System.out.println("Manufacturer: " + stand1.manufacturer);
		System.out.println("Warranty: " + stand1.warranty);
		System.out.println("Country: " + stand1.country);
		System.out.println("Model: " + stand1.model);
		System.out.println("Version: " + stand1.version);
		System.out.println("Rating: " + stand1.rating);
		System.out.println("Design: " + stand1.design);
		System.out.println("Code: " + stand1.code);
		System.out.println("Category: " + stand1.category);
		System.out.println("Availability: " + stand1.availability);
		System.out.println("Weight: " + stand1.weight);
		System.out.println("Foldable: " + stand1.foldable);
		System.out.println("Shape: " + stand1.shape);
		System.out.println("Durable: " + stand1.durable);
		System.out.println("Finish: " + stand1.finish);
		System.out.println("Size: " + stand1.size);
		System.out.println("Purpose: " + stand1.purpose);
		System.out.println("Portable: " + stand1.portable);

		Stand stand2 = new Stand();
		System.out.println("Stand2 Ref: " + stand2);

		System.out.println("Brand: " + stand2.brand);
		System.out.println("Type: " + stand2.type);
		System.out.println("Price: " + stand2.price);
		System.out.println("Material: " + stand2.material);
		System.out.println("Color: " + stand2.color);
		System.out.println("Height: " + stand2.height);
		System.out.println("Adjustable: " + stand2.adjustable);
		System.out.println("Usage: " + stand2.usage);
		System.out.println("Manufacturer: " + stand2.manufacturer);
		System.out.println("Warranty: " + stand2.warranty);
		System.out.println("Country: " + stand2.country);
		System.out.println("Model: " + stand2.model);
		System.out.println("Version: " + stand2.version);
		System.out.println("Rating: " + stand2.rating);
		System.out.println("Design: " + stand2.design);
		System.out.println("Code: " + stand2.code);
		System.out.println("Category: " + stand2.category);
		System.out.println("Availability: " + stand2.availability);
		System.out.println("Weight: " + stand2.weight);
		System.out.println("Foldable: " + stand2.foldable);
		System.out.println("Shape: " + stand2.shape);
		System.out.println("Durable: " + stand2.durable);
		System.out.println("Finish: " + stand2.finish);
		System.out.println("Size: " + stand2.size);
		System.out.println("Purpose: " + stand2.purpose);
		System.out.println("Portable: " + stand2.portable);
		
		System.out.println("\n-----------------------------------------\n");
    }
}