class CabinetRunner {
    public static void main(String[] args) {

        Cabinet cabinet1 = new Cabinet();
		Cabinet cabinet2= new Cabinet();
		Cabinet cabinet3 = new Cabinet();
		Cabinet cabinet4 = new Cabinet();
		Cabinet cabinet5 = new Cabinet();
		Cabinet cabinet6 = new Cabinet();
		Cabinet cabinet7 = new Cabinet();
		Cabinet cabinet8 = new Cabinet();
		Cabinet cabinet9 = new Cabinet();
		Cabinet cabinet10 = new Cabinet();
		
		System.out.println("Material: " + cabinet1.material);
        System.out.println("Color: " + cabinet1.color);
        System.out.println("Shelves: " + cabinet1.shelves);
        System.out.println("Price: " + cabinet1.price);
        System.out.println("Has Lock: " + cabinet1.hasLock);
        System.out.println("Brand: " + cabinet1.brand);
        System.out.println("Height: " + cabinet1.height);
        System.out.println("Width: " + cabinet1.width);
        System.out.println("Weight: " + cabinet1.weight);
        System.out.println("Type: " + cabinet1.type);
        System.out.println("Location: " + cabinet1.location);
        System.out.println("Capacity: " + cabinet1.capacity);
        System.out.println("Design: " + cabinet1.design);
        System.out.println("Movable: " + cabinet1.movable);
        System.out.println("Finish: " + cabinet1.finish);
        cabinet1.brand = "Godrej";
        cabinet1.height = 5.5;
        cabinet1.width = 3.0;
        cabinet1.weight = 40;
        cabinet1.type = "Storage";
        cabinet1.location = "Office";
        cabinet1.capacity = 100;
        cabinet1.design = "Modern";
        cabinet1.movable = true;
        cabinet1.finish = "Matte";
        System.out.println("Material: " + cabinet1.material);
        System.out.println("Color: " + cabinet1.color);
        System.out.println("Shelves: " + cabinet1.shelves);
        System.out.println("Price: " + cabinet1.price);
        System.out.println("Has Lock: " + cabinet1.hasLock);
        System.out.println("Brand: " + cabinet1.brand);
        System.out.println("Height: " + cabinet1.height);
        System.out.println("Width: " + cabinet1.width);
        System.out.println("Weight: " + cabinet1.weight);
        System.out.println("Type: " + cabinet1.type);
        System.out.println("Location: " + cabinet1.location);
        System.out.println("Capacity: " + cabinet1.capacity);
        System.out.println("Design: " + cabinet1.design);
        System.out.println("Movable: " + cabinet1.movable);
        System.out.println("Finish: " + cabinet1.finish);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + cabinet2.material);
        System.out.println("Color: " + cabinet2.color);
        System.out.println("Shelves: " + cabinet2.shelves);
        System.out.println("Price: " + cabinet2.price);
        System.out.println("Has Lock: " + cabinet2.hasLock);
        System.out.println("Brand: " + cabinet2.brand);
        System.out.println("Height: " + cabinet2.height);
        System.out.println("Width: " + cabinet2.width);
        System.out.println("Weight: " + cabinet2.weight);
        System.out.println("Type: " + cabinet2.type);
        System.out.println("Location: " + cabinet2.location);
        System.out.println("Capacity: " + cabinet2.capacity);
        System.out.println("Design: " + cabinet2.design);
        System.out.println("Movable: " + cabinet2.movable);
        System.out.println("Finish: " + cabinet2.finish);
		cabinet2.brand = "Ikea";
		cabinet2.height = 6.0;
		cabinet2.width = 2.5;
		cabinet2.weight = 35;
		cabinet2.type = "Kitchen";
		cabinet2.location = "Kitchen";
		cabinet2.capacity = 80;
		cabinet2.design = "Classic";
		cabinet2.movable = false;
		cabinet2.finish = "Glossy";
		System.out.println("Material: " + cabinet2.material);
        System.out.println("Color: " + cabinet2.color);
        System.out.println("Shelves: " + cabinet2.shelves);
        System.out.println("Price: " + cabinet2.price);
        System.out.println("Has Lock: " + cabinet2.hasLock);
        System.out.println("Brand: " + cabinet2.brand);
        System.out.println("Height: " + cabinet2.height);
        System.out.println("Width: " + cabinet2.width);
        System.out.println("Weight: " + cabinet2.weight);
        System.out.println("Type: " + cabinet2.type);
        System.out.println("Location: " + cabinet2.location);
        System.out.println("Capacity: " + cabinet2.capacity);
        System.out.println("Design: " + cabinet2.design);
        System.out.println("Movable: " + cabinet2.movable);
        System.out.println("Finish: " + cabinet2.finish);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + cabinet3.material);
        System.out.println("Color: " + cabinet3.color);
        System.out.println("Shelves: " + cabinet3.shelves);
        System.out.println("Price: " + cabinet3.price);
        System.out.println("Has Lock: " + cabinet3.hasLock);
        System.out.println("Brand: " + cabinet3.brand);
        System.out.println("Height: " + cabinet3.height);
        System.out.println("Width: " + cabinet3.width);
        System.out.println("Weight: " + cabinet3.weight);
        System.out.println("Type: " + cabinet3.type);
        System.out.println("Location: " + cabinet3.location);
        System.out.println("Capacity: " + cabinet3.capacity);
        System.out.println("Design: " + cabinet3.design);
        System.out.println("Movable: " + cabinet3.movable);
        System.out.println("Finish: " + cabinet3.finish);
		cabinet3.brand = "Nilkamal";
		cabinet3.height = 5.0;
		cabinet3.width = 3.5;
		cabinet3.weight = 45;
		cabinet3.type = "Wardrobe";
		cabinet3.location = "Bedroom";
		cabinet3.capacity = 120;
		cabinet3.design = "Modern";
		cabinet3.movable = false;
		cabinet3.finish = "Matte";
		System.out.println("Material: " + cabinet3.material);
        System.out.println("Color: " + cabinet3.color);
        System.out.println("Shelves: " + cabinet3.shelves);
        System.out.println("Price: " + cabinet3.price);
        System.out.println("Has Lock: " + cabinet3.hasLock);
        System.out.println("Brand: " + cabinet3.brand);
        System.out.println("Height: " + cabinet3.height);
        System.out.println("Width: " + cabinet3.width);
        System.out.println("Weight: " + cabinet3.weight);
        System.out.println("Type: " + cabinet3.type);
        System.out.println("Location: " + cabinet3.location);
        System.out.println("Capacity: " + cabinet3.capacity);
        System.out.println("Design: " + cabinet3.design);
        System.out.println("Movable: " + cabinet3.movable);
        System.out.println("Finish: " + cabinet3.finish);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + cabinet4.material);
        System.out.println("Color: " + cabinet4.color);
        System.out.println("Shelves: " + cabinet4.shelves);
        System.out.println("Price: " + cabinet4.price);
        System.out.println("Has Lock: " + cabinet4.hasLock);
        System.out.println("Brand: " + cabinet4.brand);
        System.out.println("Height: " + cabinet4.height);
        System.out.println("Width: " + cabinet4.width);
        System.out.println("Weight: " + cabinet4.weight);
        System.out.println("Type: " + cabinet4.type);
        System.out.println("Location: " + cabinet4.location);
        System.out.println("Capacity: " + cabinet4.capacity);
        System.out.println("Design: " + cabinet4.design);
        System.out.println("Movable: " + cabinet4.movable);
        System.out.println("Finish: " + cabinet4.finish);
		cabinet4.brand = "Durian";
		cabinet4.height = 4.5;
		cabinet4.width = 2.8;
		cabinet4.weight = 30;
		cabinet4.type = "Storage";
		cabinet4.location = "Hall";
		cabinet4.capacity = 70;
		cabinet4.design = "Vintage";
		cabinet4.movable = true;
		cabinet4.finish = "Wooden";
		System.out.println("Material: " + cabinet4.material);
        System.out.println("Color: " + cabinet4.color);
        System.out.println("Shelves: " + cabinet4.shelves);
        System.out.println("Price: " + cabinet4.price);
        System.out.println("Has Lock: " + cabinet4.hasLock);
        System.out.println("Brand: " + cabinet4.brand);
        System.out.println("Height: " + cabinet4.height);
        System.out.println("Width: " + cabinet4.width);
        System.out.println("Weight: " + cabinet4.weight);
        System.out.println("Type: " + cabinet4.type);
        System.out.println("Location: " + cabinet4.location);
        System.out.println("Capacity: " + cabinet4.capacity);
        System.out.println("Design: " + cabinet4.design);
        System.out.println("Movable: " + cabinet4.movable);
        System.out.println("Finish: " + cabinet4.finish);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + cabinet5.material);
        System.out.println("Color: " + cabinet5.color);
        System.out.println("Shelves: " + cabinet5.shelves);
        System.out.println("Price: " + cabinet5.price);
        System.out.println("Has Lock: " + cabinet5.hasLock);
        System.out.println("Brand: " + cabinet5.brand);
        System.out.println("Height: " + cabinet5.height);
        System.out.println("Width: " + cabinet5.width);
        System.out.println("Weight: " + cabinet5.weight);
        System.out.println("Type: " + cabinet5.type);
        System.out.println("Location: " + cabinet5.location);
        System.out.println("Capacity: " + cabinet5.capacity);
        System.out.println("Design: " + cabinet5.design);
        System.out.println("Movable: " + cabinet5.movable);
        System.out.println("Finish: " + cabinet5.finish);
		cabinet5.brand = "Godrej Interio";
		cabinet5.height = 6.5;
		cabinet5.width = 3.2;
		cabinet5.weight = 50;
		cabinet5.type = "Office";
		cabinet5.location = "Office";
		cabinet5.capacity = 150;
		cabinet5.design = "Professional";
		cabinet5.movable = false;
		cabinet5.finish = "Matte";
		System.out.println("Material: " + cabinet5.material);
        System.out.println("Color: " + cabinet5.color);
        System.out.println("Shelves: " + cabinet5.shelves);
        System.out.println("Price: " + cabinet5.price);
        System.out.println("Has Lock: " + cabinet5.hasLock);
        System.out.println("Brand: " + cabinet5.brand);
        System.out.println("Height: " + cabinet5.height);
        System.out.println("Width: " + cabinet5.width);
        System.out.println("Weight: " + cabinet5.weight);
        System.out.println("Type: " + cabinet5.type);
        System.out.println("Location: " + cabinet5.location);
        System.out.println("Capacity: " + cabinet5.capacity);
        System.out.println("Design: " + cabinet5.design);
        System.out.println("Movable: " + cabinet5.movable);
        System.out.println("Finish: " + cabinet5.finish);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + cabinet6.material);
        System.out.println("Color: " + cabinet6.color);
        System.out.println("Shelves: " + cabinet6.shelves);
        System.out.println("Price: " + cabinet6.price);
        System.out.println("Has Lock: " + cabinet6.hasLock);
        System.out.println("Brand: " + cabinet6.brand);
        System.out.println("Height: " + cabinet6.height);
        System.out.println("Width: " + cabinet6.width);
        System.out.println("Weight: " + cabinet6.weight);
        System.out.println("Type: " + cabinet6.type);
        System.out.println("Location: " + cabinet6.location);
        System.out.println("Capacity: " + cabinet6.capacity);
        System.out.println("Design: " + cabinet6.design);
        System.out.println("Movable: " + cabinet6.movable);
        System.out.println("Finish: " + cabinet6.finish);
		cabinet6.brand = "HomeTown";
		cabinet6.height = 5.2;
		cabinet6.width = 2.9;
		cabinet6.weight = 38;
		cabinet6.type = "Storage";
		cabinet6.location = "Garage";
		cabinet6.capacity = 90;
		cabinet6.design = "Industrial";
		cabinet6.movable = true;
		cabinet6.finish = "Rough";
		System.out.println("Material: " + cabinet6.material);
        System.out.println("Color: " + cabinet6.color);
        System.out.println("Shelves: " + cabinet6.shelves);
        System.out.println("Price: " + cabinet6.price);
        System.out.println("Has Lock: " + cabinet6.hasLock);
        System.out.println("Brand: " + cabinet6.brand);
        System.out.println("Height: " + cabinet6.height);
        System.out.println("Width: " + cabinet6.width);
        System.out.println("Weight: " + cabinet6.weight);
        System.out.println("Type: " + cabinet6.type);
        System.out.println("Location: " + cabinet6.location);
        System.out.println("Capacity: " + cabinet6.capacity);
        System.out.println("Design: " + cabinet6.design);
        System.out.println("Movable: " + cabinet6.movable);
        System.out.println("Finish: " + cabinet6.finish);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + cabinet7.material);
        System.out.println("Color: " + cabinet7.color);
        System.out.println("Shelves: " + cabinet7.shelves);
        System.out.println("Price: " + cabinet7.price);
        System.out.println("Has Lock: " + cabinet7.hasLock);
        System.out.println("Brand: " + cabinet7.brand);
        System.out.println("Height: " + cabinet7.height);
        System.out.println("Width: " + cabinet7.width);
        System.out.println("Weight: " + cabinet7.weight);
        System.out.println("Type: " + cabinet7.type);
        System.out.println("Location: " + cabinet7.location);
        System.out.println("Capacity: " + cabinet7.capacity);
        System.out.println("Design: " + cabinet7.design);
        System.out.println("Movable: " + cabinet7.movable);
        System.out.println("Finish: " + cabinet7.finish);
		cabinet7.brand = "Urban Ladder";
		cabinet7.height = 4.8;
		cabinet7.width = 3.1;
		cabinet7.weight = 42;
		cabinet7.type = "Display";
		cabinet7.location = "Living Room";
		cabinet7.capacity = 60;
		cabinet7.design = "Elegant";
		cabinet7.movable = false;
		cabinet7.finish = "Glossy";
		System.out.println("Material: " + cabinet7.material);
        System.out.println("Color: " + cabinet7.color);
        System.out.println("Shelves: " + cabinet7.shelves);
        System.out.println("Price: " + cabinet7.price);
        System.out.println("Has Lock: " + cabinet7.hasLock);
        System.out.println("Brand: " + cabinet7.brand);
        System.out.println("Height: " + cabinet7.height);
        System.out.println("Width: " + cabinet7.width);
        System.out.println("Weight: " + cabinet7.weight);
        System.out.println("Type: " + cabinet7.type);
        System.out.println("Location: " + cabinet7.location);
        System.out.println("Capacity: " + cabinet7.capacity);
        System.out.println("Design: " + cabinet7.design);
        System.out.println("Movable: " + cabinet7.movable);
        System.out.println("Finish: " + cabinet7.finish);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + cabinet8.material);
        System.out.println("Color: " + cabinet8.color);
        System.out.println("Shelves: " + cabinet8.shelves);
        System.out.println("Price: " + cabinet8.price);
        System.out.println("Has Lock: " + cabinet8.hasLock);
        System.out.println("Brand: " + cabinet8.brand);
        System.out.println("Height: " + cabinet8.height);
        System.out.println("Width: " + cabinet8.width);
        System.out.println("Weight: " + cabinet8.weight);
        System.out.println("Type: " + cabinet8.type);
        System.out.println("Location: " + cabinet8.location);
        System.out.println("Capacity: " + cabinet8.capacity);
        System.out.println("Design: " + cabinet8.design);
        System.out.println("Movable: " + cabinet8.movable);
        System.out.println("Finish: " + cabinet8.finish);
		cabinet8.brand = "Pepperfry";
		cabinet8.height = 5.7;
		cabinet8.width = 2.7;
		cabinet8.weight = 36;
		cabinet8.type = "Wardrobe";
		cabinet8.location = "Bedroom";
		cabinet8.capacity = 110;
		cabinet8.design = "Contemporary";
		cabinet8.movable = false;
		cabinet8.finish = "Matte";
		System.out.println("Material: " + cabinet8.material);
        System.out.println("Color: " + cabinet8.color);
        System.out.println("Shelves: " + cabinet8.shelves);
        System.out.println("Price: " + cabinet8.price);
        System.out.println("Has Lock: " + cabinet8.hasLock);
        System.out.println("Brand: " + cabinet8.brand);
        System.out.println("Height: " + cabinet8.height);
        System.out.println("Width: " + cabinet8.width);
        System.out.println("Weight: " + cabinet8.weight);
        System.out.println("Type: " + cabinet8.type);
        System.out.println("Location: " + cabinet8.location);
        System.out.println("Capacity: " + cabinet8.capacity);
        System.out.println("Design: " + cabinet8.design);
        System.out.println("Movable: " + cabinet8.movable);
        System.out.println("Finish: " + cabinet8.finish);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + cabinet9.material);
        System.out.println("Color: " + cabinet9.color);
        System.out.println("Shelves: " + cabinet9.shelves);
        System.out.println("Price: " + cabinet9.price);
        System.out.println("Has Lock: " + cabinet9.hasLock);
        System.out.println("Brand: " + cabinet9.brand);
        System.out.println("Height: " + cabinet9.height);
        System.out.println("Width: " + cabinet9.width);
        System.out.println("Weight: " + cabinet9.weight);
        System.out.println("Type: " + cabinet9.type);
        System.out.println("Location: " + cabinet9.location);
        System.out.println("Capacity: " + cabinet9.capacity);
        System.out.println("Design: " + cabinet9.design);
        System.out.println("Movable: " + cabinet9.movable);
        System.out.println("Finish: " + cabinet9.finish);
		cabinet9.brand = "Flipkart";
		cabinet9.height = 4.9;
		cabinet9.width = 2.6;
		cabinet9.weight = 33;
		cabinet9.type = "Storage";
		cabinet9.location = "Study";
		cabinet9.capacity = 75;
		cabinet9.design = "Minimal";
		cabinet9.movable = true;
		cabinet9.finish = "Smooth";
		System.out.println("Material: " + cabinet9.material);
        System.out.println("Color: " + cabinet9.color);
        System.out.println("Shelves: " + cabinet9.shelves);
        System.out.println("Price: " + cabinet9.price);
        System.out.println("Has Lock: " + cabinet9.hasLock);
        System.out.println("Brand: " + cabinet9.brand);
        System.out.println("Height: " + cabinet9.height);
        System.out.println("Width: " + cabinet9.width);
        System.out.println("Weight: " + cabinet9.weight);
        System.out.println("Type: " + cabinet9.type);
        System.out.println("Location: " + cabinet9.location);
        System.out.println("Capacity: " + cabinet9.capacity);
        System.out.println("Design: " + cabinet9.design);
        System.out.println("Movable: " + cabinet9.movable);
        System.out.println("Finish: " + cabinet9.finish);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + cabinet10.material);
        System.out.println("Color: " + cabinet10.color);
        System.out.println("Shelves: " + cabinet10.shelves);
        System.out.println("Price: " + cabinet10.price);
        System.out.println("Has Lock: " + cabinet10.hasLock);
        System.out.println("Brand: " + cabinet10.brand);
        System.out.println("Height: " + cabinet10.height);
        System.out.println("Width: " + cabinet10.width);
        System.out.println("Weight: " + cabinet10.weight);
        System.out.println("Type: " + cabinet10.type);
        System.out.println("Location: " + cabinet10.location);
        System.out.println("Capacity: " + cabinet10.capacity);
        System.out.println("Design: " + cabinet10.design);
        System.out.println("Movable: " + cabinet10.movable);
        System.out.println("Finish: " + cabinet10.finish);
		cabinet10.brand = "AmazonBasics";
		cabinet10.height = 5.3;
		cabinet10.width = 3.3;
		cabinet10.weight = 41;
		cabinet10.type = "Office";
		cabinet10.location = "Office";
		cabinet10.capacity = 95;
		cabinet10.design = "Simple";
		cabinet10.movable = true;
		cabinet10.finish = "Matte";
		System.out.println("Material: " + cabinet10.material);
        System.out.println("Color: " + cabinet10.color);
        System.out.println("Shelves: " + cabinet10.shelves);
        System.out.println("Price: " + cabinet10.price);
        System.out.println("Has Lock: " + cabinet10.hasLock);
        System.out.println("Brand: " + cabinet10.brand);
        System.out.println("Height: " + cabinet10.height);
        System.out.println("Width: " + cabinet10.width);
        System.out.println("Weight: " + cabinet10.weight);
        System.out.println("Type: " + cabinet10.type);
        System.out.println("Location: " + cabinet10.location);
        System.out.println("Capacity: " + cabinet10.capacity);
        System.out.println("Design: " + cabinet10.design);
        System.out.println("Movable: " + cabinet10.movable);
        System.out.println("Finish: " + cabinet10.finish);
		System.out.println("\n---------------------------------\n");
	}
}