class ControllerRunner {
    public static void main(String[] args) {

        Controller controller1 = new Controller();
        Controller controller2 = new Controller();
        Controller controller3 = new Controller();
        Controller controller4 = new Controller();
        Controller controller5 = new Controller();
        Controller controller6 = new Controller();
        Controller controller7 = new Controller();
        Controller controller8 = new Controller();
        Controller controller9 = new Controller();
        Controller controller10 = new Controller();

        System.out.println("Type: " + controller1.type);
        System.out.println("Color: " + controller1.color);
        System.out.println("Buttons: " + controller1.buttons);
        System.out.println("Price: " + controller1.price);
        System.out.println("Wireless: " + controller1.wireless);
        System.out.println("Brand: " + controller1.brand);
        System.out.println("Weight: " + controller1.weight);
        System.out.println("Connectivity: " + controller1.connectivity);
        System.out.println("Compatibility: " + controller1.compatibility);
        System.out.println("Usage: " + controller1.usage);
        System.out.println("Vibration: " + controller1.vibration);
        System.out.println("Version: " + controller1.version);
        System.out.println("Warranty: " + controller1.warranty);
        System.out.println("Origin: " + controller1.origin);
        System.out.println("Shape: " + controller1.shape);

        controller1.brand = "Sony";
        controller1.weight = 0.3;
        controller1.connectivity = "Bluetooth";
        controller1.compatibility = "PS5";
        controller1.usage = "Gaming";
        controller1.vibration = true;
        controller1.version = "DualSense";
        controller1.warranty = 1;
        controller1.origin = "Japan";
        controller1.shape = "Ergonomic";

        System.out.println("Type: " + controller1.type);
        System.out.println("Color: " + controller1.color);
        System.out.println("Buttons: " + controller1.buttons);
        System.out.println("Price: " + controller1.price);
        System.out.println("Wireless: " + controller1.wireless);
        System.out.println("Brand: " + controller1.brand);
        System.out.println("Weight: " + controller1.weight);
        System.out.println("Connectivity: " + controller1.connectivity);
        System.out.println("Compatibility: " + controller1.compatibility);
        System.out.println("Usage: " + controller1.usage);
        System.out.println("Vibration: " + controller1.vibration);
        System.out.println("Version: " + controller1.version);
        System.out.println("Warranty: " + controller1.warranty);
        System.out.println("Origin: " + controller1.origin);
        System.out.println("Shape: " + controller1.shape);
        System.out.println("\n---------------------------------\n");

        System.out.println("Type: " + controller2.type);
        System.out.println("Color: " + controller2.color);
        System.out.println("Buttons: " + controller2.buttons);
        System.out.println("Price: " + controller2.price);
        System.out.println("Wireless: " + controller2.wireless);
        System.out.println("Brand: " + controller2.brand);
        System.out.println("Weight: " + controller2.weight);
        System.out.println("Connectivity: " + controller2.connectivity);
        System.out.println("Compatibility: " + controller2.compatibility);
        System.out.println("Usage: " + controller2.usage);
        System.out.println("Vibration: " + controller2.vibration);
        System.out.println("Version: " + controller2.version);
        System.out.println("Warranty: " + controller2.warranty);
        System.out.println("Origin: " + controller2.origin);
        System.out.println("Shape: " + controller2.shape);

        controller2.brand = "Microsoft";
        controller2.weight = 0.35;
        controller2.connectivity = "Wireless";
        controller2.compatibility = "Xbox";
        controller2.usage = "Gaming";
        controller2.vibration = true;
        controller2.version = "Series X";
        controller2.warranty = 1;
        controller2.origin = "USA";
        controller2.shape = "Ergonomic";

        System.out.println("Type: " + controller2.type);
        System.out.println("Color: " + controller2.color);
        System.out.println("Buttons: " + controller2.buttons);
        System.out.println("Price: " + controller2.price);
        System.out.println("Wireless: " + controller2.wireless);
        System.out.println("Brand: " + controller2.brand);
        System.out.println("Weight: " + controller2.weight);
        System.out.println("Connectivity: " + controller2.connectivity);
        System.out.println("Compatibility: " + controller2.compatibility);
        System.out.println("Usage: " + controller2.usage);
        System.out.println("Vibration: " + controller2.vibration);
        System.out.println("Version: " + controller2.version);
        System.out.println("Warranty: " + controller2.warranty);
        System.out.println("Origin: " + controller2.origin);
        System.out.println("Shape: " + controller2.shape);
        System.out.println("\n---------------------------------\n");

        System.out.println("Type: " + controller3.type);
        System.out.println("Color: " + controller3.color);
        System.out.println("Buttons: " + controller3.buttons);
        System.out.println("Price: " + controller3.price);
        System.out.println("Wireless: " + controller3.wireless);
        System.out.println("Brand: " + controller3.brand);
        System.out.println("Weight: " + controller3.weight);
        System.out.println("Connectivity: " + controller3.connectivity);
        System.out.println("Compatibility: " + controller3.compatibility);
        System.out.println("Usage: " + controller3.usage);
        System.out.println("Vibration: " + controller3.vibration);
        System.out.println("Version: " + controller3.version);
        System.out.println("Warranty: " + controller3.warranty);
        System.out.println("Origin: " + controller3.origin);
        System.out.println("Shape: " + controller3.shape);

        controller3.brand = "Redgear";
        controller3.weight = 0.4;
        controller3.connectivity = "USB";
        controller3.compatibility = "PC";
        controller3.usage = "Gaming";
        controller3.vibration = true;
        controller3.version = "Pro";
        controller3.warranty = 1;
        controller3.origin = "India";
        controller3.shape = "Standard";
		
		System.out.println("Type: " + controller3.type);
        System.out.println("Color: " + controller3.color);
        System.out.println("Buttons: " + controller3.buttons);
        System.out.println("Price: " + controller3.price);
        System.out.println("Wireless: " + controller3.wireless);
        System.out.println("Brand: " + controller3.brand);
        System.out.println("Weight: " + controller3.weight);
        System.out.println("Connectivity: " + controller3.connectivity);
        System.out.println("Compatibility: " + controller3.compatibility);
        System.out.println("Usage: " + controller3.usage);
        System.out.println("Vibration: " + controller3.vibration);
        System.out.println("Version: " + controller3.version);
        System.out.println("Warranty: " + controller3.warranty);
        System.out.println("Origin: " + controller3.origin);
        System.out.println("Shape: " + controller3.shape);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + controller4.type);
        System.out.println("Color: " + controller4.color);
        System.out.println("Buttons: " + controller4.buttons);
        System.out.println("Price: " + controller4.price);
        System.out.println("Wireless: " + controller4.wireless);
        System.out.println("Brand: " + controller4.brand);
        System.out.println("Weight: " + controller4.weight);
        System.out.println("Connectivity: " + controller4.connectivity);
        System.out.println("Compatibility: " + controller4.compatibility);
        System.out.println("Usage: " + controller4.usage);
        System.out.println("Vibration: " + controller4.vibration);
        System.out.println("Version: " + controller4.version);
        System.out.println("Warranty: " + controller4.warranty);
        System.out.println("Origin: " + controller4.origin);
        System.out.println("Shape: " + controller4.shape);
		
        controller4.brand = "Logitech";
        controller4.weight = 0.32;
        controller4.connectivity = "Wireless";
        controller4.compatibility = "PC";
        controller4.usage = "Gaming";
        controller4.vibration = true;
        controller4.version = "F710";
        controller4.warranty = 2;
        controller4.origin = "Switzerland";
        controller4.shape = "Compact";
		
		System.out.println("Type: " + controller4.type);
        System.out.println("Color: " + controller4.color);
        System.out.println("Buttons: " + controller4.buttons);
        System.out.println("Price: " + controller4.price);
        System.out.println("Wireless: " + controller4.wireless);
        System.out.println("Brand: " + controller4.brand);
        System.out.println("Weight: " + controller4.weight);
        System.out.println("Connectivity: " + controller4.connectivity);
        System.out.println("Compatibility: " + controller4.compatibility);
        System.out.println("Usage: " + controller4.usage);
        System.out.println("Vibration: " + controller4.vibration);
        System.out.println("Version: " + controller4.version);
        System.out.println("Warranty: " + controller4.warranty);
        System.out.println("Origin: " + controller4.origin);
        System.out.println("Shape: " + controller4.shape);
		System.out.println("\n---------------------------------\n");

        System.out.println("Type: " + controller5.type);
        System.out.println("Color: " + controller5.color);
        System.out.println("Buttons: " + controller5.buttons);
        System.out.println("Price: " + controller5.price);
        System.out.println("Wireless: " + controller5.wireless);
        System.out.println("Brand: " + controller5.brand);
        System.out.println("Weight: " + controller5.weight);
        System.out.println("Connectivity: " + controller5.connectivity);
        System.out.println("Compatibility: " + controller5.compatibility);
        System.out.println("Usage: " + controller5.usage);
        System.out.println("Vibration: " + controller5.vibration);
        System.out.println("Version: " + controller5.version);
        System.out.println("Warranty: " + controller5.warranty);
        System.out.println("Origin: " + controller5.origin);
        System.out.println("Shape: " + controller5.shape);
        controller5.brand = "Razer";
        controller5.weight = 0.38;
        controller5.connectivity = "USB";
        controller5.compatibility = "PC";
        controller5.usage = "Gaming";
        controller5.vibration = true;
        controller5.version = "Wolverine";
        controller5.warranty = 2;
        controller5.origin = "USA";
        controller5.shape = "Ergonomic";
		System.out.println("Type: " + controller5.type);
        System.out.println("Color: " + controller5.color);
        System.out.println("Buttons: " + controller5.buttons);
        System.out.println("Price: " + controller5.price);
        System.out.println("Wireless: " + controller5.wireless);
        System.out.println("Brand: " + controller5.brand);
        System.out.println("Weight: " + controller5.weight);
        System.out.println("Connectivity: " + controller5.connectivity);
        System.out.println("Compatibility: " + controller5.compatibility);
        System.out.println("Usage: " + controller5.usage);
        System.out.println("Vibration: " + controller5.vibration);
        System.out.println("Version: " + controller5.version);
        System.out.println("Warranty: " + controller5.warranty);
        System.out.println("Origin: " + controller5.origin);
        System.out.println("Shape: " + controller5.shape);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + controller6.type);
        System.out.println("Color: " + controller6.color);
        System.out.println("Buttons: " + controller6.buttons);
        System.out.println("Price: " + controller6.price);
        System.out.println("Wireless: " + controller6.wireless);
        System.out.println("Brand: " + controller6.brand);
        System.out.println("Weight: " + controller6.weight);
        System.out.println("Connectivity: " + controller6.connectivity);
        System.out.println("Compatibility: " + controller6.compatibility);
        System.out.println("Usage: " + controller6.usage);
        System.out.println("Vibration: " + controller6.vibration);
        System.out.println("Version: " + controller6.version);
        System.out.println("Warranty: " + controller6.warranty);
        System.out.println("Origin: " + controller6.origin);
        System.out.println("Shape: " + controller6.shape);
        controller6.brand = "Corsair";
        controller6.weight = 0.36;
        controller6.connectivity = "Wireless";
        controller6.compatibility = "PC";
        controller6.usage = "Gaming";
        controller6.vibration = true;
        controller6.version = "Elite";
        controller6.warranty = 2;
        controller6.origin = "USA";
        controller6.shape = "Ergonomic";
		System.out.println("Type: " + controller6.type);
        System.out.println("Color: " + controller6.color);
        System.out.println("Buttons: " + controller6.buttons);
        System.out.println("Price: " + controller6.price);
        System.out.println("Wireless: " + controller6.wireless);
        System.out.println("Brand: " + controller6.brand);
        System.out.println("Weight: " + controller6.weight);
        System.out.println("Connectivity: " + controller6.connectivity);
        System.out.println("Compatibility: " + controller6.compatibility);
        System.out.println("Usage: " + controller6.usage);
        System.out.println("Vibration: " + controller6.vibration);
        System.out.println("Version: " + controller6.version);
        System.out.println("Warranty: " + controller6.warranty);
        System.out.println("Origin: " + controller6.origin);
        System.out.println("Shape: " + controller6.shape);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + controller7.type);
        System.out.println("Color: " + controller7.color);
        System.out.println("Buttons: " + controller7.buttons);
        System.out.println("Price: " + controller7.price);
        System.out.println("Wireless: " + controller7.wireless);
        System.out.println("Brand: " + controller7.brand);
        System.out.println("Weight: " + controller7.weight);
        System.out.println("Connectivity: " + controller7.connectivity);
        System.out.println("Compatibility: " + controller7.compatibility);
        System.out.println("Usage: " + controller7.usage);
        System.out.println("Vibration: " + controller7.vibration);
        System.out.println("Version: " + controller7.version);
        System.out.println("Warranty: " + controller7.warranty);
        System.out.println("Origin: " + controller7.origin);
        System.out.println("Shape: " + controller7.shape);
        controller7.brand = "Nintendo";
        controller7.weight = 0.25;
        controller7.connectivity = "Bluetooth";
        controller7.compatibility = "Switch";
        controller7.usage = "Gaming";
        controller7.vibration = true;
        controller7.version = "Joy-Con";
        controller7.warranty = 1;
        controller7.origin = "Japan";
        controller7.shape = "Compact";
		System.out.println("Type: " + controller7.type);
        System.out.println("Color: " + controller7.color);
        System.out.println("Buttons: " + controller7.buttons);
        System.out.println("Price: " + controller7.price);
        System.out.println("Wireless: " + controller7.wireless);
        System.out.println("Brand: " + controller7.brand);
        System.out.println("Weight: " + controller7.weight);
        System.out.println("Connectivity: " + controller7.connectivity);
        System.out.println("Compatibility: " + controller7.compatibility);
        System.out.println("Usage: " + controller7.usage);
        System.out.println("Vibration: " + controller7.vibration);
        System.out.println("Version: " + controller7.version);
        System.out.println("Warranty: " + controller7.warranty);
        System.out.println("Origin: " + controller7.origin);
        System.out.println("Shape: " + controller7.shape);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + controller8.type);
        System.out.println("Color: " + controller8.color);
        System.out.println("Buttons: " + controller8.buttons);
        System.out.println("Price: " + controller8.price);
        System.out.println("Wireless: " + controller8.wireless);
        System.out.println("Brand: " + controller8.brand);
        System.out.println("Weight: " + controller8.weight);
        System.out.println("Connectivity: " + controller8.connectivity);
        System.out.println("Compatibility: " + controller8.compatibility);
        System.out.println("Usage: " + controller8.usage);
        System.out.println("Vibration: " + controller8.vibration);
        System.out.println("Version: " + controller8.version);
        System.out.println("Warranty: " + controller8.warranty);
        System.out.println("Origin: " + controller8.origin);
        System.out.println("Shape: " + controller8.shape);
        controller8.brand = "HP";
        controller8.weight = 0.3;
        controller8.connectivity = "USB";
        controller8.compatibility = "PC";
        controller8.usage = "Gaming";
        controller8.vibration = false;
        controller8.version = "Basic";
        controller8.warranty = 1;
        controller8.origin = "China";
        controller8.shape = "Standard";
		System.out.println("Type: " + controller8.type);
        System.out.println("Color: " + controller8.color);
        System.out.println("Buttons: " + controller8.buttons);
        System.out.println("Price: " + controller8.price);
        System.out.println("Wireless: " + controller8.wireless);
        System.out.println("Brand: " + controller8.brand);
        System.out.println("Weight: " + controller8.weight);
        System.out.println("Connectivity: " + controller8.connectivity);
        System.out.println("Compatibility: " + controller8.compatibility);
        System.out.println("Usage: " + controller8.usage);
        System.out.println("Vibration: " + controller8.vibration);
        System.out.println("Version: " + controller8.version);
        System.out.println("Warranty: " + controller8.warranty);
        System.out.println("Origin: " + controller8.origin);
        System.out.println("Shape: " + controller8.shape);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + controller9.type);
        System.out.println("Color: " + controller9.color);
        System.out.println("Buttons: " + controller9.buttons);
        System.out.println("Price: " + controller9.price);
        System.out.println("Wireless: " + controller9.wireless);
        System.out.println("Brand: " + controller9.brand);
        System.out.println("Weight: " + controller9.weight);
        System.out.println("Connectivity: " + controller9.connectivity);
        System.out.println("Compatibility: " + controller9.compatibility);
        System.out.println("Usage: " + controller9.usage);
        System.out.println("Vibration: " + controller9.vibration);
        System.out.println("Version: " + controller9.version);
        System.out.println("Warranty: " + controller9.warranty);
        System.out.println("Origin: " + controller9.origin);
        System.out.println("Shape: " + controller9.shape);
        controller9.brand = "Asus";
        controller9.weight = 0.33;
        controller9.connectivity = "Wireless";
        controller9.compatibility = "PC";
        controller9.usage = "Gaming";
        controller9.vibration = true;
        controller9.version = "ROG";
        controller9.warranty = 2;
        controller9.origin = "Taiwan";
        controller9.shape = "Ergonomic";
		System.out.println("Type: " + controller9.type);
        System.out.println("Color: " + controller9.color);
        System.out.println("Buttons: " + controller9.buttons);
        System.out.println("Price: " + controller9.price);
        System.out.println("Wireless: " + controller9.wireless);
        System.out.println("Brand: " + controller9.brand);
        System.out.println("Weight: " + controller9.weight);
        System.out.println("Connectivity: " + controller9.connectivity);
        System.out.println("Compatibility: " + controller9.compatibility);
        System.out.println("Usage: " + controller9.usage);
        System.out.println("Vibration: " + controller9.vibration);
        System.out.println("Version: " + controller9.version);
        System.out.println("Warranty: " + controller9.warranty);
        System.out.println("Origin: " + controller9.origin);
        System.out.println("Shape: " + controller9.shape);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + controller10.type);
        System.out.println("Color: " + controller10.color);
        System.out.println("Buttons: " + controller10.buttons);
        System.out.println("Price: " + controller10.price);
        System.out.println("Wireless: " + controller10.wireless);
        System.out.println("Brand: " + controller10.brand);
        System.out.println("Weight: " + controller10.weight);
        System.out.println("Connectivity: " + controller10.connectivity);
        System.out.println("Compatibility: " + controller10.compatibility);
        System.out.println("Usage: " + controller10.usage);
        System.out.println("Vibration: " + controller10.vibration);
        System.out.println("Version: " + controller10.version);
        System.out.println("Warranty: " + controller10.warranty);
        System.out.println("Origin: " + controller10.origin);
        System.out.println("Shape: " + controller10.shape);
        controller10.brand = "Zebronics";
        controller10.weight = 0.35;
        controller10.connectivity = "USB";
        controller10.compatibility = "PC";
        controller10.usage = "Gaming";
        controller10.vibration = true;
        controller10.version = "Zeb-Game";
        controller10.warranty = 1;
        controller10.origin = "India";
        controller10.shape = "Standard";
		System.out.println("Type: " + controller10.type);
        System.out.println("Color: " + controller10.color);
        System.out.println("Buttons: " + controller10.buttons);
        System.out.println("Price: " + controller10.price);
        System.out.println("Wireless: " + controller10.wireless);
        System.out.println("Brand: " + controller10.brand);
        System.out.println("Weight: " + controller10.weight);
        System.out.println("Connectivity: " + controller10.connectivity);
        System.out.println("Compatibility: " + controller10.compatibility);
        System.out.println("Usage: " + controller10.usage);
        System.out.println("Vibration: " + controller10.vibration);
        System.out.println("Version: " + controller10.version);
        System.out.println("Warranty: " + controller10.warranty);
        System.out.println("Origin: " + controller10.origin);
        System.out.println("Shape: " + controller10.shape);
		System.out.println("\n---------------------------------\n");

    }
}