class FireRunner {
    public static void main(String[] args) {

        Fire fire1 = new Fire();
        Fire fire2 = new Fire();
        Fire fire3 = new Fire();
        Fire fire4 = new Fire();
        Fire fire5 = new Fire();
        Fire fire6 = new Fire();
        Fire fire7 = new Fire();
        Fire fire8 = new Fire();
        Fire fire9 = new Fire();
        Fire fire10 = new Fire();

        System.out.println("Color: " + fire1.color);
        System.out.println("Type: " + fire1.type);
        System.out.println("Temperature: " + fire1.temperature);
        System.out.println("Intensity: " + fire1.intensity);
        System.out.println("Dangerous: " + fire1.dangerous);
        System.out.println("Source: " + fire1.source);
        System.out.println("Duration: " + fire1.duration);
        System.out.println("Fuel: " + fire1.fuel);
        System.out.println("Location: " + fire1.location);
        System.out.println("Usage: " + fire1.usage);
        System.out.println("Controllable: " + fire1.controllable);
        System.out.println("Level: " + fire1.level);
        System.out.println("Effect: " + fire1.effect);
        System.out.println("Size: " + fire1.size);
        System.out.println("Safety: " + fire1.safety);

        fire1.source = "Matchstick";
        fire1.duration = 5;
        fire1.fuel = "Wood";
        fire1.location = "Camp";
        fire1.usage = "Cooking";
        fire1.controllable = true;
        fire1.level = 2;
        fire1.effect = "Heat";
        fire1.size = "Small";
        fire1.safety = "Moderate";

        System.out.println("Color: " + fire1.color);
        System.out.println("Type: " + fire1.type);
        System.out.println("Temperature: " + fire1.temperature);
        System.out.println("Intensity: " + fire1.intensity);
        System.out.println("Dangerous: " + fire1.dangerous);
        System.out.println("Source: " + fire1.source);
        System.out.println("Duration: " + fire1.duration);
        System.out.println("Fuel: " + fire1.fuel);
        System.out.println("Location: " + fire1.location);
        System.out.println("Usage: " + fire1.usage);
        System.out.println("Controllable: " + fire1.controllable);
        System.out.println("Level: " + fire1.level);
        System.out.println("Effect: " + fire1.effect);
        System.out.println("Size: " + fire1.size);
        System.out.println("Safety: " + fire1.safety);
        System.out.println("\n---------------------------------\n");

        System.out.println("Color: " + fire2.color);
        System.out.println("Type: " + fire2.type);
        System.out.println("Temperature: " + fire2.temperature);
        System.out.println("Intensity: " + fire2.intensity);
        System.out.println("Dangerous: " + fire2.dangerous);
        System.out.println("Source: " + fire2.source);
        System.out.println("Duration: " + fire2.duration);
        System.out.println("Fuel: " + fire2.fuel);
        System.out.println("Location: " + fire2.location);
        System.out.println("Usage: " + fire2.usage);
        System.out.println("Controllable: " + fire2.controllable);
        System.out.println("Level: " + fire2.level);
        System.out.println("Effect: " + fire2.effect);
        System.out.println("Size: " + fire2.size);
        System.out.println("Safety: " + fire2.safety);

        fire2.source = "Gas Stove";
        fire2.duration = 10;
        fire2.fuel = "Gas";
        fire2.location = "Kitchen";
        fire2.usage = "Cooking";
        fire2.controllable = true;
        fire2.level = 3;
        fire2.effect = "Heat";
        fire2.size = "Medium";
        fire2.safety = "Safe";

        System.out.println("Color: " + fire2.color);
        System.out.println("Type: " + fire2.type);
        System.out.println("Temperature: " + fire2.temperature);
        System.out.println("Intensity: " + fire2.intensity);
        System.out.println("Dangerous: " + fire2.dangerous);
        System.out.println("Source: " + fire2.source);
        System.out.println("Duration: " + fire2.duration);
        System.out.println("Fuel: " + fire2.fuel);
        System.out.println("Location: " + fire2.location);
        System.out.println("Usage: " + fire2.usage);
        System.out.println("Controllable: " + fire2.controllable);
        System.out.println("Level: " + fire2.level);
        System.out.println("Effect: " + fire2.effect);
        System.out.println("Size: " + fire2.size);
        System.out.println("Safety: " + fire2.safety);
        System.out.println("\n---------------------------------\n");

		System.out.println("Color: " + fire3.color);
		System.out.println("Type: " + fire3.type);
		System.out.println("Temperature: " + fire3.temperature);
		System.out.println("Intensity: " + fire3.intensity);
		System.out.println("Dangerous: " + fire3.dangerous);
		System.out.println("Source: " + fire3.source);
		System.out.println("Duration: " + fire3.duration);
		System.out.println("Fuel: " + fire3.fuel);
		System.out.println("Location: " + fire3.location);
		System.out.println("Usage: " + fire3.usage);
		System.out.println("Controllable: " + fire3.controllable);
		System.out.println("Level: " + fire3.level);
		System.out.println("Effect: " + fire3.effect);
		System.out.println("Size: " + fire3.size);
		System.out.println("Safety: " + fire3.safety);

		fire3.source = "Candle";
		fire3.duration = 3;
		fire3.fuel = "Wax";
		fire3.location = "Home";
		fire3.usage = "Lighting";
		fire3.controllable = true;
		fire3.level = 1;
		fire3.effect = "Light";
		fire3.size = "Small";
		fire3.safety = "Safe";

		System.out.println("Color: " + fire3.color);
		System.out.println("Type: " + fire3.type);
		System.out.println("Temperature: " + fire3.temperature);
		System.out.println("Intensity: " + fire3.intensity);
		System.out.println("Dangerous: " + fire3.dangerous);
		System.out.println("Source: " + fire3.source);
		System.out.println("Duration: " + fire3.duration);
		System.out.println("Fuel: " + fire3.fuel);
		System.out.println("Location: " + fire3.location);
		System.out.println("Usage: " + fire3.usage);
		System.out.println("Controllable: " + fire3.controllable);
		System.out.println("Level: " + fire3.level);
		System.out.println("Effect: " + fire3.effect);
		System.out.println("Size: " + fire3.size);
		System.out.println("Safety: " + fire3.safety);
		System.out.println("\n---------------------------------\n");

		System.out.println("Color: " + fire4.color);
		System.out.println("Type: " + fire4.type);
		System.out.println("Temperature: " + fire4.temperature);
		System.out.println("Intensity: " + fire4.intensity);
		System.out.println("Dangerous: " + fire4.dangerous);
		System.out.println("Source: " + fire4.source);
		System.out.println("Duration: " + fire4.duration);
		System.out.println("Fuel: " + fire4.fuel);
		System.out.println("Location: " + fire4.location);
		System.out.println("Usage: " + fire4.usage);
		System.out.println("Controllable: " + fire4.controllable);
		System.out.println("Level: " + fire4.level);
		System.out.println("Effect: " + fire4.effect);
		System.out.println("Size: " + fire4.size);
		System.out.println("Safety: " + fire4.safety);

		fire4.source = "Lighter";
		fire4.duration = 2;
		fire4.fuel = "Gas";
		fire4.location = "Pocket";
		fire4.usage = "Ignition";
		fire4.controllable = true;
		fire4.level = 1;
		fire4.effect = "Heat";
		fire4.size = "Small";
		fire4.safety = "Moderate";

		System.out.println("Color: " + fire4.color);
		System.out.println("Type: " + fire4.type);
		System.out.println("Temperature: " + fire4.temperature);
		System.out.println("Intensity: " + fire4.intensity);
		System.out.println("Dangerous: " + fire4.dangerous);
		System.out.println("Source: " + fire4.source);
		System.out.println("Duration: " + fire4.duration);
		System.out.println("Fuel: " + fire4.fuel);
		System.out.println("Location: " + fire4.location);
		System.out.println("Usage: " + fire4.usage);
		System.out.println("Controllable: " + fire4.controllable);
		System.out.println("Level: " + fire4.level);
		System.out.println("Effect: " + fire4.effect);
		System.out.println("Size: " + fire4.size);
		System.out.println("Safety: " + fire4.safety);
		System.out.println("\n---------------------------------\n");

		System.out.println("Color: " + fire5.color);
		System.out.println("Type: " + fire5.type);
		System.out.println("Temperature: " + fire5.temperature);
		System.out.println("Intensity: " + fire5.intensity);
		System.out.println("Dangerous: " + fire5.dangerous);
		System.out.println("Source: " + fire5.source);
		System.out.println("Duration: " + fire5.duration);
		System.out.println("Fuel: " + fire5.fuel);
		System.out.println("Location: " + fire5.location);
		System.out.println("Usage: " + fire5.usage);
		System.out.println("Controllable: " + fire5.controllable);
		System.out.println("Level: " + fire5.level);
		System.out.println("Effect: " + fire5.effect);
		System.out.println("Size: " + fire5.size);
		System.out.println("Safety: " + fire5.safety);

		fire5.source = "Bonfire";
		fire5.duration = 6;
		fire5.fuel = "Wood";
		fire5.location = "Outdoor";
		fire5.usage = "Warmth";
		fire5.controllable = true;
		fire5.level = 3;
		fire5.effect = "Heat";
		fire5.size = "Large";
		fire5.safety = "Careful";

		System.out.println("Color: " + fire5.color);
		System.out.println("Type: " + fire5.type);
		System.out.println("Temperature: " + fire5.temperature);
		System.out.println("Intensity: " + fire5.intensity);
		System.out.println("Dangerous: " + fire5.dangerous);
		System.out.println("Source: " + fire5.source);
		System.out.println("Duration: " + fire5.duration);
		System.out.println("Fuel: " + fire5.fuel);
		System.out.println("Location: " + fire5.location);
		System.out.println("Usage: " + fire5.usage);
		System.out.println("Controllable: " + fire5.controllable);
		System.out.println("Level: " + fire5.level);
		System.out.println("Effect: " + fire5.effect);
		System.out.println("Size: " + fire5.size);
		System.out.println("Safety: " + fire5.safety);
		System.out.println("\n---------------------------------\n");

		System.out.println("Color: " + fire6.color);
		System.out.println("Type: " + fire6.type);
		System.out.println("Temperature: " + fire6.temperature);
		System.out.println("Intensity: " + fire6.intensity);
		System.out.println("Dangerous: " + fire6.dangerous);
		System.out.println("Source: " + fire6.source);
		System.out.println("Duration: " + fire6.duration);
		System.out.println("Fuel: " + fire6.fuel);
		System.out.println("Location: " + fire6.location);
		System.out.println("Usage: " + fire6.usage);
		System.out.println("Controllable: " + fire6.controllable);
		System.out.println("Level: " + fire6.level);
		System.out.println("Effect: " + fire6.effect);
		System.out.println("Size: " + fire6.size);
		System.out.println("Safety: " + fire6.safety);

		fire6.source = "Engine";
		fire6.duration = 8;
		fire6.fuel = "Petrol";
		fire6.location = "Vehicle";
		fire6.usage = "Power";
		fire6.controllable = true;
		fire6.level = 4;
		fire6.effect = "Energy";
		fire6.size = "Medium";
		fire6.safety = "Danger";

		System.out.println("Color: " + fire6.color);
		System.out.println("Type: " + fire6.type);
		System.out.println("Temperature: " + fire6.temperature);
		System.out.println("Intensity: " + fire6.intensity);
		System.out.println("Dangerous: " + fire6.dangerous);
		System.out.println("Source: " + fire6.source);
		System.out.println("Duration: " + fire6.duration);
		System.out.println("Fuel: " + fire6.fuel);
		System.out.println("Location: " + fire6.location);
		System.out.println("Usage: " + fire6.usage);
		System.out.println("Controllable: " + fire6.controllable);
		System.out.println("Level: " + fire6.level);
		System.out.println("Effect: " + fire6.effect);
		System.out.println("Size: " + fire6.size);
		System.out.println("Safety: " + fire6.safety);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Color: " + fire7.color);
		System.out.println("Type: " + fire7.type);
		System.out.println("Temperature: " + fire7.temperature);
		System.out.println("Intensity: " + fire7.intensity);
		System.out.println("Dangerous: " + fire7.dangerous);
		System.out.println("Source: " + fire7.source);
		System.out.println("Duration: " + fire7.duration);
		System.out.println("Fuel: " + fire7.fuel);
		System.out.println("Location: " + fire7.location);
		System.out.println("Usage: " + fire7.usage);
		System.out.println("Controllable: " + fire7.controllable);
		System.out.println("Level: " + fire7.level);
		System.out.println("Effect: " + fire7.effect);
		System.out.println("Size: " + fire7.size);
		System.out.println("Safety: " + fire7.safety);
		fire7.source = "Factory";
		fire7.duration = 10;
		fire7.fuel = "Coal";
		fire7.location = "Industry";
		fire7.usage = "Production";
		fire7.controllable = true;
		fire7.level = 5;
		fire7.effect = "Heat";
		fire7.size = "Large";
		fire7.safety = "Controlled";
		System.out.println("Color: " + fire7.color);
		System.out.println("Type: " + fire7.type);
		System.out.println("Temperature: " + fire7.temperature);
		System.out.println("Intensity: " + fire7.intensity);
		System.out.println("Dangerous: " + fire7.dangerous);
		System.out.println("Source: " + fire7.source);
		System.out.println("Duration: " + fire7.duration);
		System.out.println("Fuel: " + fire7.fuel);
		System.out.println("Location: " + fire7.location);
		System.out.println("Usage: " + fire7.usage);
		System.out.println("Controllable: " + fire7.controllable);
		System.out.println("Level: " + fire7.level);
		System.out.println("Effect: " + fire7.effect);
		System.out.println("Size: " + fire7.size);
		System.out.println("Safety: " + fire7.safety);
		System.out.println("\n---------------------------------\n");

		System.out.println("Color: " + fire8.color);
		System.out.println("Type: " + fire8.type);
		System.out.println("Temperature: " + fire8.temperature);
		System.out.println("Intensity: " + fire8.intensity);
		System.out.println("Dangerous: " + fire8.dangerous);
		System.out.println("Source: " + fire8.source);
		System.out.println("Duration: " + fire8.duration);
		System.out.println("Fuel: " + fire8.fuel);
		System.out.println("Location: " + fire8.location);
		System.out.println("Usage: " + fire8.usage);
		System.out.println("Controllable: " + fire8.controllable);
		System.out.println("Level: " + fire8.level);
		System.out.println("Effect: " + fire8.effect);
		System.out.println("Size: " + fire8.size);
		System.out.println("Safety: " + fire8.safety);
		fire8.source = "Forest";
		fire8.duration = 20;
		fire8.fuel = "Trees";
		fire8.location = "Forest";
		fire8.usage = "Wildfire";
		fire8.controllable = false;
		fire8.level = 10;
		fire8.effect = "Destruction";
		fire8.size = "Huge";
		fire8.safety = "Dangerous";
		System.out.println("Color: " + fire8.color);
		System.out.println("Type: " + fire8.type);
		System.out.println("Temperature: " + fire8.temperature);
		System.out.println("Intensity: " + fire8.intensity);
		System.out.println("Dangerous: " + fire8.dangerous);
		System.out.println("Source: " + fire8.source);
		System.out.println("Duration: " + fire8.duration);
		System.out.println("Fuel: " + fire8.fuel);
		System.out.println("Location: " + fire8.location);
		System.out.println("Usage: " + fire8.usage);
		System.out.println("Controllable: " + fire8.controllable);
		System.out.println("Level: " + fire8.level);
		System.out.println("Effect: " + fire8.effect);
		System.out.println("Size: " + fire8.size);
		System.out.println("Safety: " + fire8.safety);
		System.out.println("\n---------------------------------\n");

		System.out.println("Color: " + fire9.color);
		System.out.println("Type: " + fire9.type);
		System.out.println("Temperature: " + fire9.temperature);
		System.out.println("Intensity: " + fire9.intensity);
		System.out.println("Dangerous: " + fire9.dangerous);
		System.out.println("Source: " + fire9.source);
		System.out.println("Duration: " + fire9.duration);
		System.out.println("Fuel: " + fire9.fuel);
		System.out.println("Location: " + fire9.location);
		System.out.println("Usage: " + fire9.usage);
		System.out.println("Controllable: " + fire9.controllable);
		System.out.println("Level: " + fire9.level);
		System.out.println("Effect: " + fire9.effect);
		System.out.println("Size: " + fire9.size);
		System.out.println("Safety: " + fire9.safety);
		fire9.source = "Explosion";
		fire9.duration = 1;
		fire9.fuel = "Chemicals";
		fire9.location = "Lab";
		fire9.usage = "Reaction";
		fire9.controllable = false;
		fire9.level = 9;
		fire9.effect = "Blast";
		fire9.size = "Medium";
		fire9.safety = "Very Dangerous";
		System.out.println("Color: " + fire9.color);
		System.out.println("Type: " + fire9.type);
		System.out.println("Temperature: " + fire9.temperature);
		System.out.println("Intensity: " + fire9.intensity);
		System.out.println("Dangerous: " + fire9.dangerous);
		System.out.println("Source: " + fire9.source);
		System.out.println("Duration: " + fire9.duration);
		System.out.println("Fuel: " + fire9.fuel);
		System.out.println("Location: " + fire9.location);
		System.out.println("Usage: " + fire9.usage);
		System.out.println("Controllable: " + fire9.controllable);
		System.out.println("Level: " + fire9.level);
		System.out.println("Effect: " + fire9.effect);
		System.out.println("Size: " + fire9.size);
		System.out.println("Safety: " + fire9.safety);
		System.out.println("\n---------------------------------\n");

		System.out.println("Color: " + fire10.color);
		System.out.println("Type: " + fire10.type);
		System.out.println("Temperature: " + fire10.temperature);
		System.out.println("Intensity: " + fire10.intensity);
		System.out.println("Dangerous: " + fire10.dangerous);
		System.out.println("Source: " + fire10.source);
		System.out.println("Duration: " + fire10.duration);
		System.out.println("Fuel: " + fire10.fuel);
		System.out.println("Location: " + fire10.location);
		System.out.println("Usage: " + fire10.usage);
		System.out.println("Controllable: " + fire10.controllable);
		System.out.println("Level: " + fire10.level);
		System.out.println("Effect: " + fire10.effect);
		System.out.println("Size: " + fire10.size);
		System.out.println("Safety: " + fire10.safety);
		fire10.source = "Sun";
		fire10.duration = 1000;
		fire10.fuel = "Nuclear";
		fire10.location = "Space";
		fire10.usage = "Energy";
		fire10.controllable = false;
		fire10.level = 100;
		fire10.effect = "Radiation";
		fire10.size = "Massive";
		fire10.safety = "Extreme";
		System.out.println("Color: " + fire10.color);
		System.out.println("Type: " + fire10.type);
		System.out.println("Temperature: " + fire10.temperature);
		System.out.println("Intensity: " + fire10.intensity);
		System.out.println("Dangerous: " + fire10.dangerous);
		System.out.println("Source: " + fire10.source);
		System.out.println("Duration: " + fire10.duration);
		System.out.println("Fuel: " + fire10.fuel);
		System.out.println("Location: " + fire10.location);
		System.out.println("Usage: " + fire10.usage);
		System.out.println("Controllable: " + fire10.controllable);
		System.out.println("Level: " + fire10.level);
		System.out.println("Effect: " + fire10.effect);
		System.out.println("Size: " + fire10.size);
		System.out.println("Safety: " + fire10.safety);
		System.out.println("\n---------------------------------\n");
    }
}