class GraphicCardRunner {
    public static void main(String[] args) {

        GraphicCard graphicCard1 = new GraphicCard();
        GraphicCard graphicCard2 = new GraphicCard();
        GraphicCard graphicCard3 = new GraphicCard();
        GraphicCard graphicCard4 = new GraphicCard();
        GraphicCard graphicCard5 = new GraphicCard();
        GraphicCard graphicCard6 = new GraphicCard();
        GraphicCard graphicCard7 = new GraphicCard();
        GraphicCard graphicCard8 = new GraphicCard();
        GraphicCard graphicCard9 = new GraphicCard();
        GraphicCard graphicCard10 = new GraphicCard();

        System.out.println("Brand: " + graphicCard1.brand);
        System.out.println("Model: " + graphicCard1.model);
        System.out.println("Memory: " + graphicCard1.memory);
        System.out.println("Price: " + graphicCard1.price);
        System.out.println("RGB: " + graphicCard1.rgb);
        System.out.println("Chipset: " + graphicCard1.chipset);
        System.out.println("Weight: " + graphicCard1.weight);
        System.out.println("Cores: " + graphicCard1.cores);
        System.out.println("Usage: " + graphicCard1.usage);
        System.out.println("Overclock: " + graphicCard1.overclock);
        System.out.println("Version: " + graphicCard1.version);
        System.out.println("Warranty: " + graphicCard1.warranty);
        System.out.println("Compatibility: " + graphicCard1.compatibility);
        System.out.println("Cooling: " + graphicCard1.cooling);
        System.out.println("Origin: " + graphicCard1.origin);

        graphicCard1.chipset = "RTX 3060";
        graphicCard1.weight = 1.2;
        graphicCard1.cores = 3584;
        graphicCard1.usage = "Gaming";
        graphicCard1.overclock = true;
        graphicCard1.version = "v1";
        graphicCard1.warranty = 3;
        graphicCard1.compatibility = "PC";
        graphicCard1.cooling = "Fan";
        graphicCard1.origin = "USA";

        System.out.println("Brand: " + graphicCard1.brand);
        System.out.println("Model: " + graphicCard1.model);
        System.out.println("Memory: " + graphicCard1.memory);
        System.out.println("Price: " + graphicCard1.price);
        System.out.println("RGB: " + graphicCard1.rgb);
        System.out.println("Chipset: " + graphicCard1.chipset);
        System.out.println("Weight: " + graphicCard1.weight);
        System.out.println("Cores: " + graphicCard1.cores);
        System.out.println("Usage: " + graphicCard1.usage);
        System.out.println("Overclock: " + graphicCard1.overclock);
        System.out.println("Version: " + graphicCard1.version);
        System.out.println("Warranty: " + graphicCard1.warranty);
        System.out.println("Compatibility: " + graphicCard1.compatibility);
        System.out.println("Cooling: " + graphicCard1.cooling);
        System.out.println("Origin: " + graphicCard1.origin);
        System.out.println("\n---------------------------------\n");

        System.out.println("Brand: " + graphicCard2.brand);
        System.out.println("Model: " + graphicCard2.model);
        System.out.println("Memory: " + graphicCard2.memory);
        System.out.println("Price: " + graphicCard2.price);
        System.out.println("RGB: " + graphicCard2.rgb);
        System.out.println("Chipset: " + graphicCard2.chipset);
        System.out.println("Weight: " + graphicCard2.weight);
        System.out.println("Cores: " + graphicCard2.cores);
        System.out.println("Usage: " + graphicCard2.usage);
        System.out.println("Overclock: " + graphicCard2.overclock);
        System.out.println("Version: " + graphicCard2.version);
        System.out.println("Warranty: " + graphicCard2.warranty);
        System.out.println("Compatibility: " + graphicCard2.compatibility);
        System.out.println("Cooling: " + graphicCard2.cooling);
        System.out.println("Origin: " + graphicCard2.origin);

        graphicCard2.chipset = "RTX 3050";
        graphicCard2.weight = 1.0;
        graphicCard2.cores = 2560;
        graphicCard2.usage = "Gaming";
        graphicCard2.overclock = false;
        graphicCard2.version = "v2";
        graphicCard2.warranty = 2;
        graphicCard2.compatibility = "PC";
        graphicCard2.cooling = "Dual Fan";
        graphicCard2.origin = "China";

        System.out.println("Brand: " + graphicCard2.brand);
        System.out.println("Model: " + graphicCard2.model);
        System.out.println("Memory: " + graphicCard2.memory);
        System.out.println("Price: " + graphicCard2.price);
        System.out.println("RGB: " + graphicCard2.rgb);
        System.out.println("Chipset: " + graphicCard2.chipset);
        System.out.println("Weight: " + graphicCard2.weight);
        System.out.println("Cores: " + graphicCard2.cores);
        System.out.println("Usage: " + graphicCard2.usage);
        System.out.println("Overclock: " + graphicCard2.overclock);
        System.out.println("Version: " + graphicCard2.version);
        System.out.println("Warranty: " + graphicCard2.warranty);
        System.out.println("Compatibility: " + graphicCard2.compatibility);
        System.out.println("Cooling: " + graphicCard2.cooling);
        System.out.println("Origin: " + graphicCard2.origin);
        System.out.println("\n---------------------------------\n");
		
		System.out.println("Brand: " + graphicCard3.brand);
		System.out.println("Model: " + graphicCard3.model);
		System.out.println("Memory: " + graphicCard3.memory);
		System.out.println("Price: " + graphicCard3.price);
		System.out.println("RGB: " + graphicCard3.rgb);
		System.out.println("Chipset: " + graphicCard3.chipset);
		System.out.println("Weight: " + graphicCard3.weight);
		System.out.println("Cores: " + graphicCard3.cores);
		System.out.println("Usage: " + graphicCard3.usage);
		System.out.println("Overclock: " + graphicCard3.overclock);
		System.out.println("Version: " + graphicCard3.version);
		System.out.println("Warranty: " + graphicCard3.warranty);
		System.out.println("Compatibility: " + graphicCard3.compatibility);
		System.out.println("Cooling: " + graphicCard3.cooling);
		System.out.println("Origin: " + graphicCard3.origin);

		graphicCard3.chipset = "GTX 1660";
		graphicCard3.weight = 0.9;
		graphicCard3.cores = 1408;
		graphicCard3.usage = "Gaming";
		graphicCard3.overclock = false;
		graphicCard3.version = "v3";
		graphicCard3.warranty = 2;
		graphicCard3.compatibility = "PC";
		graphicCard3.cooling = "Single Fan";
		graphicCard3.origin = "Taiwan";

		System.out.println("Brand: " + graphicCard3.brand);
		System.out.println("Model: " + graphicCard3.model);
		System.out.println("Memory: " + graphicCard3.memory);
		System.out.println("Price: " + graphicCard3.price);
		System.out.println("RGB: " + graphicCard3.rgb);
		System.out.println("Chipset: " + graphicCard3.chipset);
		System.out.println("Weight: " + graphicCard3.weight);
		System.out.println("Cores: " + graphicCard3.cores);
		System.out.println("Usage: " + graphicCard3.usage);
		System.out.println("Overclock: " + graphicCard3.overclock);
		System.out.println("Version: " + graphicCard3.version);
		System.out.println("Warranty: " + graphicCard3.warranty);
		System.out.println("Compatibility: " + graphicCard3.compatibility);
		System.out.println("Cooling: " + graphicCard3.cooling);
		System.out.println("Origin: " + graphicCard3.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + graphicCard4.brand);
		System.out.println("Model: " + graphicCard4.model);
		System.out.println("Memory: " + graphicCard4.memory);
		System.out.println("Price: " + graphicCard4.price);
		System.out.println("RGB: " + graphicCard4.rgb);
		System.out.println("Chipset: " + graphicCard4.chipset);
		System.out.println("Weight: " + graphicCard4.weight);
		System.out.println("Cores: " + graphicCard4.cores);
		System.out.println("Usage: " + graphicCard4.usage);
		System.out.println("Overclock: " + graphicCard4.overclock);
		System.out.println("Version: " + graphicCard4.version);
		System.out.println("Warranty: " + graphicCard4.warranty);
		System.out.println("Compatibility: " + graphicCard4.compatibility);
		System.out.println("Cooling: " + graphicCard4.cooling);
		System.out.println("Origin: " + graphicCard4.origin);

		graphicCard4.chipset = "RTX 3070";
		graphicCard4.weight = 1.4;
		graphicCard4.cores = 5888;
		graphicCard4.usage = "Gaming";
		graphicCard4.overclock = true;
		graphicCard4.version = "v4";
		graphicCard4.warranty = 3;
		graphicCard4.compatibility = "PC";
		graphicCard4.cooling = "Triple Fan";
		graphicCard4.origin = "USA";

		System.out.println("Brand: " + graphicCard4.brand);
		System.out.println("Model: " + graphicCard4.model);
		System.out.println("Memory: " + graphicCard4.memory);
		System.out.println("Price: " + graphicCard4.price);
		System.out.println("RGB: " + graphicCard4.rgb);
		System.out.println("Chipset: " + graphicCard4.chipset);
		System.out.println("Weight: " + graphicCard4.weight);
		System.out.println("Cores: " + graphicCard4.cores);
		System.out.println("Usage: " + graphicCard4.usage);
		System.out.println("Overclock: " + graphicCard4.overclock);
		System.out.println("Version: " + graphicCard4.version);
		System.out.println("Warranty: " + graphicCard4.warranty);
		System.out.println("Compatibility: " + graphicCard4.compatibility);
		System.out.println("Cooling: " + graphicCard4.cooling);
		System.out.println("Origin: " + graphicCard4.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + graphicCard5.brand);
		System.out.println("Model: " + graphicCard5.model);
		System.out.println("Memory: " + graphicCard5.memory);
		System.out.println("Price: " + graphicCard5.price);
		System.out.println("RGB: " + graphicCard5.rgb);
		System.out.println("Chipset: " + graphicCard5.chipset);
		System.out.println("Weight: " + graphicCard5.weight);
		System.out.println("Cores: " + graphicCard5.cores);
		System.out.println("Usage: " + graphicCard5.usage);
		System.out.println("Overclock: " + graphicCard5.overclock);
		System.out.println("Version: " + graphicCard5.version);
		System.out.println("Warranty: " + graphicCard5.warranty);
		System.out.println("Compatibility: " + graphicCard5.compatibility);
		System.out.println("Cooling: " + graphicCard5.cooling);
		System.out.println("Origin: " + graphicCard5.origin);

		graphicCard5.chipset = "RTX 3080";
		graphicCard5.weight = 1.6;
		graphicCard5.cores = 8704;
		graphicCard5.usage = "High-End Gaming";
		graphicCard5.overclock = true;
		graphicCard5.version = "v5";
		graphicCard5.warranty = 3;
		graphicCard5.compatibility = "PC";
		graphicCard5.cooling = "Liquid";
		graphicCard5.origin = "USA";

		System.out.println("Brand: " + graphicCard5.brand);
		System.out.println("Model: " + graphicCard5.model);
		System.out.println("Memory: " + graphicCard5.memory);
		System.out.println("Price: " + graphicCard5.price);
		System.out.println("RGB: " + graphicCard5.rgb);
		System.out.println("Chipset: " + graphicCard5.chipset);
		System.out.println("Weight: " + graphicCard5.weight);
		System.out.println("Cores: " + graphicCard5.cores);
		System.out.println("Usage: " + graphicCard5.usage);
		System.out.println("Overclock: " + graphicCard5.overclock);
		System.out.println("Version: " + graphicCard5.version);
		System.out.println("Warranty: " + graphicCard5.warranty);
		System.out.println("Compatibility: " + graphicCard5.compatibility);
		System.out.println("Cooling: " + graphicCard5.cooling);
		System.out.println("Origin: " + graphicCard5.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + graphicCard6.brand);
		System.out.println("Model: " + graphicCard6.model);
		System.out.println("Memory: " + graphicCard6.memory);
		System.out.println("Price: " + graphicCard6.price);
		System.out.println("RGB: " + graphicCard6.rgb);
		System.out.println("Chipset: " + graphicCard6.chipset);
		System.out.println("Weight: " + graphicCard6.weight);
		System.out.println("Cores: " + graphicCard6.cores);
		System.out.println("Usage: " + graphicCard6.usage);
		System.out.println("Overclock: " + graphicCard6.overclock);
		System.out.println("Version: " + graphicCard6.version);
		System.out.println("Warranty: " + graphicCard6.warranty);
		System.out.println("Compatibility: " + graphicCard6.compatibility);
		System.out.println("Cooling: " + graphicCard6.cooling);
		System.out.println("Origin: " + graphicCard6.origin);

		graphicCard6.chipset = "GTX 1050";
		graphicCard6.weight = 0.8;
		graphicCard6.cores = 640;
		graphicCard6.usage = "Basic";
		graphicCard6.overclock = false;
		graphicCard6.version = "v6";
		graphicCard6.warranty = 1;
		graphicCard6.compatibility = "PC";
		graphicCard6.cooling = "Fan";
		graphicCard6.origin = "China";

		System.out.println("Brand: " + graphicCard6.brand);
		System.out.println("Model: " + graphicCard6.model);
		System.out.println("Memory: " + graphicCard6.memory);
		System.out.println("Price: " + graphicCard6.price);
		System.out.println("RGB: " + graphicCard6.rgb);
		System.out.println("Chipset: " + graphicCard6.chipset);
		System.out.println("Weight: " + graphicCard6.weight);
		System.out.println("Cores: " + graphicCard6.cores);
		System.out.println("Usage: " + graphicCard6.usage);
		System.out.println("Overclock: " + graphicCard6.overclock);
		System.out.println("Version: " + graphicCard6.version);
		System.out.println("Warranty: " + graphicCard6.warranty);
		System.out.println("Compatibility: " + graphicCard6.compatibility);
		System.out.println("Cooling: " + graphicCard6.cooling);
		System.out.println("Origin: " + graphicCard6.origin);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Brand: " + graphicCard7.brand);
		System.out.println("Model: " + graphicCard7.model);
		System.out.println("Memory: " + graphicCard7.memory);
		System.out.println("Price: " + graphicCard7.price);
		System.out.println("RGB: " + graphicCard7.rgb);
		System.out.println("Chipset: " + graphicCard7.chipset);
		System.out.println("Weight: " + graphicCard7.weight);
		System.out.println("Cores: " + graphicCard7.cores);
		System.out.println("Usage: " + graphicCard7.usage);
		System.out.println("Overclock: " + graphicCard7.overclock);
		System.out.println("Version: " + graphicCard7.version);
		System.out.println("Warranty: " + graphicCard7.warranty);
		System.out.println("Compatibility: " + graphicCard7.compatibility);
		System.out.println("Cooling: " + graphicCard7.cooling);
		System.out.println("Origin: " + graphicCard7.origin);
		
		graphicCard7.chipset = "RTX 3090";
		graphicCard7.weight = 1.8;
		graphicCard7.cores = 10496;
		graphicCard7.usage = "Professional";
		graphicCard7.overclock = true;
		graphicCard7.version = "v7";
		graphicCard7.warranty = 3;
		graphicCard7.compatibility = "PC";
		graphicCard7.cooling = "Liquid";
		graphicCard7.origin = "USA";

		System.out.println("Brand: " + graphicCard7.brand);
		System.out.println("Model: " + graphicCard7.model);
		System.out.println("Memory: " + graphicCard7.memory);
		System.out.println("Price: " + graphicCard7.price);
		System.out.println("RGB: " + graphicCard7.rgb);
		System.out.println("Chipset: " + graphicCard7.chipset);
		System.out.println("Weight: " + graphicCard7.weight);
		System.out.println("Cores: " + graphicCard7.cores);
		System.out.println("Usage: " + graphicCard7.usage);
		System.out.println("Overclock: " + graphicCard7.overclock);
		System.out.println("Version: " + graphicCard7.version);
		System.out.println("Warranty: " + graphicCard7.warranty);
		System.out.println("Compatibility: " + graphicCard7.compatibility);
		System.out.println("Cooling: " + graphicCard7.cooling);
		System.out.println("Origin: " + graphicCard7.origin);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Brand: " + graphicCard8.brand);
		System.out.println("Model: " + graphicCard8.model);
		System.out.println("Memory: " + graphicCard8.memory);
		System.out.println("Price: " + graphicCard8.price);
		System.out.println("RGB: " + graphicCard8.rgb);
		System.out.println("Chipset: " + graphicCard8.chipset);
		System.out.println("Weight: " + graphicCard8.weight);
		System.out.println("Cores: " + graphicCard8.cores);
		System.out.println("Usage: " + graphicCard8.usage);
		System.out.println("Overclock: " + graphicCard8.overclock);
		System.out.println("Version: " + graphicCard8.version);
		System.out.println("Warranty: " + graphicCard8.warranty);
		System.out.println("Compatibility: " + graphicCard8.compatibility);
		System.out.println("Cooling: " + graphicCard8.cooling);
		System.out.println("Origin: " + graphicCard8.origin);
		graphicCard8.chipset = "GTX 1650";
		graphicCard8.weight = 0.9;
		graphicCard8.cores = 896;
		graphicCard8.usage = "Budget Gaming";
		graphicCard8.overclock = false;
		graphicCard8.version = "v8";
		graphicCard8.warranty = 2;
		graphicCard8.compatibility = "PC";
		graphicCard8.cooling = "Fan";
		graphicCard8.origin = "China";
		System.out.println("Brand: " + graphicCard8.brand);
		System.out.println("Model: " + graphicCard8.model);
		System.out.println("Memory: " + graphicCard8.memory);
		System.out.println("Price: " + graphicCard8.price);
		System.out.println("RGB: " + graphicCard8.rgb);
		System.out.println("Chipset: " + graphicCard8.chipset);
		System.out.println("Weight: " + graphicCard8.weight);
		System.out.println("Cores: " + graphicCard8.cores);
		System.out.println("Usage: " + graphicCard8.usage);
		System.out.println("Overclock: " + graphicCard8.overclock);
		System.out.println("Version: " + graphicCard8.version);
		System.out.println("Warranty: " + graphicCard8.warranty);
		System.out.println("Compatibility: " + graphicCard8.compatibility);
		System.out.println("Cooling: " + graphicCard8.cooling);
		System.out.println("Origin: " + graphicCard8.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + graphicCard9.brand);
		System.out.println("Model: " + graphicCard9.model);
		System.out.println("Memory: " + graphicCard9.memory);
		System.out.println("Price: " + graphicCard9.price);
		System.out.println("RGB: " + graphicCard9.rgb);
		System.out.println("Chipset: " + graphicCard9.chipset);
		System.out.println("Weight: " + graphicCard9.weight);
		System.out.println("Cores: " + graphicCard9.cores);
		System.out.println("Usage: " + graphicCard9.usage);
		System.out.println("Overclock: " + graphicCard9.overclock);
		System.out.println("Version: " + graphicCard9.version);
		System.out.println("Warranty: " + graphicCard9.warranty);
		System.out.println("Compatibility: " + graphicCard9.compatibility);
		System.out.println("Cooling: " + graphicCard9.cooling);
		System.out.println("Origin: " + graphicCard9.origin);
		graphicCard9.chipset = "RTX 4060";
		graphicCard9.weight = 1.3;
		graphicCard9.cores = 3072;
		graphicCard9.usage = "Gaming";
		graphicCard9.overclock = true;
		graphicCard9.version = "v9";
		graphicCard9.warranty = 3;
		graphicCard9.compatibility = "PC";
		graphicCard9.cooling = "Dual Fan";
		graphicCard9.origin = "Taiwan";
		System.out.println("Brand: " + graphicCard9.brand);
		System.out.println("Model: " + graphicCard9.model);
		System.out.println("Memory: " + graphicCard9.memory);
		System.out.println("Price: " + graphicCard9.price);
		System.out.println("RGB: " + graphicCard9.rgb);
		System.out.println("Chipset: " + graphicCard9.chipset);
		System.out.println("Weight: " + graphicCard9.weight);
		System.out.println("Cores: " + graphicCard9.cores);
		System.out.println("Usage: " + graphicCard9.usage);
		System.out.println("Overclock: " + graphicCard9.overclock);
		System.out.println("Version: " + graphicCard9.version);
		System.out.println("Warranty: " + graphicCard9.warranty);
		System.out.println("Compatibility: " + graphicCard9.compatibility);
		System.out.println("Cooling: " + graphicCard9.cooling);
		System.out.println("Origin: " + graphicCard9.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + graphicCard10.brand);
		System.out.println("Model: " + graphicCard10.model);
		System.out.println("Memory: " + graphicCard10.memory);
		System.out.println("Price: " + graphicCard10.price);
		System.out.println("RGB: " + graphicCard10.rgb);
		System.out.println("Chipset: " + graphicCard10.chipset);
		System.out.println("Weight: " + graphicCard10.weight);
		System.out.println("Cores: " + graphicCard10.cores);
		System.out.println("Usage: " + graphicCard10.usage);
		System.out.println("Overclock: " + graphicCard10.overclock);
		System.out.println("Version: " + graphicCard10.version);
		System.out.println("Warranty: " + graphicCard10.warranty);
		System.out.println("Compatibility: " + graphicCard10.compatibility);
		System.out.println("Cooling: " + graphicCard10.cooling);
		System.out.println("Origin: " + graphicCard10.origin);
		graphicCard10.chipset = "RTX 4070";
		graphicCard10.weight = 1.5;
		graphicCard10.cores = 5888;
		graphicCard10.usage = "High-End Gaming";
		graphicCard10.overclock = true;
		graphicCard10.version = "v10";
		graphicCard10.warranty = 3;
		graphicCard10.compatibility = "PC";
		graphicCard10.cooling = "Triple Fan";
		graphicCard10.origin = "USA";
		System.out.println("Brand: " + graphicCard10.brand);
		System.out.println("Model: " + graphicCard10.model);
		System.out.println("Memory: " + graphicCard10.memory);
		System.out.println("Price: " + graphicCard10.price);
		System.out.println("RGB: " + graphicCard10.rgb);
		System.out.println("Chipset: " + graphicCard10.chipset);
		System.out.println("Weight: " + graphicCard10.weight);
		System.out.println("Cores: " + graphicCard10.cores);
		System.out.println("Usage: " + graphicCard10.usage);
		System.out.println("Overclock: " + graphicCard10.overclock);
		System.out.println("Version: " + graphicCard10.version);
		System.out.println("Warranty: " + graphicCard10.warranty);
		System.out.println("Compatibility: " + graphicCard10.compatibility);
		System.out.println("Cooling: " + graphicCard10.cooling);
		System.out.println("Origin: " + graphicCard10.origin);

    }
}