class LampRunner {
    public static void main(String[] args) {

        Lamp lamp1 = new Lamp();
		Lamp lamp2 = new Lamp();
		Lamp lamp3 = new Lamp();
		Lamp lamp4 = new Lamp();
		Lamp lamp5 = new Lamp();
		Lamp lamp6 = new Lamp();
		Lamp lamp7 = new Lamp();
		Lamp lamp8 = new Lamp();
		Lamp lamp9 = new Lamp();
		Lamp lamp10 = new Lamp();

        System.out.println("Material: "+lamp1.material);
        System.out.println("Color: "+lamp1.color);
        System.out.println("Power: "+lamp1.power);
        System.out.println("Price: "+lamp1.price);
        System.out.println("Rechargeable: "+lamp1.rechargeable);
        System.out.println("Brand: "+lamp1.brand);
        System.out.println("Height: "+lamp1.height);
        System.out.println("Weight: "+lamp1.weight);
        System.out.println("Type: "+lamp1.type);
        System.out.println("Light type: "+lamp1.lightType);
        System.out.println("Warranty: "+lamp1.warranty);
        System.out.println("Portable: "+lamp1.portable);
        System.out.println("Design: "+lamp1.design);
        System.out.println("Usage: "+lamp1.usage);
        System.out.println("Shape: "+lamp1.shape);
        lamp1.brand = "Philips";
        lamp1.height = 12.5;
        lamp1.weight = 2.0;
        lamp1.type = "LED";
        lamp1.lightType = "Warm";
        lamp1.warranty = 2;
        lamp1.portable = true;
        lamp1.design = "Modern";
        lamp1.usage = "Home";
        lamp1.shape = "Round";
        System.out.println("Material: "+lamp1.material);
        System.out.println("Color: "+lamp1.color);
        System.out.println("Power: "+lamp1.power);
        System.out.println("Price: "+lamp1.price);
        System.out.println("Rechargeable: "+lamp1.rechargeable);
        System.out.println("Brand: "+lamp1.brand);
        System.out.println("Height: "+lamp1.height);
        System.out.println("Weight: "+lamp1.weight);
        System.out.println("Type: "+lamp1.type);
        System.out.println("Light type: "+lamp1.lightType);
        System.out.println("Warranty: "+lamp1.warranty);
        System.out.println("Portable: "+lamp1.portable);
        System.out.println("Design: "+lamp1.design);
        System.out.println("Usage: "+lamp1.usage);
        System.out.println("Shape: "+lamp1.shape);
		System.out.println("\n--------------------\n");
		
		System.out.println("Material: " + lamp2.material);
        System.out.println("Color: " + lamp2.color);
        System.out.println("Power: " + lamp2.power);
        System.out.println("Price: " + lamp2.price);
        System.out.println("Rechargeable: " + lamp2.rechargeable);
        System.out.println("Brand: " + lamp2.brand);
        System.out.println("Height: " + lamp2.height);
        System.out.println("Weight: " + lamp2.weight);
        System.out.println("Type: " + lamp2.type);
        System.out.println("Light Type: " + lamp2.lightType);
        System.out.println("Warranty: " + lamp2.warranty);
        System.out.println("Portable: " + lamp2.portable);
        System.out.println("Design: " + lamp2.design);
        System.out.println("Usage: " + lamp2.usage);
        System.out.println("Shape: " + lamp2.shape);
        lamp2.brand = "Syska";
        lamp2.height = 1.8;
        lamp2.weight = 2.5;
        lamp2.type = "Desk Lamp";
        lamp2.lightType = "LED";
        lamp2.warranty = 1;
        lamp2.portable = true;
        lamp2.design = "Minimal";
        lamp2.usage = "Office";
        lamp2.shape = "Square";
        System.out.println("Material: " + lamp2.material);
        System.out.println("Color: " + lamp2.color);
        System.out.println("Power: " + lamp2.power);
        System.out.println("Price: " + lamp2.price);
        System.out.println("Rechargeable: " + lamp2.rechargeable);
        System.out.println("Brand: " + lamp2.brand);
        System.out.println("Height: " + lamp2.height);
        System.out.println("Weight: " + lamp2.weight);
        System.out.println("Type: " + lamp2.type);
        System.out.println("Light Type: " + lamp2.lightType);
        System.out.println("Warranty: " + lamp2.warranty);
        System.out.println("Portable: " + lamp2.portable);
        System.out.println("Design: " + lamp2.design);
        System.out.println("Usage: " + lamp2.usage);
        System.out.println("Shape: " + lamp2.shape);
        System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + lamp3.material);
		System.out.println("Color: " + lamp3.color);
		System.out.println("Power: " + lamp3.power);
		System.out.println("Price: " + lamp3.price);
		System.out.println("Rechargeable: " + lamp3.rechargeable);
		System.out.println("Brand: " + lamp3.brand);
		System.out.println("Height: " + lamp3.height);
		System.out.println("Weight: " + lamp3.weight);
		System.out.println("Type: " + lamp3.type);
		System.out.println("Light Type: " + lamp3.lightType);
		System.out.println("Warranty: " + lamp3.warranty);
		System.out.println("Portable: " + lamp3.portable);
		System.out.println("Design: " + lamp3.design);
		System.out.println("Usage: " + lamp3.usage);
		System.out.println("Shape: " + lamp3.shape);
		lamp3.brand = "Havells";
		lamp3.height = 2.0;
		lamp3.weight = 3.0;
		lamp3.type = "Floor Lamp";
		lamp3.lightType = "Halogen";
		lamp3.warranty = 3;
		lamp3.portable = false;
		lamp3.design = "Classic";
		lamp3.usage = "Living Room";
		lamp3.shape = "Cylinder";
		System.out.println("Material: " + lamp3.material);
		System.out.println("Color: " + lamp3.color);
		System.out.println("Power: " + lamp3.power);
		System.out.println("Price: " + lamp3.price);
		System.out.println("Rechargeable: " + lamp3.rechargeable);
		System.out.println("Brand: " + lamp3.brand);
		System.out.println("Height: " + lamp3.height);
		System.out.println("Weight: " + lamp3.weight);
		System.out.println("Type: " + lamp3.type);
		System.out.println("Light Type: " + lamp3.lightType);
		System.out.println("Warranty: " + lamp3.warranty);
		System.out.println("Portable: " + lamp3.portable);
		System.out.println("Design: " + lamp3.design);
		System.out.println("Usage: " + lamp3.usage);
		System.out.println("Shape: " + lamp3.shape);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + lamp4.material);
		System.out.println("Color: " + lamp4.color);
		System.out.println("Power: " + lamp4.power);
		System.out.println("Price: " + lamp4.price);
		System.out.println("Rechargeable: " + lamp4.rechargeable);
		System.out.println("Brand: " + lamp4.brand);
		System.out.println("Height: " + lamp4.height);
		System.out.println("Weight: " + lamp4.weight);
		System.out.println("Type: " + lamp4.type);
		System.out.println("Light Type: " + lamp4.lightType);
		System.out.println("Warranty: " + lamp4.warranty);
		System.out.println("Portable: " + lamp4.portable);
		System.out.println("Design: " + lamp4.design);
		System.out.println("Usage: " + lamp4.usage);
		System.out.println("Shape: " + lamp4.shape);
		lamp4.brand = "Wipro";
		lamp4.height = 1.6;
		lamp4.weight = 2.2;
		lamp4.type = "Night Lamp";
		lamp4.lightType = "LED";
		lamp4.warranty = 1;
		lamp4.portable = true;
		lamp4.design = "Cute";
		lamp4.usage = "Bedroom";
		lamp4.shape = "Oval";
		System.out.println("Material: " + lamp4.material);
		System.out.println("Color: " + lamp4.color);
		System.out.println("Power: " + lamp4.power);
		System.out.println("Price: " + lamp4.price);
		System.out.println("Rechargeable: " + lamp4.rechargeable);
		System.out.println("Brand: " + lamp4.brand);
		System.out.println("Height: " + lamp4.height);
		System.out.println("Weight: " + lamp4.weight);
		System.out.println("Type: " + lamp4.type);
		System.out.println("Light Type: " + lamp4.lightType);
		System.out.println("Warranty: " + lamp4.warranty);
		System.out.println("Portable: " + lamp4.portable);
		System.out.println("Design: " + lamp4.design);
		System.out.println("Usage: " + lamp4.usage);
		System.out.println("Shape: " + lamp4.shape);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + lamp5.material);
		System.out.println("Color: " + lamp5.color);
		System.out.println("Power: " + lamp5.power);
		System.out.println("Price: " + lamp5.price);
		System.out.println("Rechargeable: " + lamp5.rechargeable);
		System.out.println("Brand: " + lamp5.brand);
		System.out.println("Height: " + lamp5.height);
		System.out.println("Weight: " + lamp5.weight);
		System.out.println("Type: " + lamp5.type);
		System.out.println("Light Type: " + lamp5.lightType);
		System.out.println("Warranty: " + lamp5.warranty);
		System.out.println("Portable: " + lamp5.portable);
		System.out.println("Design: " + lamp5.design);
		System.out.println("Usage: " + lamp5.usage);
		System.out.println("Shape: " + lamp5.shape);
		lamp5.brand = "Bajaj";
		lamp5.height = 1.9;
		lamp5.weight = 2.8;
		lamp5.type = "Study Lamp";
		lamp5.lightType = "CFL";
		lamp5.warranty = 2;
		lamp5.portable = true;
		lamp5.design = "Simple";
		lamp5.usage = "Study";
		lamp5.shape = "Round";
		System.out.println("Material: " + lamp5.material);
		System.out.println("Color: " + lamp5.color);
		System.out.println("Power: " + lamp5.power);
		System.out.println("Price: " + lamp5.price);
		System.out.println("Rechargeable: " + lamp5.rechargeable);
		System.out.println("Brand: " + lamp5.brand);
		System.out.println("Height: " + lamp5.height);
		System.out.println("Weight: " + lamp5.weight);
		System.out.println("Type: " + lamp5.type);
		System.out.println("Light Type: " + lamp5.lightType);
		System.out.println("Warranty: " + lamp5.warranty);
		System.out.println("Portable: " + lamp5.portable);
		System.out.println("Design: " + lamp5.design);
		System.out.println("Usage: " + lamp5.usage);
		System.out.println("Shape: " + lamp5.shape);
		System.out.println("\n---------------------------------\n");	

		System.out.println("Material: " + lamp6.material);
		System.out.println("Color: " + lamp6.color);
		System.out.println("Power: " + lamp6.power);
		System.out.println("Price: " + lamp6.price);
		System.out.println("Rechargeable: " + lamp6.rechargeable);
		System.out.println("Brand: " + lamp6.brand);
		System.out.println("Height: " + lamp6.height);
		System.out.println("Weight: " + lamp6.weight);
		System.out.println("Type: " + lamp6.type);
		System.out.println("Light Type: " + lamp6.lightType);
		System.out.println("Warranty: " + lamp6.warranty);
		System.out.println("Portable: " + lamp6.portable);
		System.out.println("Design: " + lamp6.design);
		System.out.println("Usage: " + lamp6.usage);
		System.out.println("Shape: " + lamp6.shape);
		lamp6.brand = "Mi";
		lamp6.height = 1.7;
		lamp6.weight = 2.1;
		lamp6.type = "Smart Lamp";
		lamp6.lightType = "LED";
		lamp6.warranty = 1;
		lamp6.portable = true;
		lamp6.design = "Modern";
		lamp6.usage = "Office";
		lamp6.shape = "Slim";
		System.out.println("Material: " + lamp6.material);
		System.out.println("Color: " + lamp6.color);
		System.out.println("Power: " + lamp6.power);
		System.out.println("Price: " + lamp6.price);
		System.out.println("Rechargeable: " + lamp6.rechargeable);
		System.out.println("Brand: " + lamp6.brand);
		System.out.println("Height: " + lamp6.height);
		System.out.println("Weight: " + lamp6.weight);
		System.out.println("Type: " + lamp6.type);
		System.out.println("Light Type: " + lamp6.lightType);
		System.out.println("Warranty: " + lamp6.warranty);
		System.out.println("Portable: " + lamp6.portable);
		System.out.println("Design: " + lamp6.design);
		System.out.println("Usage: " + lamp6.usage);
		System.out.println("Shape: " + lamp6.shape);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + lamp7.material);
		System.out.println("Color: " + lamp7.color);
		System.out.println("Power: " + lamp7.power);
		System.out.println("Price: " + lamp7.price);
		System.out.println("Rechargeable: " + lamp7.rechargeable);
		System.out.println("Brand: " + lamp7.brand);
		System.out.println("Height: " + lamp7.height);
		System.out.println("Weight: " + lamp7.weight);
		System.out.println("Type: " + lamp7.type);
		System.out.println("Light Type: " + lamp7.lightType);
		System.out.println("Warranty: " + lamp7.warranty);
		System.out.println("Portable: " + lamp7.portable);
		System.out.println("Design: " + lamp7.design);
		System.out.println("Usage: " + lamp7.usage);
		System.out.println("Shape: " + lamp7.shape);
		lamp7.brand = "AmazonBasics";
		lamp7.height = 2.2;
		lamp7.weight = 3.5;
		lamp7.type = "Floor Lamp";
		lamp7.lightType = "LED";
		lamp7.warranty = 2;
		lamp7.portable = false;
		lamp7.design = "Elegant";
		lamp7.usage = "Living Room";
		lamp7.shape = "Tall";
		System.out.println("Material: " + lamp7.material);
		System.out.println("Color: " + lamp7.color);
		System.out.println("Power: " + lamp7.power);
		System.out.println("Price: " + lamp7.price);
		System.out.println("Rechargeable: " + lamp7.rechargeable);
		System.out.println("Brand: " + lamp7.brand);
		System.out.println("Height: " + lamp7.height);
		System.out.println("Weight: " + lamp7.weight);
		System.out.println("Type: " + lamp7.type);
		System.out.println("Light Type: " + lamp7.lightType);
		System.out.println("Warranty: " + lamp7.warranty);
		System.out.println("Portable: " + lamp7.portable);
		System.out.println("Design: " + lamp7.design);
		System.out.println("Usage: " + lamp7.usage);
		System.out.println("Shape: " + lamp7.shape);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + lamp8.material);
		System.out.println("Color: " + lamp8.color);
		System.out.println("Power: " + lamp8.power);
		System.out.println("Price: " + lamp8.price);
		System.out.println("Rechargeable: " + lamp8.rechargeable);
		System.out.println("Brand: " + lamp8.brand);
		System.out.println("Height: " + lamp8.height);
		System.out.println("Weight: " + lamp8.weight);
		System.out.println("Type: " + lamp8.type);
		System.out.println("Light Type: " + lamp8.lightType);
		System.out.println("Warranty: " + lamp8.warranty);
		System.out.println("Portable: " + lamp8.portable);
		System.out.println("Design: " + lamp8.design);
		System.out.println("Usage: " + lamp8.usage);
		System.out.println("Shape: " + lamp8.shape);
		lamp8.brand = "Ikea";
		lamp8.height = 1.4;
		lamp8.weight = 1.8;
		lamp8.type = "Table Lamp";
		lamp8.lightType = "LED";
		lamp8.warranty = 2;
		lamp8.portable = true;
		lamp8.design = "Scandinavian";
		lamp8.usage = "Bedroom";
		lamp8.shape = "Round";
		System.out.println("Material: " + lamp8.material);
		System.out.println("Color: " + lamp8.color);
		System.out.println("Power: " + lamp8.power);
		System.out.println("Price: " + lamp8.price);
		System.out.println("Rechargeable: " + lamp8.rechargeable);
		System.out.println("Brand: " + lamp8.brand);
		System.out.println("Height: " + lamp8.height);
		System.out.println("Weight: " + lamp8.weight);
		System.out.println("Type: " + lamp8.type);
		System.out.println("Light Type: " + lamp8.lightType);
		System.out.println("Warranty: " + lamp8.warranty);
		System.out.println("Portable: " + lamp8.portable);
		System.out.println("Design: " + lamp8.design);
		System.out.println("Usage: " + lamp8.usage);
		System.out.println("Shape: " + lamp8.shape);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + lamp9.material);
		System.out.println("Color: " + lamp9.color);
		System.out.println("Power: " + lamp9.power);
		System.out.println("Price: " + lamp9.price);
		System.out.println("Rechargeable: " + lamp9.rechargeable);
		System.out.println("Brand: " + lamp9.brand);
		System.out.println("Height: " + lamp9.height);
		System.out.println("Weight: " + lamp9.weight);
		System.out.println("Type: " + lamp9.type);
		System.out.println("Light Type: " + lamp9.lightType);
		System.out.println("Warranty: " + lamp9.warranty);
		System.out.println("Portable: " + lamp9.portable);
		System.out.println("Design: " + lamp9.design);
		System.out.println("Usage: " + lamp9.usage);
		System.out.println("Shape: " + lamp9.shape);
		lamp9.brand = "Philips Hue";
		lamp9.height = 1.3;
		lamp9.weight = 1.9;
		lamp9.type = "Smart Lamp";
		lamp9.lightType = "RGB LED";
		lamp9.warranty = 2;
		lamp9.portable = true;
		lamp9.design = "Futuristic";
		lamp9.usage = "Gaming";
		lamp9.shape = "Cylinder";
		System.out.println("Material: " + lamp9.material);
		System.out.println("Color: " + lamp9.color);
		System.out.println("Power: " + lamp9.power);
		System.out.println("Price: " + lamp9.price);
		System.out.println("Rechargeable: " + lamp9.rechargeable);
		System.out.println("Brand: " + lamp9.brand);
		System.out.println("Height: " + lamp9.height);
		System.out.println("Weight: " + lamp9.weight);
		System.out.println("Type: " + lamp9.type);
		System.out.println("Light Type: " + lamp9.lightType);
		System.out.println("Warranty: " + lamp9.warranty);
		System.out.println("Portable: " + lamp9.portable);
		System.out.println("Design: " + lamp9.design);
		System.out.println("Usage: " + lamp9.usage);
		System.out.println("Shape: " + lamp9.shape);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Material: " + lamp10.material);
		System.out.println("Color: " + lamp10.color);
		System.out.println("Power: " + lamp10.power);
		System.out.println("Price: " + lamp10.price);
		System.out.println("Rechargeable: " + lamp10.rechargeable);
		System.out.println("Brand: " + lamp10.brand);
		System.out.println("Height: " + lamp10.height);
		System.out.println("Weight: " + lamp10.weight);
		System.out.println("Type: " + lamp10.type);
		System.out.println("Light Type: " + lamp10.lightType);
		System.out.println("Warranty: " + lamp10.warranty);
		System.out.println("Portable: " + lamp10.portable);
		System.out.println("Design: " + lamp10.design);
		System.out.println("Usage: " + lamp10.usage);
		System.out.println("Shape: " + lamp10.shape);
		lamp10.brand = "Orient";
		lamp10.height = 1.8;
		lamp10.weight = 2.6;
		lamp10.type = "Desk Lamp";
		lamp10.lightType = "LED";
		lamp10.warranty = 1;
		lamp10.portable = true;
		lamp10.design = "Compact";
		lamp10.usage = "Office";
		lamp10.shape = "Square";
		System.out.println("Material: " + lamp10.material);
		System.out.println("Color: " + lamp10.color);
		System.out.println("Power: " + lamp10.power);
		System.out.println("Price: " + lamp10.price);
		System.out.println("Rechargeable: " + lamp10.rechargeable);
		System.out.println("Brand: " + lamp10.brand);
		System.out.println("Height: " + lamp10.height);
		System.out.println("Weight: " + lamp10.weight);
		System.out.println("Type: " + lamp10.type);
		System.out.println("Light Type: " + lamp10.lightType);
		System.out.println("Warranty: " + lamp10.warranty);
		System.out.println("Portable: " + lamp10.portable);
		System.out.println("Design: " + lamp10.design);
		System.out.println("Usage: " + lamp10.usage);
		System.out.println("Shape: " + lamp10.shape);
		System.out.println("\n---------------------------------\n");
    }
}