class MouseRunner {
    public static void main(String[] args) {

        Mouse mouse1 = new Mouse();
        Mouse mouse2 = new Mouse();
        Mouse mouse3 = new Mouse();
        Mouse mouse4 = new Mouse();
        Mouse mouse5 = new Mouse();
        Mouse mouse6 = new Mouse();
        Mouse mouse7 = new Mouse();
        Mouse mouse8 = new Mouse();
        Mouse mouse9 = new Mouse();
        Mouse mouse10 = new Mouse();

        // ---------------- mouse1 ----------------
        System.out.println("Type: " + mouse1.type);
        System.out.println("Color: " + mouse1.color);
        System.out.println("Buttons: " + mouse1.buttons);
        System.out.println("Price: " + mouse1.price);
        System.out.println("Wireless: " + mouse1.wireless);
        System.out.println("Brand: " + mouse1.brand);
        System.out.println("Weight: " + mouse1.weight);
        System.out.println("Connectivity: " + mouse1.connectivity);
        System.out.println("DPI: " + mouse1.dpi);
        System.out.println("Usage: " + mouse1.usage);
        System.out.println("Shape: " + mouse1.shape);
        System.out.println("RGB: " + mouse1.rgb);
        System.out.println("Version: " + mouse1.version);
        System.out.println("Warranty: " + mouse1.warranty);
        System.out.println("Compatibility: " + mouse1.compatibility);

        mouse1.brand = "Logitech";
        mouse1.weight = 0.2;
        mouse1.connectivity = "USB";
        mouse1.dpi = 1200;
        mouse1.usage = "Office";
        mouse1.shape = "Ergonomic";
        mouse1.rgb = false;
        mouse1.version = "M185";
        mouse1.warranty = 2;
        mouse1.compatibility = "PC";

        System.out.println("Type: " + mouse1.type);
        System.out.println("Color: " + mouse1.color);
        System.out.println("Buttons: " + mouse1.buttons);
        System.out.println("Price: " + mouse1.price);
        System.out.println("Wireless: " + mouse1.wireless);
        System.out.println("Brand: " + mouse1.brand);
        System.out.println("Weight: " + mouse1.weight);
        System.out.println("Connectivity: " + mouse1.connectivity);
        System.out.println("DPI: " + mouse1.dpi);
        System.out.println("Usage: " + mouse1.usage);
        System.out.println("Shape: " + mouse1.shape);
        System.out.println("RGB: " + mouse1.rgb);
        System.out.println("Version: " + mouse1.version);
        System.out.println("Warranty: " + mouse1.warranty);
        System.out.println("Compatibility: " + mouse1.compatibility);
        System.out.println("\n---------------------------------\n");

        // ---------------- mouse2 ----------------
        System.out.println("Type: " + mouse2.type);
        System.out.println("Color: " + mouse2.color);
        System.out.println("Buttons: " + mouse2.buttons);
        System.out.println("Price: " + mouse2.price);
        System.out.println("Wireless: " + mouse2.wireless);
        System.out.println("Brand: " + mouse2.brand);
        System.out.println("Weight: " + mouse2.weight);
        System.out.println("Connectivity: " + mouse2.connectivity);
        System.out.println("DPI: " + mouse2.dpi);
        System.out.println("Usage: " + mouse2.usage);
        System.out.println("Shape: " + mouse2.shape);
        System.out.println("RGB: " + mouse2.rgb);
        System.out.println("Version: " + mouse2.version);
        System.out.println("Warranty: " + mouse2.warranty);
        System.out.println("Compatibility: " + mouse2.compatibility);

        mouse2.brand = "HP";
        mouse2.weight = 0.25;
        mouse2.connectivity = "Wireless";
        mouse2.dpi = 1600;
        mouse2.usage = "Office";
        mouse2.shape = "Standard";
        mouse2.rgb = false;
        mouse2.version = "X200";
        mouse2.warranty = 1;
        mouse2.compatibility = "Laptop";

        System.out.println("Type: " + mouse2.type);
        System.out.println("Color: " + mouse2.color);
        System.out.println("Buttons: " + mouse2.buttons);
        System.out.println("Price: " + mouse2.price);
        System.out.println("Wireless: " + mouse2.wireless);
        System.out.println("Brand: " + mouse2.brand);
        System.out.println("Weight: " + mouse2.weight);
        System.out.println("Connectivity: " + mouse2.connectivity);
        System.out.println("DPI: " + mouse2.dpi);
        System.out.println("Usage: " + mouse2.usage);
        System.out.println("Shape: " + mouse2.shape);
        System.out.println("RGB: " + mouse2.rgb);
        System.out.println("Version: " + mouse2.version);
        System.out.println("Warranty: " + mouse2.warranty);
        System.out.println("Compatibility: " + mouse2.compatibility);
        System.out.println("\n---------------------------------\n");

        // ---------------- mouse3 ----------------
        System.out.println("Type: " + mouse3.type);
        System.out.println("Color: " + mouse3.color);
        System.out.println("Buttons: " + mouse3.buttons);
        System.out.println("Price: " + mouse3.price);
        System.out.println("Wireless: " + mouse3.wireless);
        System.out.println("Brand: " + mouse3.brand);
        System.out.println("Weight: " + mouse3.weight);
        System.out.println("Connectivity: " + mouse3.connectivity);
        System.out.println("DPI: " + mouse3.dpi);
        System.out.println("Usage: " + mouse3.usage);
        System.out.println("Shape: " + mouse3.shape);
        System.out.println("RGB: " + mouse3.rgb);
        System.out.println("Version: " + mouse3.version);
        System.out.println("Warranty: " + mouse3.warranty);
        System.out.println("Compatibility: " + mouse3.compatibility);

        mouse3.brand = "Dell";
        mouse3.weight = 0.3;
        mouse3.connectivity = "USB";
        mouse3.dpi = 1000;
        mouse3.usage = "Office";
        mouse3.shape = "Compact";
        mouse3.rgb = false;
        mouse3.version = "D100";
        mouse3.warranty = 1;
        mouse3.compatibility = "PC";

        System.out.println("Type: " + mouse3.type);
        System.out.println("Color: " + mouse3.color);
        System.out.println("Buttons: " + mouse3.buttons);
        System.out.println("Price: " + mouse3.price);
        System.out.println("Wireless: " + mouse3.wireless);
        System.out.println("Brand: " + mouse3.brand);
        System.out.println("Weight: " + mouse3.weight);
        System.out.println("Connectivity: " + mouse3.connectivity);
        System.out.println("DPI: " + mouse3.dpi);
        System.out.println("Usage: " + mouse3.usage);
        System.out.println("Shape: " + mouse3.shape);
        System.out.println("RGB: " + mouse3.rgb);
        System.out.println("Version: " + mouse3.version);
        System.out.println("Warranty: " + mouse3.warranty);
        System.out.println("Compatibility: " + mouse3.compatibility);
        System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + mouse4.type);
		System.out.println("Color: " + mouse4.color);
		System.out.println("Buttons: " + mouse4.buttons);
		System.out.println("Price: " + mouse4.price);
		System.out.println("Wireless: " + mouse4.wireless);
		System.out.println("Brand: " + mouse4.brand);
		System.out.println("Weight: " + mouse4.weight);
		System.out.println("Connectivity: " + mouse4.connectivity);
		System.out.println("DPI: " + mouse4.dpi);
		System.out.println("Usage: " + mouse4.usage);
		System.out.println("Shape: " + mouse4.shape);
		System.out.println("RGB: " + mouse4.rgb);
		System.out.println("Version: " + mouse4.version);
		System.out.println("Warranty: " + mouse4.warranty);
		System.out.println("Compatibility: " + mouse4.compatibility);

		mouse4.brand = "Lenovo";
		mouse4.weight = 0.28;
		mouse4.connectivity = "Wireless";
		mouse4.dpi = 1200;
		mouse4.usage = "Office";
		mouse4.shape = "Slim";
		mouse4.rgb = false;
		mouse4.version = "L300";
		mouse4.warranty = 1;
		mouse4.compatibility = "Laptop";

		System.out.println("Type: " + mouse4.type);
		System.out.println("Color: " + mouse4.color);
		System.out.println("Buttons: " + mouse4.buttons);
		System.out.println("Price: " + mouse4.price);
		System.out.println("Wireless: " + mouse4.wireless);
		System.out.println("Brand: " + mouse4.brand);
		System.out.println("Weight: " + mouse4.weight);
		System.out.println("Connectivity: " + mouse4.connectivity);
		System.out.println("DPI: " + mouse4.dpi);
		System.out.println("Usage: " + mouse4.usage);
		System.out.println("Shape: " + mouse4.shape);
		System.out.println("RGB: " + mouse4.rgb);
		System.out.println("Version: " + mouse4.version);
		System.out.println("Warranty: " + mouse4.warranty);
		System.out.println("Compatibility: " + mouse4.compatibility);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + mouse5.type);
		System.out.println("Color: " + mouse5.color);
		System.out.println("Buttons: " + mouse5.buttons);
		System.out.println("Price: " + mouse5.price);
		System.out.println("Wireless: " + mouse5.wireless);
		System.out.println("Brand: " + mouse5.brand);
		System.out.println("Weight: " + mouse5.weight);
		System.out.println("Connectivity: " + mouse5.connectivity);
		System.out.println("DPI: " + mouse5.dpi);
		System.out.println("Usage: " + mouse5.usage);
		System.out.println("Shape: " + mouse5.shape);
		System.out.println("RGB: " + mouse5.rgb);
		System.out.println("Version: " + mouse5.version);
		System.out.println("Warranty: " + mouse5.warranty);
		System.out.println("Compatibility: " + mouse5.compatibility);

		mouse5.brand = "Redgear";
		mouse5.weight = 0.35;
		mouse5.connectivity = "USB";
		mouse5.dpi = 2400;
		mouse5.usage = "Gaming";
		mouse5.shape = "Ergonomic";
		mouse5.rgb = true;
		mouse5.version = "A15";
		mouse5.warranty = 1;
		mouse5.compatibility = "PC";

		System.out.println("Type: " + mouse5.type);
		System.out.println("Color: " + mouse5.color);
		System.out.println("Buttons: " + mouse5.buttons);
		System.out.println("Price: " + mouse5.price);
		System.out.println("Wireless: " + mouse5.wireless);
		System.out.println("Brand: " + mouse5.brand);
		System.out.println("Weight: " + mouse5.weight);
		System.out.println("Connectivity: " + mouse5.connectivity);
		System.out.println("DPI: " + mouse5.dpi);
		System.out.println("Usage: " + mouse5.usage);
		System.out.println("Shape: " + mouse5.shape);
		System.out.println("RGB: " + mouse5.rgb);
		System.out.println("Version: " + mouse5.version);
		System.out.println("Warranty: " + mouse5.warranty);
		System.out.println("Compatibility: " + mouse5.compatibility);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + mouse6.type);
		System.out.println("Color: " + mouse6.color);
		System.out.println("Buttons: " + mouse6.buttons);
		System.out.println("Price: " + mouse6.price);
		System.out.println("Wireless: " + mouse6.wireless);
		System.out.println("Brand: " + mouse6.brand);
		System.out.println("Weight: " + mouse6.weight);
		System.out.println("Connectivity: " + mouse6.connectivity);
		System.out.println("DPI: " + mouse6.dpi);
		System.out.println("Usage: " + mouse6.usage);
		System.out.println("Shape: " + mouse6.shape);
		System.out.println("RGB: " + mouse6.rgb);
		System.out.println("Version: " + mouse6.version);
		System.out.println("Warranty: " + mouse6.warranty);
		System.out.println("Compatibility: " + mouse6.compatibility);

		mouse6.brand = "HP Gaming";
		mouse6.weight = 0.4;
		mouse6.connectivity = "USB";
		mouse6.dpi = 3200;
		mouse6.usage = "Gaming";
		mouse6.shape = "Ergonomic";
		mouse6.rgb = true;
		mouse6.version = "G200";
		mouse6.warranty = 2;
		mouse6.compatibility = "PC";

		System.out.println("Type: " + mouse6.type);
		System.out.println("Color: " + mouse6.color);
		System.out.println("Buttons: " + mouse6.buttons);
		System.out.println("Price: " + mouse6.price);
		System.out.println("Wireless: " + mouse6.wireless);
		System.out.println("Brand: " + mouse6.brand);
		System.out.println("Weight: " + mouse6.weight);
		System.out.println("Connectivity: " + mouse6.connectivity);
		System.out.println("DPI: " + mouse6.dpi);
		System.out.println("Usage: " + mouse6.usage);
		System.out.println("Shape: " + mouse6.shape);
		System.out.println("RGB: " + mouse6.rgb);
		System.out.println("Version: " + mouse6.version);
		System.out.println("Warranty: " + mouse6.warranty);
		System.out.println("Compatibility: " + mouse6.compatibility);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + mouse7.type);
		System.out.println("Color: " + mouse7.color);
		System.out.println("Buttons: " + mouse7.buttons);
		System.out.println("Price: " + mouse7.price);
		System.out.println("Wireless: " + mouse7.wireless);
		System.out.println("Brand: " + mouse7.brand);
		System.out.println("Weight: " + mouse7.weight);
		System.out.println("Connectivity: " + mouse7.connectivity);
		System.out.println("DPI: " + mouse7.dpi);
		System.out.println("Usage: " + mouse7.usage);
		System.out.println("Shape: " + mouse7.shape);
		System.out.println("RGB: " + mouse7.rgb);
		System.out.println("Version: " + mouse7.version);
		System.out.println("Warranty: " + mouse7.warranty);
		System.out.println("Compatibility: " + mouse7.compatibility);
		
		mouse7.brand = "Zebronics";
		mouse7.weight = 0.3;
		mouse7.connectivity = "Wireless";
		mouse7.dpi = 1600;
		mouse7.usage = "Office";
		mouse7.shape = "Compact";
		mouse7.rgb = false;
		mouse7.version = "Zeb-Mouse";
		mouse7.warranty = 1;
		mouse7.compatibility = "Laptop";
		
		System.out.println("Type: " + mouse7.type);
		System.out.println("Color: " + mouse7.color);
		System.out.println("Buttons: " + mouse7.buttons);
		System.out.println("Price: " + mouse7.price);
		System.out.println("Wireless: " + mouse7.wireless);
		System.out.println("Brand: " + mouse7.brand);
		System.out.println("Weight: " + mouse7.weight);
		System.out.println("Connectivity: " + mouse7.connectivity);
		System.out.println("DPI: " + mouse7.dpi);
		System.out.println("Usage: " + mouse7.usage);
		System.out.println("Shape: " + mouse7.shape);
		System.out.println("RGB: " + mouse7.rgb);
		System.out.println("Version: " + mouse7.version);
		System.out.println("Warranty: " + mouse7.warranty);
		System.out.println("Compatibility: " + mouse7.compatibility);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Type: " + mouse8.type);
		System.out.println("Color: " + mouse8.color);
		System.out.println("Buttons: " + mouse8.buttons);
		System.out.println("Price: " + mouse8.price);
		System.out.println("Wireless: " + mouse8.wireless);
		System.out.println("Brand: " + mouse8.brand);
		System.out.println("Weight: " + mouse8.weight);
		System.out.println("Connectivity: " + mouse8.connectivity);
		System.out.println("DPI: " + mouse8.dpi);
		System.out.println("Usage: " + mouse8.usage);
		System.out.println("Shape: " + mouse8.shape);
		System.out.println("RGB: " + mouse8.rgb);
		System.out.println("Version: " + mouse8.version);
		System.out.println("Warranty: " + mouse8.warranty);
		System.out.println("Compatibility: " + mouse8.compatibility);
		mouse8.brand = "Corsair";
		mouse8.weight = 0.45;
		mouse8.connectivity = "USB";
		mouse8.dpi = 6400;
		mouse8.usage = "Gaming";
		mouse8.shape = "Ergonomic";
		mouse8.rgb = true;
		mouse8.version = "M55";
		mouse8.warranty = 2;
		mouse8.compatibility = "PC";
		System.out.println("Type: " + mouse8.type);
		System.out.println("Color: " + mouse8.color);
		System.out.println("Buttons: " + mouse8.buttons);
		System.out.println("Price: " + mouse8.price);
		System.out.println("Wireless: " + mouse8.wireless);
		System.out.println("Brand: " + mouse8.brand);
		System.out.println("Weight: " + mouse8.weight);
		System.out.println("Connectivity: " + mouse8.connectivity);
		System.out.println("DPI: " + mouse8.dpi);
		System.out.println("Usage: " + mouse8.usage);
		System.out.println("Shape: " + mouse8.shape);
		System.out.println("RGB: " + mouse8.rgb);
		System.out.println("Version: " + mouse8.version);
		System.out.println("Warranty: " + mouse8.warranty);
		System.out.println("Compatibility: " + mouse8.compatibility);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Type: " + mouse9.type);
		System.out.println("Color: " + mouse9.color);
		System.out.println("Buttons: " + mouse9.buttons);
		System.out.println("Price: " + mouse9.price);
		System.out.println("Wireless: " + mouse9.wireless);
		System.out.println("Brand: " + mouse9.brand);
		System.out.println("Weight: " + mouse9.weight);
		System.out.println("Connectivity: " + mouse9.connectivity);
		System.out.println("DPI: " + mouse9.dpi);
		System.out.println("Usage: " + mouse9.usage);
		System.out.println("Shape: " + mouse9.shape);
		System.out.println("RGB: " + mouse9.rgb);
		System.out.println("Version: " + mouse9.version);
		System.out.println("Warranty: " + mouse9.warranty);
		System.out.println("Compatibility: " + mouse9.compatibility);
		
		mouse9.brand = "Razer";
		mouse9.weight = 0.5;
		mouse9.connectivity = "USB";
		mouse9.dpi = 10000;
		mouse9.usage = "Gaming";
		mouse9.shape = "Pro";
		mouse9.rgb = true;
		mouse9.version = "DeathAdder";
		mouse9.warranty = 2;
		mouse9.compatibility = "PC";
		
		System.out.println("Type: " + mouse9.type);
		System.out.println("Color: " + mouse9.color);
		System.out.println("Buttons: " + mouse9.buttons);
		System.out.println("Price: " + mouse9.price);
		System.out.println("Wireless: " + mouse9.wireless);
		System.out.println("Brand: " + mouse9.brand);
		System.out.println("Weight: " + mouse9.weight);
		System.out.println("Connectivity: " + mouse9.connectivity);
		System.out.println("DPI: " + mouse9.dpi);
		System.out.println("Usage: " + mouse9.usage);
		System.out.println("Shape: " + mouse9.shape);
		System.out.println("RGB: " + mouse9.rgb);
		System.out.println("Version: " + mouse9.version);
		System.out.println("Warranty: " + mouse9.warranty);
		System.out.println("Compatibility: " + mouse9.compatibility);
		System.out.println("\n---------------------------------\n");
		
		System.out.println("Type: " + mouse10.type);
		System.out.println("Color: " + mouse10.color);
		System.out.println("Buttons: " + mouse10.buttons);
		System.out.println("Price: " + mouse10.price);
		System.out.println("Wireless: " + mouse10.wireless);
		System.out.println("Brand: " + mouse10.brand);
		System.out.println("Weight: " + mouse10.weight);
		System.out.println("Connectivity: " + mouse10.connectivity);
		System.out.println("DPI: " + mouse10.dpi);
		System.out.println("Usage: " + mouse10.usage);
		System.out.println("Shape: " + mouse10.shape);
		System.out.println("RGB: " + mouse10.rgb);
		System.out.println("Version: " + mouse10.version);
		System.out.println("Warranty: " + mouse10.warranty);
		System.out.println("Compatibility: " + mouse10.compatibility);
		mouse10.brand = "Apple";
		mouse10.weight = 0.2;
		mouse10.connectivity = "Bluetooth";
		mouse10.dpi = 1300;
		mouse10.usage = "Office";
		mouse10.shape = "Slim";
		mouse10.rgb = false;
		mouse10.version = "Magic Mouse";
		mouse10.warranty = 1;
		mouse10.compatibility = "Mac";
		System.out.println("Type: " + mouse10.type);
		System.out.println("Color: " + mouse10.color);
		System.out.println("Buttons: " + mouse10.buttons);
		System.out.println("Price: " + mouse10.price);
		System.out.println("Wireless: " + mouse10.wireless);
		System.out.println("Brand: " + mouse10.brand);
		System.out.println("Weight: " + mouse10.weight);
		System.out.println("Connectivity: " + mouse10.connectivity);
		System.out.println("DPI: " + mouse10.dpi);
		System.out.println("Usage: " + mouse10.usage);
		System.out.println("Shape: " + mouse10.shape);
		System.out.println("RGB: " + mouse10.rgb);
		System.out.println("Version: " + mouse10.version);
		System.out.println("Warranty: " + mouse10.warranty);
		System.out.println("Compatibility: " + mouse10.compatibility);
		System.out.println("\n---------------------------------\n");
    }
}