class ProjectorRunner {
    public static void main(String[] args) {

        Projector projector1 = new Projector();
        Projector projector2 = new Projector();
        Projector projector3 = new Projector();
        Projector projector4 = new Projector();
        Projector projector5 = new Projector();
        Projector projector6 = new Projector();
        Projector projector7 = new Projector();
        Projector projector8 = new Projector();
        Projector projector9 = new Projector();
        Projector projector10 = new Projector();

        System.out.println("Type: " + projector1.type);
        System.out.println("Color: " + projector1.color);
        System.out.println("Resolution: " + projector1.resolution);
        System.out.println("Price: " + projector1.price);
        System.out.println("Portable: " + projector1.portable);
        System.out.println("Brand: " + projector1.brand);
        System.out.println("Weight: " + projector1.weight);
        System.out.println("Brightness: " + projector1.brightness);
        System.out.println("Usage: " + projector1.usage);
        System.out.println("Wireless: " + projector1.wireless);
        System.out.println("Version: " + projector1.version);
        System.out.println("Warranty: " + projector1.warranty);
        System.out.println("Connectivity: " + projector1.connectivity);
        System.out.println("Origin: " + projector1.origin);
        System.out.println("Shape: " + projector1.shape);

        projector1.brand = "Epson";
        projector1.weight = 2.5;
        projector1.brightness = 3000;
        projector1.usage = "Office";
        projector1.wireless = true;
        projector1.version = "v1";
        projector1.warranty = 2;
        projector1.connectivity = "HDMI";
        projector1.origin = "Japan";
        projector1.shape = "Rectangle";

        System.out.println("Type: " + projector1.type);
        System.out.println("Color: " + projector1.color);
        System.out.println("Resolution: " + projector1.resolution);
        System.out.println("Price: " + projector1.price);
        System.out.println("Portable: " + projector1.portable);
        System.out.println("Brand: " + projector1.brand);
        System.out.println("Weight: " + projector1.weight);
        System.out.println("Brightness: " + projector1.brightness);
        System.out.println("Usage: " + projector1.usage);
        System.out.println("Wireless: " + projector1.wireless);
        System.out.println("Version: " + projector1.version);
        System.out.println("Warranty: " + projector1.warranty);
        System.out.println("Connectivity: " + projector1.connectivity);
        System.out.println("Origin: " + projector1.origin);
        System.out.println("Shape: " + projector1.shape);
        System.out.println("\n---------------------------------\n");

        System.out.println("Type: " + projector2.type);
        System.out.println("Color: " + projector2.color);
        System.out.println("Resolution: " + projector2.resolution);
        System.out.println("Price: " + projector2.price);
        System.out.println("Portable: " + projector2.portable);
        System.out.println("Brand: " + projector2.brand);
        System.out.println("Weight: " + projector2.weight);
        System.out.println("Brightness: " + projector2.brightness);
        System.out.println("Usage: " + projector2.usage);
        System.out.println("Wireless: " + projector2.wireless);
        System.out.println("Version: " + projector2.version);
        System.out.println("Warranty: " + projector2.warranty);
        System.out.println("Connectivity: " + projector2.connectivity);
        System.out.println("Origin: " + projector2.origin);
        System.out.println("Shape: " + projector2.shape);

        projector2.brand = "Sony";
        projector2.weight = 3.0;
        projector2.brightness = 3500;
        projector2.usage = "Home Theater";
        projector2.wireless = false;
        projector2.version = "v2";
        projector2.warranty = 3;
        projector2.connectivity = "HDMI";
        projector2.origin = "Japan";
        projector2.shape = "Square";

        System.out.println("Type: " + projector2.type);
        System.out.println("Color: " + projector2.color);
        System.out.println("Resolution: " + projector2.resolution);
        System.out.println("Price: " + projector2.price);
        System.out.println("Portable: " + projector2.portable);
        System.out.println("Brand: " + projector2.brand);
        System.out.println("Weight: " + projector2.weight);
        System.out.println("Brightness: " + projector2.brightness);
        System.out.println("Usage: " + projector2.usage);
        System.out.println("Wireless: " + projector2.wireless);
        System.out.println("Version: " + projector2.version);
        System.out.println("Warranty: " + projector2.warranty);
        System.out.println("Connectivity: " + projector2.connectivity);
        System.out.println("Origin: " + projector2.origin);
        System.out.println("Shape: " + projector2.shape);

        System.out.println("\n---------------------------------\n");

		// ---------------- projector3 ----------------
		System.out.println("Type: " + projector3.type);
		System.out.println("Color: " + projector3.color);
		System.out.println("Resolution: " + projector3.resolution);
		System.out.println("Price: " + projector3.price);
		System.out.println("Portable: " + projector3.portable);
		System.out.println("Brand: " + projector3.brand);
		System.out.println("Weight: " + projector3.weight);
		System.out.println("Brightness: " + projector3.brightness);
		System.out.println("Usage: " + projector3.usage);
		System.out.println("Wireless: " + projector3.wireless);
		System.out.println("Version: " + projector3.version);
		System.out.println("Warranty: " + projector3.warranty);
		System.out.println("Connectivity: " + projector3.connectivity);
		System.out.println("Origin: " + projector3.origin);
		System.out.println("Shape: " + projector3.shape);

		projector3.brand = "BenQ";
		projector3.weight = 2.8;
		projector3.brightness = 3200;
		projector3.usage = "Office";
		projector3.wireless = true;
		projector3.version = "v3";
		projector3.warranty = 2;
		projector3.connectivity = "VGA";
		projector3.origin = "Taiwan";
		projector3.shape = "Rectangle";

		System.out.println("Type: " + projector3.type);
		System.out.println("Color: " + projector3.color);
		System.out.println("Resolution: " + projector3.resolution);
		System.out.println("Price: " + projector3.price);
		System.out.println("Portable: " + projector3.portable);
		System.out.println("Brand: " + projector3.brand);
		System.out.println("Weight: " + projector3.weight);
		System.out.println("Brightness: " + projector3.brightness);
		System.out.println("Usage: " + projector3.usage);
		System.out.println("Wireless: " + projector3.wireless);
		System.out.println("Version: " + projector3.version);
		System.out.println("Warranty: " + projector3.warranty);
		System.out.println("Connectivity: " + projector3.connectivity);
		System.out.println("Origin: " + projector3.origin);
		System.out.println("Shape: " + projector3.shape);

		System.out.println("\n---------------------------------\n");


		// ---------------- projector4 ----------------
		System.out.println("Type: " + projector4.type);
		System.out.println("Color: " + projector4.color);
		System.out.println("Resolution: " + projector4.resolution);
		System.out.println("Price: " + projector4.price);
		System.out.println("Portable: " + projector4.portable);
		System.out.println("Brand: " + projector4.brand);
		System.out.println("Weight: " + projector4.weight);
		System.out.println("Brightness: " + projector4.brightness);
		System.out.println("Usage: " + projector4.usage);
		System.out.println("Wireless: " + projector4.wireless);
		System.out.println("Version: " + projector4.version);
		System.out.println("Warranty: " + projector4.warranty);
		System.out.println("Connectivity: " + projector4.connectivity);
		System.out.println("Origin: " + projector4.origin);
		System.out.println("Shape: " + projector4.shape);

		projector4.brand = "LG";
		projector4.weight = 2.2;
		projector4.brightness = 2800;
		projector4.usage = "Home";
		projector4.wireless = true;
		projector4.version = "v4";
		projector4.warranty = 2;
		projector4.connectivity = "HDMI";
		projector4.origin = "Korea";
		projector4.shape = "Compact";

		System.out.println("Type: " + projector4.type);
		System.out.println("Color: " + projector4.color);
		System.out.println("Resolution: " + projector4.resolution);
		System.out.println("Price: " + projector4.price);
		System.out.println("Portable: " + projector4.portable);
		System.out.println("Brand: " + projector4.brand);
		System.out.println("Weight: " + projector4.weight);
		System.out.println("Brightness: " + projector4.brightness);
		System.out.println("Usage: " + projector4.usage);
		System.out.println("Wireless: " + projector4.wireless);
		System.out.println("Version: " + projector4.version);
		System.out.println("Warranty: " + projector4.warranty);
		System.out.println("Connectivity: " + projector4.connectivity);
		System.out.println("Origin: " + projector4.origin);
		System.out.println("Shape: " + projector4.shape);

		System.out.println("\n---------------------------------\n");


		// ---------------- projector5 ----------------
		System.out.println("Type: " + projector5.type);
		System.out.println("Color: " + projector5.color);
		System.out.println("Resolution: " + projector5.resolution);
		System.out.println("Price: " + projector5.price);
		System.out.println("Portable: " + projector5.portable);
		System.out.println("Brand: " + projector5.brand);
		System.out.println("Weight: " + projector5.weight);
		System.out.println("Brightness: " + projector5.brightness);
		System.out.println("Usage: " + projector5.usage);
		System.out.println("Wireless: " + projector5.wireless);
		System.out.println("Version: " + projector5.version);
		System.out.println("Warranty: " + projector5.warranty);
		System.out.println("Connectivity: " + projector5.connectivity);
		System.out.println("Origin: " + projector5.origin);
		System.out.println("Shape: " + projector5.shape);

		projector5.brand = "ViewSonic";
		projector5.weight = 3.1;
		projector5.brightness = 3600;
		projector5.usage = "Office";
		projector5.wireless = false;
		projector5.version = "v5";
		projector5.warranty = 3;
		projector5.connectivity = "HDMI";
		projector5.origin = "USA";
		projector5.shape = "Rectangle";

		System.out.println("Type: " + projector5.type);
		System.out.println("Color: " + projector5.color);
		System.out.println("Resolution: " + projector5.resolution);
		System.out.println("Price: " + projector5.price);
		System.out.println("Portable: " + projector5.portable);
		System.out.println("Brand: " + projector5.brand);
		System.out.println("Weight: " + projector5.weight);
		System.out.println("Brightness: " + projector5.brightness);
		System.out.println("Usage: " + projector5.usage);
		System.out.println("Wireless: " + projector5.wireless);
		System.out.println("Version: " + projector5.version);
		System.out.println("Warranty: " + projector5.warranty);
		System.out.println("Connectivity: " + projector5.connectivity);
		System.out.println("Origin: " + projector5.origin);
		System.out.println("Shape: " + projector5.shape);

		System.out.println("\n---------------------------------\n");


		// ---------------- projector6 ----------------
		System.out.println("Type: " + projector6.type);
		System.out.println("Color: " + projector6.color);
		System.out.println("Resolution: " + projector6.resolution);
		System.out.println("Price: " + projector6.price);
		System.out.println("Portable: " + projector6.portable);
		System.out.println("Brand: " + projector6.brand);
		System.out.println("Weight: " + projector6.weight);
		System.out.println("Brightness: " + projector6.brightness);
		System.out.println("Usage: " + projector6.usage);
		System.out.println("Wireless: " + projector6.wireless);
		System.out.println("Version: " + projector6.version);
		System.out.println("Warranty: " + projector6.warranty);
		System.out.println("Connectivity: " + projector6.connectivity);
		System.out.println("Origin: " + projector6.origin);
		System.out.println("Shape: " + projector6.shape);

		projector6.brand = "Panasonic";
		projector6.weight = 3.5;
		projector6.brightness = 4000;
		projector6.usage = "Conference";
		projector6.wireless = true;
		projector6.version = "v6";
		projector6.warranty = 3;
		projector6.connectivity = "HDMI";
		projector6.origin = "Japan";
		projector6.shape = "Rectangle";

		System.out.println("Type: " + projector6.type);
		System.out.println("Color: " + projector6.color);
		System.out.println("Resolution: " + projector6.resolution);
		System.out.println("Price: " + projector6.price);
		System.out.println("Portable: " + projector6.portable);
		System.out.println("Brand: " + projector6.brand);
		System.out.println("Weight: " + projector6.weight);
		System.out.println("Brightness: " + projector6.brightness);
		System.out.println("Usage: " + projector6.usage);
		System.out.println("Wireless: " + projector6.wireless);
		System.out.println("Version: " + projector6.version);
		System.out.println("Warranty: " + projector6.warranty);
		System.out.println("Connectivity: " + projector6.connectivity);
		System.out.println("Origin: " + projector6.origin);
		System.out.println("Shape: " + projector6.shape);

		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + projector7.type);
		System.out.println("Color: " + projector7.color);
		System.out.println("Resolution: " + projector7.resolution);
		System.out.println("Price: " + projector7.price);
		System.out.println("Portable: " + projector7.portable);
		System.out.println("Brand: " + projector7.brand);
		System.out.println("Weight: " + projector7.weight);
		System.out.println("Brightness: " + projector7.brightness);
		System.out.println("Usage: " + projector7.usage);
		System.out.println("Wireless: " + projector7.wireless);
		System.out.println("Version: " + projector7.version);
		System.out.println("Warranty: " + projector7.warranty);
		System.out.println("Connectivity: " + projector7.connectivity);
		System.out.println("Origin: " + projector7.origin);
		System.out.println("Shape: " + projector7.shape);
		projector7.brand = "Acer";
		projector7.weight = 2.4;
		projector7.brightness = 3000;
		projector7.usage = "Office";
		projector7.wireless = false;
		projector7.version = "v7";
		projector7.warranty = 2;
		projector7.connectivity = "VGA";
		projector7.origin = "Taiwan";
		projector7.shape = "Compact";
		System.out.println("Type: " + projector7.type);
		System.out.println("Color: " + projector7.color);
		System.out.println("Resolution: " + projector7.resolution);
		System.out.println("Price: " + projector7.price);
		System.out.println("Portable: " + projector7.portable);
		System.out.println("Brand: " + projector7.brand);
		System.out.println("Weight: " + projector7.weight);
		System.out.println("Brightness: " + projector7.brightness);
		System.out.println("Usage: " + projector7.usage);
		System.out.println("Wireless: " + projector7.wireless);
		System.out.println("Version: " + projector7.version);
		System.out.println("Warranty: " + projector7.warranty);
		System.out.println("Connectivity: " + projector7.connectivity);
		System.out.println("Origin: " + projector7.origin);
		System.out.println("Shape: " + projector7.shape);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + projector8.type);
		System.out.println("Color: " + projector8.color);
		System.out.println("Resolution: " + projector8.resolution);
		System.out.println("Price: " + projector8.price);
		System.out.println("Portable: " + projector8.portable);
		System.out.println("Brand: " + projector8.brand);
		System.out.println("Weight: " + projector8.weight);
		System.out.println("Brightness: " + projector8.brightness);
		System.out.println("Usage: " + projector8.usage);
		System.out.println("Wireless: " + projector8.wireless);
		System.out.println("Version: " + projector8.version);
		System.out.println("Warranty: " + projector8.warranty);
		System.out.println("Connectivity: " + projector8.connectivity);
		System.out.println("Origin: " + projector8.origin);
		System.out.println("Shape: " + projector8.shape);
		projector8.brand = "Optoma";
		projector8.weight = 2.7;
		projector8.brightness = 3400;
		projector8.usage = "Home Theater";
		projector8.wireless = true;
		projector8.version = "v8";
		projector8.warranty = 2;
		projector8.connectivity = "HDMI";
		projector8.origin = "China";
		projector8.shape = "Rectangle";
		System.out.println("Type: " + projector8.type);
		System.out.println("Color: " + projector8.color);
		System.out.println("Resolution: " + projector8.resolution);
		System.out.println("Price: " + projector8.price);
		System.out.println("Portable: " + projector8.portable);
		System.out.println("Brand: " + projector8.brand);
		System.out.println("Weight: " + projector8.weight);
		System.out.println("Brightness: " + projector8.brightness);
		System.out.println("Usage: " + projector8.usage);
		System.out.println("Wireless: " + projector8.wireless);
		System.out.println("Version: " + projector8.version);
		System.out.println("Warranty: " + projector8.warranty);
		System.out.println("Connectivity: " + projector8.connectivity);
		System.out.println("Origin: " + projector8.origin);
		System.out.println("Shape: " + projector8.shape);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + projector9.type);
		System.out.println("Color: " + projector9.color);
		System.out.println("Resolution: " + projector9.resolution);
		System.out.println("Price: " + projector9.price);
		System.out.println("Portable: " + projector9.portable);
		System.out.println("Brand: " + projector9.brand);
		System.out.println("Weight: " + projector9.weight);
		System.out.println("Brightness: " + projector9.brightness);
		System.out.println("Usage: " + projector9.usage);
		System.out.println("Wireless: " + projector9.wireless);
		System.out.println("Version: " + projector9.version);
		System.out.println("Warranty: " + projector9.warranty);
		System.out.println("Connectivity: " + projector9.connectivity);
		System.out.println("Origin: " + projector9.origin);
		System.out.println("Shape: " + projector9.shape);
		projector9.brand = "Xiaomi";
		projector9.weight = 2.0;
		projector9.brightness = 2500;
		projector9.usage = "Portable";
		projector9.wireless = true;
		projector9.version = "v9";
		projector9.warranty = 1;
		projector9.connectivity = "WiFi";
		projector9.origin = "China";
		projector9.shape = "Compact";
		System.out.println("Type: " + projector9.type);
		System.out.println("Color: " + projector9.color);
		System.out.println("Resolution: " + projector9.resolution);
		System.out.println("Price: " + projector9.price);
		System.out.println("Portable: " + projector9.portable);
		System.out.println("Brand: " + projector9.brand);
		System.out.println("Weight: " + projector9.weight);
		System.out.println("Brightness: " + projector9.brightness);
		System.out.println("Usage: " + projector9.usage);
		System.out.println("Wireless: " + projector9.wireless);
		System.out.println("Version: " + projector9.version);
		System.out.println("Warranty: " + projector9.warranty);
		System.out.println("Connectivity: " + projector9.connectivity);
		System.out.println("Origin: " + projector9.origin);
		System.out.println("Shape: " + projector9.shape);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + projector10.type);
		System.out.println("Color: " + projector10.color);
		System.out.println("Resolution: " + projector10.resolution);
		System.out.println("Price: " + projector10.price);
		System.out.println("Portable: " + projector10.portable);
		System.out.println("Brand: " + projector10.brand);
		System.out.println("Weight: " + projector10.weight);
		System.out.println("Brightness: " + projector10.brightness);
		System.out.println("Usage: " + projector10.usage);
		System.out.println("Wireless: " + projector10.wireless);
		System.out.println("Version: " + projector10.version);
		System.out.println("Warranty: " + projector10.warranty);
		System.out.println("Connectivity: " + projector10.connectivity);
		System.out.println("Origin: " + projector10.origin);
		System.out.println("Shape: " + projector10.shape);
		projector10.brand = "Samsung";
		projector10.weight = 2.6;
		projector10.brightness = 3300;
		projector10.usage = "Home";
		projector10.wireless = true;
		projector10.version = "v10";
		projector10.warranty = 2;
		projector10.connectivity = "HDMI";
		projector10.origin = "Korea";
		projector10.shape = "Slim";
		System.out.println("Type: " + projector10.type);
		System.out.println("Color: " + projector10.color);
		System.out.println("Resolution: " + projector10.resolution);
		System.out.println("Price: " + projector10.price);
		System.out.println("Portable: " + projector10.portable);
		System.out.println("Brand: " + projector10.brand);
		System.out.println("Weight: " + projector10.weight);
		System.out.println("Brightness: " + projector10.brightness);
		System.out.println("Usage: " + projector10.usage);
		System.out.println("Wireless: " + projector10.wireless);
		System.out.println("Version: " + projector10.version);
		System.out.println("Warranty: " + projector10.warranty);
		System.out.println("Connectivity: " + projector10.connectivity);
		System.out.println("Origin: " + projector10.origin);
		System.out.println("Shape: " + projector10.shape);
		System.out.println("\n---------------------------------\n");
    }
}