class RouterRunner {
    public static void main(String[] args) {

        Router router1 = new Router();
        Router router2 = new Router();
        Router router3 = new Router();
        Router router4 = new Router();
        Router router5 = new Router();
        Router router6 = new Router();
        Router router7 = new Router();
        Router router8 = new Router();
        Router router9 = new Router();
        Router router10 = new Router();

        System.out.println("Type: " + router1.type);
        System.out.println("Band: " + router1.band);
        System.out.println("Antennas: " + router1.antennas);
        System.out.println("Price: " + router1.price);
        System.out.println("Secure: " + router1.secure);
        System.out.println("Brand: " + router1.brand);
        System.out.println("Weight: " + router1.weight);
        System.out.println("Speed: " + router1.speed);
        System.out.println("Usage: " + router1.usage);
        System.out.println("DualBand: " + router1.dualBand);
        System.out.println("Version: " + router1.version);
        System.out.println("Warranty: " + router1.warranty);
        System.out.println("Connectivity: " + router1.connectivity);
        System.out.println("Origin: " + router1.origin);
        System.out.println("Shape: " + router1.shape);

        router1.brand = "TP-Link";
        router1.weight = 0.6;
        router1.speed = 1200;
        router1.usage = "Home";
        router1.dualBand = true;
        router1.version = "v1";
        router1.warranty = 2;
        router1.connectivity = "WiFi";
        router1.origin = "China";
        router1.shape = "Rectangle";

        System.out.println("Type: " + router1.type);
        System.out.println("Band: " + router1.band);
        System.out.println("Antennas: " + router1.antennas);
        System.out.println("Price: " + router1.price);
        System.out.println("Secure: " + router1.secure);
        System.out.println("Brand: " + router1.brand);
        System.out.println("Weight: " + router1.weight);
        System.out.println("Speed: " + router1.speed);
        System.out.println("Usage: " + router1.usage);
        System.out.println("DualBand: " + router1.dualBand);
        System.out.println("Version: " + router1.version);
        System.out.println("Warranty: " + router1.warranty);
        System.out.println("Connectivity: " + router1.connectivity);
        System.out.println("Origin: " + router1.origin);
        System.out.println("Shape: " + router1.shape);

        System.out.println("\n---------------------------------\n");

        System.out.println("Type: " + router2.type);
        System.out.println("Band: " + router2.band);
        System.out.println("Antennas: " + router2.antennas);
        System.out.println("Price: " + router2.price);
        System.out.println("Secure: " + router2.secure);
        System.out.println("Brand: " + router2.brand);
        System.out.println("Weight: " + router2.weight);
        System.out.println("Speed: " + router2.speed);
        System.out.println("Usage: " + router2.usage);
        System.out.println("DualBand: " + router2.dualBand);
        System.out.println("Version: " + router2.version);
        System.out.println("Warranty: " + router2.warranty);
        System.out.println("Connectivity: " + router2.connectivity);
        System.out.println("Origin: " + router2.origin);
        System.out.println("Shape: " + router2.shape);

        router2.brand = "D-Link";
        router2.weight = 0.7;
        router2.speed = 1500;
        router2.usage = "Office";
        router2.dualBand = true;
        router2.version = "v2";
        router2.warranty = 3;
        router2.connectivity = "WiFi";
        router2.origin = "Taiwan";
        router2.shape = "Square";

        System.out.println("Type: " + router2.type);
        System.out.println("Band: " + router2.band);
        System.out.println("Antennas: " + router2.antennas);
        System.out.println("Price: " + router2.price);
        System.out.println("Secure: " + router2.secure);
        System.out.println("Brand: " + router2.brand);
        System.out.println("Weight: " + router2.weight);
        System.out.println("Speed: " + router2.speed);
        System.out.println("Usage: " + router2.usage);
        System.out.println("DualBand: " + router2.dualBand);
        System.out.println("Version: " + router2.version);
        System.out.println("Warranty: " + router2.warranty);
        System.out.println("Connectivity: " + router2.connectivity);
        System.out.println("Origin: " + router2.origin);
        System.out.println("Shape: " + router2.shape);

        System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + router3.type);
        System.out.println("Band: " + router3.band);
        System.out.println("Antennas: " + router3.antennas);
        System.out.println("Price: " + router3.price);
        System.out.println("Secure: " + router3.secure);
        System.out.println("Brand: " + router3.brand);
        System.out.println("Weight: " + router3.weight);
        System.out.println("Speed: " + router3.speed);
        System.out.println("Usage: " + router3.usage);
        System.out.println("DualBand: " + router3.dualBand);
        System.out.println("Version: " + router3.version);
        System.out.println("Warranty: " + router3.warranty);
        System.out.println("Connectivity: " + router3.connectivity);
        System.out.println("Origin: " + router3.origin);
        System.out.println("Shape: " + router3.shape);
        router3.brand = "Netgear";
        router3.weight = 0.65;
        router3.speed = 1800;
        router3.usage = "Office";
        router3.dualBand = true;
        router3.version = "v3";
        router3.warranty = 2;
        router3.connectivity = "WiFi";
        router3.origin = "USA";
        router3.shape = "Rectangle";
		System.out.println("Type: " + router3.type);
        System.out.println("Band: " + router3.band);
        System.out.println("Antennas: " + router3.antennas);
        System.out.println("Price: " + router3.price);
        System.out.println("Secure: " + router3.secure);
        System.out.println("Brand: " + router3.brand);
        System.out.println("Weight: " + router3.weight);
        System.out.println("Speed: " + router3.speed);
        System.out.println("Usage: " + router3.usage);
        System.out.println("DualBand: " + router3.dualBand);
        System.out.println("Version: " + router3.version);
        System.out.println("Warranty: " + router3.warranty);
        System.out.println("Connectivity: " + router3.connectivity);
        System.out.println("Origin: " + router3.origin);
        System.out.println("Shape: " + router3.shape);
		
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + router4.type);
        System.out.println("Band: " + router4.band);
        System.out.println("Antennas: " + router4.antennas);
        System.out.println("Price: " + router4.price);
        System.out.println("Secure: " + router4.secure);
        System.out.println("Brand: " + router4.brand);
        System.out.println("Weight: " + router4.weight);
        System.out.println("Speed: " + router4.speed);
        System.out.println("Usage: " + router4.usage);
        System.out.println("DualBand: " + router4.dualBand);
        System.out.println("Version: " + router4.version);
        System.out.println("Warranty: " + router4.warranty);
        System.out.println("Connectivity: " + router4.connectivity);
        System.out.println("Origin: " + router4.origin);
        System.out.println("Shape: " + router4.shape);
        router4.brand = "Cisco";
        router4.weight = 1.0;
        router4.speed = 2500;
        router4.usage = "Enterprise";
        router4.dualBand = true;
        router4.version = "v4";
        router4.warranty = 3;
        router4.connectivity = "Ethernet";
        router4.origin = "USA";
        router4.shape = "Rack";
		System.out.println("Type: " + router4.type);
        System.out.println("Band: " + router4.band);
        System.out.println("Antennas: " + router4.antennas);
        System.out.println("Price: " + router4.price);
        System.out.println("Secure: " + router4.secure);
        System.out.println("Brand: " + router4.brand);
        System.out.println("Weight: " + router4.weight);
        System.out.println("Speed: " + router4.speed);
        System.out.println("Usage: " + router4.usage);
        System.out.println("DualBand: " + router4.dualBand);
        System.out.println("Version: " + router4.version);
        System.out.println("Warranty: " + router4.warranty);
        System.out.println("Connectivity: " + router4.connectivity);
        System.out.println("Origin: " + router4.origin);
        System.out.println("Shape: " + router4.shape);
		
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + router5.type);
        System.out.println("Band: " + router5.band);
        System.out.println("Antennas: " + router5.antennas);
        System.out.println("Price: " + router5.price);
        System.out.println("Secure: " + router5.secure);
        System.out.println("Brand: " + router5.brand);
        System.out.println("Weight: " + router5.weight);
        System.out.println("Speed: " + router5.speed);
        System.out.println("Usage: " + router5.usage);
        System.out.println("DualBand: " + router5.dualBand);
        System.out.println("Version: " + router5.version);
        System.out.println("Warranty: " + router5.warranty);
        System.out.println("Connectivity: " + router5.connectivity);
        System.out.println("Origin: " + router5.origin);
        System.out.println("Shape: " + router5.shape);
        router5.brand = "Tenda";
        router5.weight = 0.55;
        router5.speed = 1000;
        router5.usage = "Home";
        router5.dualBand = false;
        router5.version = "v5";
        router5.warranty = 1;
        router5.connectivity = "WiFi";
        router5.origin = "China";
        router5.shape = "Compact";
		System.out.println("Type: " + router5.type);
        System.out.println("Band: " + router5.band);
        System.out.println("Antennas: " + router5.antennas);
        System.out.println("Price: " + router5.price);
        System.out.println("Secure: " + router5.secure);
        System.out.println("Brand: " + router5.brand);
        System.out.println("Weight: " + router5.weight);
        System.out.println("Speed: " + router5.speed);
        System.out.println("Usage: " + router5.usage);
        System.out.println("DualBand: " + router5.dualBand);
        System.out.println("Version: " + router5.version);
        System.out.println("Warranty: " + router5.warranty);
        System.out.println("Connectivity: " + router5.connectivity);
        System.out.println("Origin: " + router5.origin);
        System.out.println("Shape: " + router5.shape);
		
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + router6.type);
        System.out.println("Band: " + router6.band);
        System.out.println("Antennas: " + router6.antennas);
        System.out.println("Price: " + router6.price);
        System.out.println("Secure: " + router6.secure);
        System.out.println("Brand: " + router6.brand);
        System.out.println("Weight: " + router6.weight);
        System.out.println("Speed: " + router6.speed);
        System.out.println("Usage: " + router6.usage);
        System.out.println("DualBand: " + router6.dualBand);
        System.out.println("Version: " + router6.version);
        System.out.println("Warranty: " + router6.warranty);
        System.out.println("Connectivity: " + router6.connectivity);
        System.out.println("Origin: " + router6.origin);
        System.out.println("Shape: " + router6.shape);
        router6.brand = "Linksys";
        router6.weight = 0.7;
        router6.speed = 2000;
        router6.usage = "Home";
        router6.dualBand = true;
        router6.version = "v6";
        router6.warranty = 2;
        router6.connectivity = "WiFi";
        router6.origin = "USA";
        router6.shape = "Rectangle";
		System.out.println("Type: " + router6.type);
        System.out.println("Band: " + router6.band);
        System.out.println("Antennas: " + router6.antennas);
        System.out.println("Price: " + router6.price);
        System.out.println("Secure: " + router6.secure);
        System.out.println("Brand: " + router6.brand);
        System.out.println("Weight: " + router6.weight);
        System.out.println("Speed: " + router6.speed);
        System.out.println("Usage: " + router6.usage);
        System.out.println("DualBand: " + router6.dualBand);
        System.out.println("Version: " + router6.version);
        System.out.println("Warranty: " + router6.warranty);
        System.out.println("Connectivity: " + router6.connectivity);
        System.out.println("Origin: " + router6.origin);
        System.out.println("Shape: " + router6.shape);
		
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + router7.type);
        System.out.println("Band: " + router7.band);
        System.out.println("Antennas: " + router7.antennas);
        System.out.println("Price: " + router7.price);
        System.out.println("Secure: " + router7.secure);
        System.out.println("Brand: " + router7.brand);
        System.out.println("Weight: " + router7.weight);
        System.out.println("Speed: " + router7.speed);
        System.out.println("Usage: " + router7.usage);
        System.out.println("DualBand: " + router7.dualBand);
        System.out.println("Version: " + router7.version);
        System.out.println("Warranty: " + router7.warranty);
        System.out.println("Connectivity: " + router7.connectivity);
        System.out.println("Origin: " + router7.origin);
        System.out.println("Shape: " + router7.shape);
        router7.brand = "Belkin";
        router7.weight = 0.6;
        router7.speed = 1200;
        router7.usage = "Home";
        router7.dualBand = true;
        router7.version = "v7";
        router7.warranty = 2;
        router7.connectivity = "WiFi";
        router7.origin = "USA";
        router7.shape = "Slim";
		System.out.println("Type: " + router7.type);
        System.out.println("Band: " + router7.band);
        System.out.println("Antennas: " + router7.antennas);
        System.out.println("Price: " + router7.price);
        System.out.println("Secure: " + router7.secure);
        System.out.println("Brand: " + router7.brand);
        System.out.println("Weight: " + router7.weight);
        System.out.println("Speed: " + router7.speed);
        System.out.println("Usage: " + router7.usage);
        System.out.println("DualBand: " + router7.dualBand);
        System.out.println("Version: " + router7.version);
        System.out.println("Warranty: " + router7.warranty);
        System.out.println("Connectivity: " + router7.connectivity);
        System.out.println("Origin: " + router7.origin);
        System.out.println("Shape: " + router7.shape);
		
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + router8.type);
        System.out.println("Band: " + router8.band);
        System.out.println("Antennas: " + router8.antennas);
        System.out.println("Price: " + router8.price);
        System.out.println("Secure: " + router8.secure);
        System.out.println("Brand: " + router8.brand);
        System.out.println("Weight: " + router8.weight);
        System.out.println("Speed: " + router8.speed);
        System.out.println("Usage: " + router8.usage);
        System.out.println("DualBand: " + router8.dualBand);
        System.out.println("Version: " + router8.version);
        System.out.println("Warranty: " + router8.warranty);
        System.out.println("Connectivity: " + router8.connectivity);
        System.out.println("Origin: " + router8.origin);
        System.out.println("Shape: " + router8.shape);
        router8.brand = "Asus";
        router8.weight = 0.75;
        router8.speed = 3000;
        router8.usage = "Gaming";
        router8.dualBand = true;
        router8.version = "v8";
        router8.warranty = 3;
        router8.connectivity = "WiFi";
        router8.origin = "Taiwan";
        router8.shape = "Modern";
		System.out.println("Type: " + router8.type);
        System.out.println("Band: " + router8.band);
        System.out.println("Antennas: " + router8.antennas);
        System.out.println("Price: " + router8.price);
        System.out.println("Secure: " + router8.secure);
        System.out.println("Brand: " + router8.brand);
        System.out.println("Weight: " + router8.weight);
        System.out.println("Speed: " + router8.speed);
        System.out.println("Usage: " + router8.usage);
        System.out.println("DualBand: " + router8.dualBand);
        System.out.println("Version: " + router8.version);
        System.out.println("Warranty: " + router8.warranty);
        System.out.println("Connectivity: " + router8.connectivity);
        System.out.println("Origin: " + router8.origin);
        System.out.println("Shape: " + router8.shape);
		
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + router9.type);
        System.out.println("Band: " + router9.band);
        System.out.println("Antennas: " + router9.antennas);
        System.out.println("Price: " + router9.price);
        System.out.println("Secure: " + router9.secure);
        System.out.println("Brand: " + router9.brand);
        System.out.println("Weight: " + router9.weight);
        System.out.println("Speed: " + router9.speed);
        System.out.println("Usage: " + router9.usage);
        System.out.println("DualBand: " + router9.dualBand);
        System.out.println("Version: " + router9.version);
        System.out.println("Warranty: " + router9.warranty);
        System.out.println("Connectivity: " + router9.connectivity);
        System.out.println("Origin: " + router9.origin);
        System.out.println("Shape: " + router9.shape);
        router9.brand = "HP";
        router9.weight = 0.6;
        router9.speed = 1400;
        router9.usage = "Office";
        router9.dualBand = true;
        router9.version = "v9";
        router9.warranty = 1;
        router9.connectivity = "WiFi";
        router9.origin = "China";
        router9.shape = "Standard";
		System.out.println("Type: " + router9.type);
        System.out.println("Band: " + router9.band);
        System.out.println("Antennas: " + router9.antennas);
        System.out.println("Price: " + router9.price);
        System.out.println("Secure: " + router9.secure);
        System.out.println("Brand: " + router9.brand);
        System.out.println("Weight: " + router9.weight);
        System.out.println("Speed: " + router9.speed);
        System.out.println("Usage: " + router9.usage);
        System.out.println("DualBand: " + router9.dualBand);
        System.out.println("Version: " + router9.version);
        System.out.println("Warranty: " + router9.warranty);
        System.out.println("Connectivity: " + router9.connectivity);
        System.out.println("Origin: " + router9.origin);
        System.out.println("Shape: " + router9.shape);
		
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + router10.type);
        System.out.println("Band: " + router10.band);
        System.out.println("Antennas: " + router10.antennas);
        System.out.println("Price: " + router10.price);
        System.out.println("Secure: " + router10.secure);
        System.out.println("Brand: " + router10.brand);
        System.out.println("Weight: " + router10.weight);
        System.out.println("Speed: " + router10.speed);
        System.out.println("Usage: " + router10.usage);
        System.out.println("DualBand: " + router10.dualBand);
        System.out.println("Version: " + router10.version);
        System.out.println("Warranty: " + router10.warranty);
        System.out.println("Connectivity: " + router10.connectivity);
        System.out.println("Origin: " + router10.origin);
        System.out.println("Shape: " + router10.shape);
        router10.brand = "Zebronics";
        router10.weight = 0.58;
        router10.speed = 900;
        router10.usage = "Home";
        router10.dualBand = false;
        router10.version = "v10";
        router10.warranty = 1;
        router10.connectivity = "WiFi";
        router10.origin = "India";
        router10.shape = "Compact";
		System.out.println("Type: " + router10.type);
        System.out.println("Band: " + router10.band);
        System.out.println("Antennas: " + router10.antennas);
        System.out.println("Price: " + router10.price);
        System.out.println("Secure: " + router10.secure);
        System.out.println("Brand: " + router10.brand);
        System.out.println("Weight: " + router10.weight);
        System.out.println("Speed: " + router10.speed);
        System.out.println("Usage: " + router10.usage);
        System.out.println("DualBand: " + router10.dualBand);
        System.out.println("Version: " + router10.version);
        System.out.println("Warranty: " + router10.warranty);
        System.out.println("Connectivity: " + router10.connectivity);
        System.out.println("Origin: " + router10.origin);
        System.out.println("Shape: " + router10.shape);
		
		System.out.println("\n---------------------------------\n");

    }
}