class XboxRunner {
    public static void main(String[] args) {

        Xbox xbox1 = new Xbox();
        Xbox xbox2 = new Xbox();
        Xbox xbox3 = new Xbox();
        Xbox xbox4 = new Xbox();
        Xbox xbox5 = new Xbox();
        Xbox xbox6 = new Xbox();
        Xbox xbox7 = new Xbox();
        Xbox xbox8 = new Xbox();
        Xbox xbox9 = new Xbox();
        Xbox xbox10 = new Xbox();

        System.out.println("Brand: " + xbox1.brand);
        System.out.println("Color: " + xbox1.color);
        System.out.println("Storage: " + xbox1.storage);
        System.out.println("Price: " + xbox1.price);
        System.out.println("Online: " + xbox1.online);
        System.out.println("Model: " + xbox1.model);
        System.out.println("Weight: " + xbox1.weight);
        System.out.println("RAM: " + xbox1.ram);
        System.out.println("Usage: " + xbox1.usage);
        System.out.println("Supports4K: " + xbox1.supports4K);
        System.out.println("Version: " + xbox1.version);
        System.out.println("Warranty: " + xbox1.warranty);
        System.out.println("Processor: " + xbox1.processor);
        System.out.println("Cooling: " + xbox1.cooling);
        System.out.println("Origin: " + xbox1.origin);

        xbox1.model = "Series S";
        xbox1.weight = 1.9;
        xbox1.ram = 10;
        xbox1.usage = "Gaming";
        xbox1.supports4K = true;
        xbox1.version = "v1";
        xbox1.warranty = 1;
        xbox1.processor = "AMD";
        xbox1.cooling = "Fan";
        xbox1.origin = "USA";

        System.out.println("Brand: " + xbox1.brand);
        System.out.println("Color: " + xbox1.color);
        System.out.println("Storage: " + xbox1.storage);
        System.out.println("Price: " + xbox1.price);
        System.out.println("Online: " + xbox1.online);
        System.out.println("Model: " + xbox1.model);
        System.out.println("Weight: " + xbox1.weight);
        System.out.println("RAM: " + xbox1.ram);
        System.out.println("Usage: " + xbox1.usage);
        System.out.println("Supports4K: " + xbox1.supports4K);
        System.out.println("Version: " + xbox1.version);
        System.out.println("Warranty: " + xbox1.warranty);
        System.out.println("Processor: " + xbox1.processor);
        System.out.println("Cooling: " + xbox1.cooling);
        System.out.println("Origin: " + xbox1.origin);
        System.out.println("\n---------------------------------\n");

        System.out.println("Brand: " + xbox2.brand);
        System.out.println("Color: " + xbox2.color);
        System.out.println("Storage: " + xbox2.storage);
        System.out.println("Price: " + xbox2.price);
        System.out.println("Online: " + xbox2.online);
        System.out.println("Model: " + xbox2.model);
        System.out.println("Weight: " + xbox2.weight);
        System.out.println("RAM: " + xbox2.ram);
        System.out.println("Usage: " + xbox2.usage);
        System.out.println("Supports4K: " + xbox2.supports4K);
        System.out.println("Version: " + xbox2.version);
        System.out.println("Warranty: " + xbox2.warranty);
        System.out.println("Processor: " + xbox2.processor);
        System.out.println("Cooling: " + xbox2.cooling);
        System.out.println("Origin: " + xbox2.origin);

        xbox2.model = "Series X";
        xbox2.weight = 4.4;
        xbox2.ram = 16;
        xbox2.usage = "Gaming";
        xbox2.supports4K = true;
        xbox2.version = "v2";
        xbox2.warranty = 2;
        xbox2.processor = "AMD Ryzen";
        xbox2.cooling = "Advanced Cooling";
        xbox2.origin = "USA";

        System.out.println("Brand: " + xbox2.brand);
        System.out.println("Color: " + xbox2.color);
        System.out.println("Storage: " + xbox2.storage);
        System.out.println("Price: " + xbox2.price);
        System.out.println("Online: " + xbox2.online);
        System.out.println("Model: " + xbox2.model);
        System.out.println("Weight: " + xbox2.weight);
        System.out.println("RAM: " + xbox2.ram);
        System.out.println("Usage: " + xbox2.usage);
        System.out.println("Supports4K: " + xbox2.supports4K);
        System.out.println("Version: " + xbox2.version);
        System.out.println("Warranty: " + xbox2.warranty);
        System.out.println("Processor: " + xbox2.processor);
        System.out.println("Cooling: " + xbox2.cooling);
        System.out.println("Origin: " + xbox2.origin);
        System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + xbox3.brand);
        System.out.println("Color: " + xbox3.color);
        System.out.println("Storage: " + xbox3.storage);
        System.out.println("Price: " + xbox3.price);
        System.out.println("Online: " + xbox3.online);
        System.out.println("Model: " + xbox3.model);
        System.out.println("Weight: " + xbox3.weight);
        System.out.println("RAM: " + xbox3.ram);
        System.out.println("Usage: " + xbox3.usage);
        System.out.println("Supports4K: " + xbox3.supports4K);
        System.out.println("Version: " + xbox3.version);
        System.out.println("Warranty: " + xbox3.warranty);
        System.out.println("Processor: " + xbox3.processor);
        System.out.println("Cooling: " + xbox3.cooling);
        System.out.println("Origin: " + xbox3.origin);
        xbox3.model = "One S";
        xbox3.weight = 2.9;
        xbox3.ram = 8;
        xbox3.usage = "Gaming";
        xbox3.supports4K = false;
        xbox3.version = "v3";
        xbox3.warranty = 1;
        xbox3.processor = "AMD";
        xbox3.cooling = "Fan";
        xbox3.origin = "China";
		System.out.println("Brand: " + xbox3.brand);
        System.out.println("Color: " + xbox3.color);
        System.out.println("Storage: " + xbox3.storage);
        System.out.println("Price: " + xbox3.price);
        System.out.println("Online: " + xbox3.online);
        System.out.println("Model: " + xbox3.model);
        System.out.println("Weight: " + xbox3.weight);
        System.out.println("RAM: " + xbox3.ram);
        System.out.println("Usage: " + xbox3.usage);
        System.out.println("Supports4K: " + xbox3.supports4K);
        System.out.println("Version: " + xbox3.version);
        System.out.println("Warranty: " + xbox3.warranty);
        System.out.println("Processor: " + xbox3.processor);
        System.out.println("Cooling: " + xbox3.cooling);
        System.out.println("Origin: " + xbox3.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + xbox4.brand);
        System.out.println("Color: " + xbox4.color);
        System.out.println("Storage: " + xbox4.storage);
        System.out.println("Price: " + xbox4.price);
        System.out.println("Online: " + xbox4.online);
        System.out.println("Model: " + xbox4.model);
        System.out.println("Weight: " + xbox4.weight);
        System.out.println("RAM: " + xbox4.ram);
        System.out.println("Usage: " + xbox4.usage);
        System.out.println("Supports4K: " + xbox4.supports4K);
        System.out.println("Version: " + xbox4.version);
        System.out.println("Warranty: " + xbox4.warranty);
        System.out.println("Processor: " + xbox4.processor);
        System.out.println("Cooling: " + xbox4.cooling);
        System.out.println("Origin: " + xbox4.origin);
        xbox4.model = "One X";
        xbox4.weight = 3.8;
        xbox4.ram = 12;
        xbox4.usage = "Gaming";
        xbox4.supports4K = true;
        xbox4.version = "v4";
        xbox4.warranty = 2;
        xbox4.processor = "AMD";
        xbox4.cooling = "Enhanced";
        xbox4.origin = "China";
		System.out.println("Brand: " + xbox4.brand);
        System.out.println("Color: " + xbox4.color);
        System.out.println("Storage: " + xbox4.storage);
        System.out.println("Price: " + xbox4.price);
        System.out.println("Online: " + xbox4.online);
        System.out.println("Model: " + xbox4.model);
        System.out.println("Weight: " + xbox4.weight);
        System.out.println("RAM: " + xbox4.ram);
        System.out.println("Usage: " + xbox4.usage);
        System.out.println("Supports4K: " + xbox4.supports4K);
        System.out.println("Version: " + xbox4.version);
        System.out.println("Warranty: " + xbox4.warranty);
        System.out.println("Processor: " + xbox4.processor);
        System.out.println("Cooling: " + xbox4.cooling);
        System.out.println("Origin: " + xbox4.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + xbox5.brand);
        System.out.println("Color: " + xbox5.color);
        System.out.println("Storage: " + xbox5.storage);
        System.out.println("Price: " + xbox5.price);
        System.out.println("Online: " + xbox5.online);
        System.out.println("Model: " + xbox5.model);
        System.out.println("Weight: " + xbox5.weight);
        System.out.println("RAM: " + xbox5.ram);
        System.out.println("Usage: " + xbox5.usage);
        System.out.println("Supports4K: " + xbox5.supports4K);
        System.out.println("Version: " + xbox5.version);
        System.out.println("Warranty: " + xbox5.warranty);
        System.out.println("Processor: " + xbox5.processor);
        System.out.println("Cooling: " + xbox5.cooling);
        System.out.println("Origin: " + xbox5.origin);
        xbox5.model = "Series S Digital";
        xbox5.weight = 2.0;
        xbox5.ram = 10;
        xbox5.usage = "Gaming";
        xbox5.supports4K = true;
        xbox5.version = "v5";
        xbox5.warranty = 1;
        xbox5.processor = "AMD";
        xbox5.cooling = "Fan";
        xbox5.origin = "USA";
		System.out.println("Brand: " + xbox5.brand);
        System.out.println("Color: " + xbox5.color);
        System.out.println("Storage: " + xbox5.storage);
        System.out.println("Price: " + xbox5.price);
        System.out.println("Online: " + xbox5.online);
        System.out.println("Model: " + xbox5.model);
        System.out.println("Weight: " + xbox5.weight);
        System.out.println("RAM: " + xbox5.ram);
        System.out.println("Usage: " + xbox5.usage);
        System.out.println("Supports4K: " + xbox5.supports4K);
        System.out.println("Version: " + xbox5.version);
        System.out.println("Warranty: " + xbox5.warranty);
        System.out.println("Processor: " + xbox5.processor);
        System.out.println("Cooling: " + xbox5.cooling);
        System.out.println("Origin: " + xbox5.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + xbox6.brand);
        System.out.println("Color: " + xbox6.color);
        System.out.println("Storage: " + xbox6.storage);
        System.out.println("Price: " + xbox6.price);
        System.out.println("Online: " + xbox6.online);
        System.out.println("Model: " + xbox6.model);
        System.out.println("Weight: " + xbox6.weight);
        System.out.println("RAM: " + xbox6.ram);
        System.out.println("Usage: " + xbox6.usage);
        System.out.println("Supports4K: " + xbox6.supports4K);
        System.out.println("Version: " + xbox6.version);
        System.out.println("Warranty: " + xbox6.warranty);
        System.out.println("Processor: " + xbox6.processor);
        System.out.println("Cooling: " + xbox6.cooling);
        System.out.println("Origin: " + xbox6.origin);
        xbox6.model = "Series X Pro";
        xbox6.weight = 4.5;
        xbox6.ram = 16;
        xbox6.usage = "Gaming";
        xbox6.supports4K = true;
        xbox6.version = "v6";
        xbox6.warranty = 2;
        xbox6.processor = "AMD Ryzen";
        xbox6.cooling = "Liquid";
        xbox6.origin = "USA";
		System.out.println("Brand: " + xbox6.brand);
        System.out.println("Color: " + xbox6.color);
        System.out.println("Storage: " + xbox6.storage);
        System.out.println("Price: " + xbox6.price);
        System.out.println("Online: " + xbox6.online);
        System.out.println("Model: " + xbox6.model);
        System.out.println("Weight: " + xbox6.weight);
        System.out.println("RAM: " + xbox6.ram);
        System.out.println("Usage: " + xbox6.usage);
        System.out.println("Supports4K: " + xbox6.supports4K);
        System.out.println("Version: " + xbox6.version);
        System.out.println("Warranty: " + xbox6.warranty);
        System.out.println("Processor: " + xbox6.processor);
        System.out.println("Cooling: " + xbox6.cooling);
        System.out.println("Origin: " + xbox6.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + xbox7.brand);
        System.out.println("Color: " + xbox7.color);
        System.out.println("Storage: " + xbox7.storage);
        System.out.println("Price: " + xbox7.price);
        System.out.println("Online: " + xbox7.online);
        System.out.println("Model: " + xbox7.model);
        System.out.println("Weight: " + xbox7.weight);
        System.out.println("RAM: " + xbox7.ram);
        System.out.println("Usage: " + xbox7.usage);
        System.out.println("Supports4K: " + xbox7.supports4K);
        System.out.println("Version: " + xbox7.version);
        System.out.println("Warranty: " + xbox7.warranty);
        System.out.println("Processor: " + xbox7.processor);
        System.out.println("Cooling: " + xbox7.cooling);
        System.out.println("Origin: " + xbox7.origin);
        xbox7.model = "One Elite";
        xbox7.weight = 3.5;
        xbox7.ram = 8;
        xbox7.usage = "Gaming";
        xbox7.supports4K = false;
        xbox7.version = "v7";
        xbox7.warranty = 1;
        xbox7.processor = "AMD";
        xbox7.cooling = "Fan";
        xbox7.origin = "China";
		System.out.println("Brand: " + xbox7.brand);
        System.out.println("Color: " + xbox7.color);
        System.out.println("Storage: " + xbox7.storage);
        System.out.println("Price: " + xbox7.price);
        System.out.println("Online: " + xbox7.online);
        System.out.println("Model: " + xbox7.model);
        System.out.println("Weight: " + xbox7.weight);
        System.out.println("RAM: " + xbox7.ram);
        System.out.println("Usage: " + xbox7.usage);
        System.out.println("Supports4K: " + xbox7.supports4K);
        System.out.println("Version: " + xbox7.version);
        System.out.println("Warranty: " + xbox7.warranty);
        System.out.println("Processor: " + xbox7.processor);
        System.out.println("Cooling: " + xbox7.cooling);
        System.out.println("Origin: " + xbox7.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + xbox8.brand);
        System.out.println("Color: " + xbox8.color);
        System.out.println("Storage: " + xbox8.storage);
        System.out.println("Price: " + xbox8.price);
        System.out.println("Online: " + xbox8.online);
        System.out.println("Model: " + xbox8.model);
        System.out.println("Weight: " + xbox8.weight);
        System.out.println("RAM: " + xbox8.ram);
        System.out.println("Usage: " + xbox8.usage);
        System.out.println("Supports4K: " + xbox8.supports4K);
        System.out.println("Version: " + xbox8.version);
        System.out.println("Warranty: " + xbox8.warranty);
        System.out.println("Processor: " + xbox8.processor);
        System.out.println("Cooling: " + xbox8.cooling);
        System.out.println("Origin: " + xbox8.origin);
        xbox8.model = "Series Lite";
        xbox8.weight = 1.8;
        xbox8.ram = 8;
        xbox8.usage = "Gaming";
        xbox8.supports4K = false;
        xbox8.version = "v8";
        xbox8.warranty = 1;
        xbox8.processor = "AMD";
        xbox8.cooling = "Basic";
        xbox8.origin = "India";
		System.out.println("Brand: " + xbox8.brand);
        System.out.println("Color: " + xbox8.color);
        System.out.println("Storage: " + xbox8.storage);
        System.out.println("Price: " + xbox8.price);
        System.out.println("Online: " + xbox8.online);
        System.out.println("Model: " + xbox8.model);
        System.out.println("Weight: " + xbox8.weight);
        System.out.println("RAM: " + xbox8.ram);
        System.out.println("Usage: " + xbox8.usage);
        System.out.println("Supports4K: " + xbox8.supports4K);
        System.out.println("Version: " + xbox8.version);
        System.out.println("Warranty: " + xbox8.warranty);
        System.out.println("Processor: " + xbox8.processor);
        System.out.println("Cooling: " + xbox8.cooling);
        System.out.println("Origin: " + xbox8.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + xbox9.brand);
        System.out.println("Color: " + xbox9.color);
        System.out.println("Storage: " + xbox9.storage);
        System.out.println("Price: " + xbox9.price);
        System.out.println("Online: " + xbox9.online);
        System.out.println("Model: " + xbox9.model);
        System.out.println("Weight: " + xbox9.weight);
        System.out.println("RAM: " + xbox9.ram);
        System.out.println("Usage: " + xbox9.usage);
        System.out.println("Supports4K: " + xbox9.supports4K);
        System.out.println("Version: " + xbox9.version);
        System.out.println("Warranty: " + xbox9.warranty);
        System.out.println("Processor: " + xbox9.processor);
        System.out.println("Cooling: " + xbox9.cooling);
        System.out.println("Origin: " + xbox9.origin);
        xbox9.model = "Series Ultra";
        xbox9.weight = 4.2;
        xbox9.ram = 16;
        xbox9.usage = "Gaming";
        xbox9.supports4K = true;
        xbox9.version = "v9";
        xbox9.warranty = 2;
        xbox9.processor = "AMD Ryzen";
        xbox9.cooling = "Advanced";
        xbox9.origin = "USA";
		System.out.println("Brand: " + xbox9.brand);
        System.out.println("Color: " + xbox9.color);
        System.out.println("Storage: " + xbox9.storage);
        System.out.println("Price: " + xbox9.price);
        System.out.println("Online: " + xbox9.online);
        System.out.println("Model: " + xbox9.model);
        System.out.println("Weight: " + xbox9.weight);
        System.out.println("RAM: " + xbox9.ram);
        System.out.println("Usage: " + xbox9.usage);
        System.out.println("Supports4K: " + xbox9.supports4K);
        System.out.println("Version: " + xbox9.version);
        System.out.println("Warranty: " + xbox9.warranty);
        System.out.println("Processor: " + xbox9.processor);
        System.out.println("Cooling: " + xbox9.cooling);
        System.out.println("Origin: " + xbox9.origin);
		System.out.println("\n---------------------------------\n");

		System.out.println("Brand: " + xbox10.brand);
        System.out.println("Color: " + xbox10.color);
        System.out.println("Storage: " + xbox10.storage);
        System.out.println("Price: " + xbox10.price);
        System.out.println("Online: " + xbox10.online);
        System.out.println("Model: " + xbox10.model);
        System.out.println("Weight: " + xbox10.weight);
        System.out.println("RAM: " + xbox10.ram);
        System.out.println("Usage: " + xbox10.usage);
        System.out.println("Supports4K: " + xbox10.supports4K);
        System.out.println("Version: " + xbox10.version);
        System.out.println("Warranty: " + xbox10.warranty);
        System.out.println("Processor: " + xbox10.processor);
        System.out.println("Cooling: " + xbox10.cooling);
        System.out.println("Origin: " + xbox10.origin);
        xbox10.model = "Series Mini";
        xbox10.weight = 1.5;
        xbox10.ram = 8;
        xbox10.usage = "Gaming";
        xbox10.supports4K = false;
        xbox10.version = "v10";
        xbox10.warranty = 1;
        xbox10.processor = "AMD";
        xbox10.cooling = "Basic";
        xbox10.origin = "India";
		System.out.println("Brand: " + xbox10.brand);
        System.out.println("Color: " + xbox10.color);
        System.out.println("Storage: " + xbox10.storage);
        System.out.println("Price: " + xbox10.price);
        System.out.println("Online: " + xbox10.online);
        System.out.println("Model: " + xbox10.model);
        System.out.println("Weight: " + xbox10.weight);
        System.out.println("RAM: " + xbox10.ram);
        System.out.println("Usage: " + xbox10.usage);
        System.out.println("Supports4K: " + xbox10.supports4K);
        System.out.println("Version: " + xbox10.version);
        System.out.println("Warranty: " + xbox10.warranty);
        System.out.println("Processor: " + xbox10.processor);
        System.out.println("Cooling: " + xbox10.cooling);
        System.out.println("Origin: " + xbox10.origin);
		System.out.println("\n---------------------------------\n");

    }
}