class ZipRunner {
    public static void main(String[] args) {

        Zip zip1 = new Zip();
        Zip zip2 = new Zip();
        Zip zip3 = new Zip();
        Zip zip4 = new Zip();
        Zip zip5 = new Zip();
        Zip zip6 = new Zip();
        Zip zip7 = new Zip();
        Zip zip8 = new Zip();
        Zip zip9 = new Zip();
        Zip zip10 = new Zip();

        System.out.println("Type: " + zip1.type);
        System.out.println("Format: " + zip1.format);
        System.out.println("Size: " + zip1.size);
        System.out.println("Ratio: " + zip1.ratio);
        System.out.println("Encrypted: " + zip1.encrypted);
        System.out.println("Name: " + zip1.name);
        System.out.println("Weight: " + zip1.weight);
        System.out.println("Usage: " + zip1.usage);
        System.out.println("Secure: " + zip1.secure);
        System.out.println("Version: " + zip1.version);
        System.out.println("Files: " + zip1.files);
        System.out.println("Tool: " + zip1.tool);
        System.out.println("Compatibility: " + zip1.compatibility);
        System.out.println("Origin: " + zip1.origin);
        System.out.println("Status: " + zip1.status);

        zip1.name = "ProjectFiles";
        zip1.weight = 1.2;
        zip1.usage = "Backup";
        zip1.secure = true;
        zip1.version = "v1";
        zip1.files = 20;
        zip1.tool = "WinZip";
        zip1.compatibility = "Windows";
        zip1.origin = "USA";
        zip1.status = "Compressed";

        System.out.println("Type: " + zip1.type);
        System.out.println("Format: " + zip1.format);
        System.out.println("Size: " + zip1.size);
        System.out.println("Ratio: " + zip1.ratio);
        System.out.println("Encrypted: " + zip1.encrypted);
        System.out.println("Name: " + zip1.name);
        System.out.println("Weight: " + zip1.weight);
        System.out.println("Usage: " + zip1.usage);
        System.out.println("Secure: " + zip1.secure);
        System.out.println("Version: " + zip1.version);
        System.out.println("Files: " + zip1.files);
        System.out.println("Tool: " + zip1.tool);
        System.out.println("Compatibility: " + zip1.compatibility);
        System.out.println("Origin: " + zip1.origin);
        System.out.println("Status: " + zip1.status);

        System.out.println("\n---------------------------------\n");

        System.out.println("Type: " + zip2.type);
        System.out.println("Format: " + zip2.format);
        System.out.println("Size: " + zip2.size);
        System.out.println("Ratio: " + zip2.ratio);
        System.out.println("Encrypted: " + zip2.encrypted);
        System.out.println("Name: " + zip2.name);
        System.out.println("Weight: " + zip2.weight);
        System.out.println("Usage: " + zip2.usage);
        System.out.println("Secure: " + zip2.secure);
        System.out.println("Version: " + zip2.version);
        System.out.println("Files: " + zip2.files);
        System.out.println("Tool: " + zip2.tool);
        System.out.println("Compatibility: " + zip2.compatibility);
        System.out.println("Origin: " + zip2.origin);
        System.out.println("Status: " + zip2.status);

        zip2.name = "Images";
        zip2.weight = 0.8;
        zip2.usage = "Storage";
        zip2.secure = true;
        zip2.version = "v2";
        zip2.files = 50;
        zip2.tool = "7Zip";
        zip2.compatibility = "Windows";
        zip2.origin = "Russia";
        zip2.status = "Compressed";

        System.out.println("Type: " + zip2.type);
        System.out.println("Format: " + zip2.format);
        System.out.println("Size: " + zip2.size);
        System.out.println("Ratio: " + zip2.ratio);
        System.out.println("Encrypted: " + zip2.encrypted);
        System.out.println("Name: " + zip2.name);
        System.out.println("Weight: " + zip2.weight);
        System.out.println("Usage: " + zip2.usage);
        System.out.println("Secure: " + zip2.secure);
        System.out.println("Version: " + zip2.version);
        System.out.println("Files: " + zip2.files);
        System.out.println("Tool: " + zip2.tool);
        System.out.println("Compatibility: " + zip2.compatibility);
        System.out.println("Origin: " + zip2.origin);
        System.out.println("Status: " + zip2.status);

        System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + zip3.type);
        System.out.println("Format: " + zip3.format);
        System.out.println("Size: " + zip3.size);
        System.out.println("Ratio: " + zip3.ratio);
        System.out.println("Encrypted: " + zip3.encrypted);
        System.out.println("Name: " + zip3.name);
        System.out.println("Weight: " + zip3.weight);
        System.out.println("Usage: " + zip3.usage);
        System.out.println("Secure: " + zip3.secure);
        System.out.println("Version: " + zip3.version);
        System.out.println("Files: " + zip3.files);
        System.out.println("Tool: " + zip3.tool);
        System.out.println("Compatibility: " + zip3.compatibility);
        System.out.println("Origin: " + zip3.origin);
        System.out.println("Status: " + zip3.status);
        zip3.name = "Docs";
        zip3.weight = 0.6;
        zip3.usage = "Office";
        zip3.secure = true;
        zip3.version = "v3";
        zip3.files = 30;
        zip3.tool = "WinRAR";
        zip3.compatibility = "Windows";
        zip3.origin = "Germany";
        zip3.status = "Compressed";
		System.out.println("Type: " + zip3.type);
        System.out.println("Format: " + zip3.format);
        System.out.println("Size: " + zip3.size);
        System.out.println("Ratio: " + zip3.ratio);
        System.out.println("Encrypted: " + zip3.encrypted);
        System.out.println("Name: " + zip3.name);
        System.out.println("Weight: " + zip3.weight);
        System.out.println("Usage: " + zip3.usage);
        System.out.println("Secure: " + zip3.secure);
        System.out.println("Version: " + zip3.version);
        System.out.println("Files: " + zip3.files);
        System.out.println("Tool: " + zip3.tool);
        System.out.println("Compatibility: " + zip3.compatibility);
        System.out.println("Origin: " + zip3.origin);
        System.out.println("Status: " + zip3.status);
		
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + zip4.type);
        System.out.println("Format: " + zip4.format);
        System.out.println("Size: " + zip4.size);
        System.out.println("Ratio: " + zip4.ratio);
        System.out.println("Encrypted: " + zip4.encrypted);
        System.out.println("Name: " + zip4.name);
        System.out.println("Weight: " + zip4.weight);
        System.out.println("Usage: " + zip4.usage);
        System.out.println("Secure: " + zip4.secure);
        System.out.println("Version: " + zip4.version);
        System.out.println("Files: " + zip4.files);
        System.out.println("Tool: " + zip4.tool);
        System.out.println("Compatibility: " + zip4.compatibility);
        System.out.println("Origin: " + zip4.origin);
        System.out.println("Status: " + zip4.status);
        zip4.name = "Videos";
        zip4.weight = 2.0;
        zip4.usage = "Media";
        zip4.secure = false;
        zip4.version = "v4";
        zip4.files = 10;
        zip4.tool = "7Zip";
        zip4.compatibility = "Windows";
        zip4.origin = "USA";
        zip4.status = "Compressed";
		System.out.println("Type: " + zip4.type);
        System.out.println("Format: " + zip4.format);
        System.out.println("Size: " + zip4.size);
        System.out.println("Ratio: " + zip4.ratio);
        System.out.println("Encrypted: " + zip4.encrypted);
        System.out.println("Name: " + zip4.name);
        System.out.println("Weight: " + zip4.weight);
        System.out.println("Usage: " + zip4.usage);
        System.out.println("Secure: " + zip4.secure);
        System.out.println("Version: " + zip4.version);
        System.out.println("Files: " + zip4.files);
        System.out.println("Tool: " + zip4.tool);
        System.out.println("Compatibility: " + zip4.compatibility);
        System.out.println("Origin: " + zip4.origin);
        System.out.println("Status: " + zip4.status);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + zip5.type);
        System.out.println("Format: " + zip5.format);
        System.out.println("Size: " + zip5.size);
        System.out.println("Ratio: " + zip5.ratio);
        System.out.println("Encrypted: " + zip5.encrypted);
        System.out.println("Name: " + zip5.name);
        System.out.println("Weight: " + zip5.weight);
        System.out.println("Usage: " + zip5.usage);
        System.out.println("Secure: " + zip5.secure);
        System.out.println("Version: " + zip5.version);
        System.out.println("Files: " + zip5.files);
        System.out.println("Tool: " + zip5.tool);
        System.out.println("Compatibility:" + zip5.compatibility);
        System.out.println("Origin: " + zip5.origin);
        System.out.println("Status: " + zip5.status);
        zip5.name = "Music";
        zip5.weight = 1.5;
        zip5.usage = "Entertainment";
        zip5.secure = false;
        zip5.version = "v5";
        zip5.files = 40;
        zip5.tool = "WinZip";
        zip5.compatibility = "Windows";
        zip5.origin = "USA";
        zip5.status = "Compressed";
		System.out.println("Type: " + zip5.type);
        System.out.println("Format: " + zip5.format);
        System.out.println("Size: " + zip5.size);
        System.out.println("Ratio: " + zip5.ratio);
        System.out.println("Encrypted: " + zip5.encrypted);
        System.out.println("Name: " + zip5.name);
        System.out.println("Weight: " + zip5.weight);
        System.out.println("Usage: " + zip5.usage);
        System.out.println("Secure: " + zip5.secure);
        System.out.println("Version: " + zip5.version);
        System.out.println("Files: " + zip5.files);
        System.out.println("Tool: " + zip5.tool);
        System.out.println("Compatibility:" + zip5.compatibility);
        System.out.println("Origin: " + zip5.origin);
        System.out.println("Status: " + zip5.status);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + zip6.type);
        System.out.println("Format: " + zip6.format);
        System.out.println("Size: " + zip6.size);
        System.out.println("Ratio: " + zip6.ratio);
        System.out.println("Encrypted: " + zip6.encrypted);
        System.out.println("Name: " + zip6.name);
        System.out.println("Weight: " + zip6.weight);
        System.out.println("Usage: " + zip6.usage);
        System.out.println("Secure: " + zip6.secure);
        System.out.println("Version: " + zip6.version);
        System.out.println("Files: " + zip6.files);
        System.out.println("Tool: " + zip6.tool);
        System.out.println("Compatibility:" + zip6.compatibility);
        System.out.println("Origin: " + zip6.origin);
        System.out.println("Status: " + zip6.status);
        zip6.name = "Backup";
        zip6.weight = 3.0;
        zip6.usage = "Backup";
        zip6.secure = true;
        zip6.version = "v6";
        zip6.files = 100;
        zip6.tool = "WinRAR";
        zip6.compatibility = "Linux";
        zip6.origin = "Germany";
        zip6.status = "Compressed";
		System.out.println("Type: " + zip6.type);
        System.out.println("Format: " + zip6.format);
        System.out.println("Size: " + zip6.size);
        System.out.println("Ratio: " + zip6.ratio);
        System.out.println("Encrypted: " + zip6.encrypted);
        System.out.println("Name: " + zip6.name);
        System.out.println("Weight: " + zip6.weight);
        System.out.println("Usage: " + zip6.usage);
        System.out.println("Secure: " + zip6.secure);
        System.out.println("Version: " + zip6.version);
        System.out.println("Files: " + zip6.files);
        System.out.println("Tool: " + zip6.tool);
        System.out.println("Compatibility:" + zip6.compatibility);
        System.out.println("Origin: " + zip6.origin);
        System.out.println("Status: " + zip6.status);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + zip7.type);
        System.out.println("Format: " + zip7.format);
        System.out.println("Size: " + zip7.size);
        System.out.println("Ratio: " + zip7.ratio);
        System.out.println("Encrypted: " + zip7.encrypted);
        System.out.println("Name: " + zip7.name);
        System.out.println("Weight: " + zip7.weight);
        System.out.println("Usage: " + zip7.usage);
        System.out.println("Secure: " + zip7.secure);
        System.out.println("Version: " + zip7.version);
        System.out.println("Files: " + zip7.files);
        System.out.println("Tool: " + zip7.tool);
        System.out.println("Compatibility:" + zip7.compatibility);
        System.out.println("Origin: " + zip7.origin);
        System.out.println("Status: " + zip7.status);
        zip7.name = "Games";
        zip7.weight = 4.5;
        zip7.usage = "Gaming";
        zip7.secure = false;
        zip7.version = "v7";
        zip7.files = 15;
        zip7.tool = "7Zip";
        zip7.compatibility = "Windows";
        zip7.origin = "USA";
        zip7.status = "Compressed";
		System.out.println("Type: " + zip7.type);
        System.out.println("Format: " + zip7.format);
        System.out.println("Size: " + zip7.size);
        System.out.println("Ratio: " + zip7.ratio);
        System.out.println("Encrypted: " + zip7.encrypted);
        System.out.println("Name: " + zip7.name);
        System.out.println("Weight: " + zip7.weight);
        System.out.println("Usage: " + zip7.usage);
        System.out.println("Secure: " + zip7.secure);
        System.out.println("Version: " + zip7.version);
        System.out.println("Files: " + zip7.files);
        System.out.println("Tool: " + zip7.tool);
        System.out.println("Compatibility:" + zip7.compatibility);
        System.out.println("Origin: " + zip7.origin);
        System.out.println("Status: " + zip7.status);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + zip8.type);
        System.out.println("Format: " + zip8.format);
        System.out.println("Size: " + zip8.size);
        System.out.println("Ratio: " + zip8.ratio);
        System.out.println("Encrypted: " + zip8.encrypted);
        System.out.println("Name: " + zip8.name);
        System.out.println("Weight: " + zip8.weight);
        System.out.println("Usage: " + zip8.usage);
        System.out.println("Secure: " + zip8.secure);
        System.out.println("Version: " + zip8.version);
        System.out.println("Files: " + zip8.files);
        System.out.println("Tool: " + zip8.tool);
        System.out.println("Compatibility:" + zip8.compatibility);
        System.out.println("Origin: " + zip8.origin);
        System.out.println("Status: " + zip8.status);
        zip8.name = "Projects";
        zip8.weight = 1.8;
        zip8.usage = "Development";
        zip8.secure = true;
        zip8.version = "v8";
        zip8.files = 60;
        zip8.tool = "WinZip";
        zip8.compatibility = "Mac";
        zip8.origin = "USA";
        zip8.status = "Compressed";
		System.out.println("Type: " + zip8.type);
        System.out.println("Format: " + zip8.format);
        System.out.println("Size: " + zip8.size);
        System.out.println("Ratio: " + zip8.ratio);
        System.out.println("Encrypted: " + zip8.encrypted);
        System.out.println("Name: " + zip8.name);
        System.out.println("Weight: " + zip8.weight);
        System.out.println("Usage: " + zip8.usage);
        System.out.println("Secure: " + zip8.secure);
        System.out.println("Version: " + zip8.version);
        System.out.println("Files: " + zip8.files);
        System.out.println("Tool: " + zip8.tool);
        System.out.println("Compatibility:" + zip8.compatibility);
        System.out.println("Origin: " + zip8.origin);
        System.out.println("Status: " + zip8.status);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + zip9.type);
        System.out.println("Format: " + zip9.format);
        System.out.println("Size: " + zip9.size);
        System.out.println("Ratio: " + zip9.ratio);
        System.out.println("Encrypted: " + zip9.encrypted);
        System.out.println("Name: " + zip9.name);
        System.out.println("Weight: " + zip9.weight);
        System.out.println("Usage: " + zip9.usage);
        System.out.println("Secure: " + zip9.secure);
        System.out.println("Version: " + zip9.version);
        System.out.println("Files: " + zip9.files);
        System.out.println("Tool: " + zip9.tool);
        System.out.println("Compatibility:" + zip9.compatibility);
        System.out.println("Origin: " + zip9.origin);
        System.out.println("Status: " + zip9.status);
        zip9.name = "Assignments";
        zip9.weight = 0.9;
        zip9.usage = "Study";
        zip9.secure = true;
        zip9.version = "v9";
        zip9.files = 25;
        zip9.tool = "WinRAR";
        zip9.compatibility = "Windows";
        zip9.origin = "India";
        zip9.status = "Compressed";
		System.out.println("Type: " + zip9.type);
        System.out.println("Format: " + zip9.format);
        System.out.println("Size: " + zip9.size);
        System.out.println("Ratio: " + zip9.ratio);
        System.out.println("Encrypted: " + zip9.encrypted);
        System.out.println("Name: " + zip9.name);
        System.out.println("Weight: " + zip9.weight);
        System.out.println("Usage: " + zip9.usage);
        System.out.println("Secure: " + zip9.secure);
        System.out.println("Version: " + zip9.version);
        System.out.println("Files: " + zip9.files);
        System.out.println("Tool: " + zip9.tool);
        System.out.println("Compatibility:" + zip9.compatibility);
        System.out.println("Origin: " + zip9.origin);
        System.out.println("Status: " + zip9.status);
		System.out.println("\n---------------------------------\n");

		System.out.println("Type: " + zip10.type);
        System.out.println("Format: " + zip10.format);
        System.out.println("Size: " + zip10.size);
        System.out.println("Ratio: " + zip10.ratio);
        System.out.println("Encrypted: " + zip10.encrypted);
        System.out.println("Name: " + zip10.name);
        System.out.println("Weight: " + zip10.weight);
        System.out.println("Usage: " + zip10.usage);
        System.out.println("Secure: " + zip10.secure);
        System.out.println("Version: " + zip10.version);
        System.out.println("Files: " + zip10.files);
        System.out.println("Tool: " + zip10.tool);
        System.out.println("Compatibility:" + zip10.compatibility);
        System.out.println("Origin: " + zip10.origin);
        System.out.println("Status: " + zip10.status);
        zip10.name = "Reports";
        zip10.weight = 1.1;
        zip10.usage = "Office";
        zip10.secure = true;
        zip10.version = "v10";
        zip10.files = 35;
        zip10.tool = "7Zip";
        zip10.compatibility = "Windows";
        zip10.origin = "UK";
        zip10.status = "Compressed";
		System.out.println("Type: " + zip10.type);
        System.out.println("Format: " + zip10.format);
        System.out.println("Size: " + zip10.size);
        System.out.println("Ratio: " + zip10.ratio);
        System.out.println("Encrypted: " + zip10.encrypted);
        System.out.println("Name: " + zip10.name);
        System.out.println("Weight: " + zip10.weight);
        System.out.println("Usage: " + zip10.usage);
        System.out.println("Secure: " + zip10.secure);
        System.out.println("Version: " + zip10.version);
        System.out.println("Files: " + zip10.files);
        System.out.println("Tool: " + zip10.tool);
        System.out.println("Compatibility:" + zip10.compatibility);
        System.out.println("Origin: " + zip10.origin);
        System.out.println("Status: " + zip10.status);
		System.out.println("\n---------------------------------\n");

    }
}